### ISSUE TITLE
Function argument and newly allocated block should not alias

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#100]

**Comment by aqjune** [comment]
This contains two things to consider:
(1) Function arguments that are pointer types should not have block ids that are newly allocated after function began.
```
def void @f(i32* %p) {
%q = call malloc(i32 4) ; p.bid cannot be q.bid
}
```
This can be efficiently encoded by adding preconditions saying that function pointer arguments have upper bound of block id.

(2) The initial memory should not have pointer bytes with block ids newly allocated after beginning.
```
def void @f(i32** %p) {
%q = call malloc(i32 4)
%p2 = load i32*, i32** %p ; p2.bid cannot be q.bid
}
```
One possible solution is to use quantification.
We can say that, for all byte b inside the block that p points to, b's block id less than its upper bound.

**Comment by aqjune** [comment]
Just realized that we don't need upper bound of block id to do (1) and (2), because we already have local_bid and nonlocal_bid.
Making malloc be a local block will resolve (1). I guess unescaped malloc is equivalent to alloca (without behavior w.r.t. free call and possible null pointer return), so I think this is okay.
I'll open a PR that does this.

**Comment by nunoplopes** [comment]
I believe it's all good now. Closing, thanks!

**Comment by aqjune** [comment]
(2) is not resolved, but I'll make a new issue dedicated for that later.
