### ISSUE TITLE
make undef inputs default to off

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#1001]
in this post 
https://www.npopov.com/2024/01/01/This-year-in-LLVM-2023.html
Nikita says:
**Undefined behavior in LLVM comes in two flavors: One of those is immediate undefined behavior, which basically works the same as in C, and poison values, which get propagated by most operations and only turn into immediate undefined behavior in certain contexts, for example when you try to branch on them.**
I take this as a sign that we can turn off undef inputs in Alive2, basically just flipping the sense of the `--disable-undef-inputs` flag. This will reduce the number of complaints that we get about timeouts and also, nobody wants to see undef-related bugs. I'm happy to do the pull request for this. We could even add a little warning to the effect of "This result is based on the assumption that inputs are not undef"

**Comment by nunoplopes** [comment]
I think it's too early for this. Let's revisit once we change the memory model.
