### ISSUE TITLE
Add support for gep's nuw nusw attributes

### ISSUE THREAD

**Issue by Hels15** [AliveToolkit/alive2#1033]
This pr implements nuw and nusw flags for the GEP instruction: https://github.com/llvm/llvm-project/pull/90824
After the PR is merged we can implement it in alive2.

I started to work on this so I will keep this thread active, although I can't do much until the PR is merged.

**Comment by nikic** [comment]
The PR has been merged.

**Comment by nunoplopes** [comment]
see PR https://github.com/AliveToolkit/alive2/pull/1047
