### ISSUE TITLE
Incorrect handling of poison values

### ISSUE THREAD

**Issue by artagnon** [AliveToolkit/alive2#1038]
Input to Alive2:

```llvm
define i16 @src() {
  %and = and i16 poison, 0
  ret i16 %and
}

define i16 @tgt() {
  ret i16 3
}
```

Changing `ret i16 3` to any other return value has no impact on correctness.

Handy link: https://alive2.llvm.org/ce/z/2KR-wy

**Comment by nunoplopes** [comment]
Right, because poison can be replaced by any value.
Alive2 is correct.
