### ISSUE TITLE
LLVM version

### ISSUE THREAD

**Issue by Ryuanxue** [AliveToolkit/alive2#1040]
Hello,

I am trying to use this project, and I need to utilize Translation Validation. According to the building instructions, I should compile LLVM first and then reconfigure Alive2, correct? I would like to know the specific versions of LLVM and Clang required for this project. I look forward to your response. Thank you very much.

**Comment by regehr** [comment]
you should build Alive2 against the main branch of Clang/LLVM from the git repo
