### ISSUE TITLE
Why are we reinitializing the variable 'e'?

### ISSUE THREAD

**Issue by IamYJLee** [AliveToolkit/alive2#1069]
https://github.com/AliveToolkit/alive2/blob/master/tools/transform.cpp#L597

After removing this code, I haven't encountered any specific problems. 
Can anyone explain why we're reinitializing the variable 'e'?

**Comment by nunoplopes** [comment]
It's to reduce memory usage. `expr()` creates an empty/invalid expression that doesn't occupy memory.
