### ISSUE TITLE
Is "and i32 undef, 1" an zero?

### ISSUE THREAD

**Issue by IamYJLee** [AliveToolkit/alive2#1071]
https://alive2.llvm.org/ce/z/9SGjhN

In the target source, if `%a` is undef, why is `%#0` a zero? Isn't the result of `and i32 undef, 1` supposed to be undef?

According to [the LLVM Language Reference - undefined-values](https://llvm.org/docs/LangRef.html#undefined-values), 
> it is safe to assume that all bits of the ‘undef’ could be 0, and optimize the ‘and’ to 0.

Is this optimization based on that assumption?

**Comment by nunoplopes** [comment]
What the counterexample is telling you is that target can return 0, while the source cannot.
The counterexample doesn't show undef, but rather concrete values for each register.
