### ISSUE TITLE
[Q] if local-block id  and offset is zero, example output is null.

### ISSUE THREAD

**Issue by IamYJLee** [AliveToolkit/alive2#1080]
The example output `Pointer(local, block_id=0, offset=0)` results in null, which seems incorrect. I discovered that by slightly modifying the operator overloading function (`operator<<`) of the Pointer class, i can correctly output a non-null `Pointer(local, block_id=0, offset=0)`.

Is there a reason to output `null`?

## Before
```
Source:
ptr %a = null
ptr %b = pointer(local, block_id=1, offset=0)
ptr %y = pointer(local, block_id=1, offset=0)
i1 %cmp = #x1 (1)
```
## After
```
Source:
ptr %a = pointer(local, block_id=0, offset=0)
ptr %b = pointer(local, block_id=1, offset=0)
ptr %y = pointer(local, block_id=1, offset=0)
i1 %cmp = #x1 (1)
```

**Comment by nunoplopes** [comment]
We use the convention that block=0 & offset=0 is null. We need to represent it somehow.
