### ISSUE TITLE
Backwards compatibility with earlier LLVM versions

### ISSUE THREAD

**Issue by can-leh-emmtrix** [AliveToolkit/alive2#1084]
We are interested in using alive2 with LLVM 14. I currently have a prototype implementation that adds`#if`s to the relevant parts of the `llvm2alive_` visitor. Could this feature be upstreamed? From what I can tell the main changes are the addition of new flags & intrinsics as well as moving to opaque pointers. Are you aware of any important changes to the existing semantics?

**Comment by nunoplopes** [comment]
No, sorry, this is not something I'm willing to support.
LLVM breaks the API all the time, and there have been minor semantic changes as well. It's just too much effort for something that most people don't care about.
