### ISSUE TITLE
Same IR Code, But Verification Fail

### ISSUE THREAD

**Issue by IamYJLee** [AliveToolkit/alive2#1087]
I found something I don't understand while looking into the case of `ERROR: Source and target don't have the same return domain.`
Why did the verification fail?

https://alive2.llvm.org/ce/z/SBacDP

**Comment by nunoplopes** [comment]
reduced test case:
```llvm
declare void @use_writeonly(ptr) memory(write)

define void @src() {
  %src = alloca i32, align 4
  %dest = alloca i32, align 4
  call void @use_writeonly(ptr %dest)
  ret void
}

define void @tgt() {
  %src = alloca i32, align 4
  %dest = alloca i32, align 4
  call void @use_writeonly(ptr %dest)
  ret void
}
```

**Comment by IamYJLee** [comment]
I would like to try to fix this problem. Could I get some help to do so?

**Comment by nunoplopes** [comment]
It's hard to give any concrete advise. The bug can be either in state,cpp (addFnCall), in memory.cpp (refinement of input memory for the function), or in pointer.cpp (refinement of input ptrs to the function).

**Comment by IamYJLee** [comment]
Thank you for advise.
I am trying to fix this problem. 
I saw a difference between the source and target in the function domain.

Source :
```
domain = (or (and |@use_writeonly#ptr!void#ub!7| |@use_writeonly#ptr!void#noreturn!8|)
    (and |@use_writeonly#ptr!void#ub!7|
         (not |@use_writeonly#ptr!void#noreturn!8|)))
```

Target: 
```
domain = (or (and |@use_writeonly#ptr!void#ub!7|
         (ite (= #b1 ((_ extract 1 1) (blk_kind #b1)))
              (and (= #b01 (blk_kind #b1)) (= #x4 (blk_size #b1)))
              (bvule (blk_size #b1) #x4))
         |@use_writeonly#ptr!void#noreturn!8|)
    (and |@use_writeonly#ptr!void#ub!7|
         (not |@use_writeonly#ptr!void#noreturn!8|)
         (ite (= #b1 ((_ extract 1 1) (blk_kind #b1)))
              (and (= #b01 (blk_kind #b1)) (= #x4 (blk_size #b1)))
              (bvule (blk_size #b1) #x4))))
```

And if the `memory` function attribute is removed, this problem does not occur. 
So I am debugging the `State::addFnCall` function.

**Comment by IamYJLee** [comment]
@nunoplopes 

I analyzed why the following condition are applied to the domain of `target`.
```
(ite (= #b1 ((_ extract 1 1) (blk_kind #b1)))
              (and (= #b01 (blk_kind #b1)) (= #x4 (blk_size #b1)))
              (bvule (blk_size #b1) #x4))
```

I confirmed that these condition arise from the code below because the values for `local_blk_kind`, `local_blk_size`, and `local_blk_align` of the memory are empty.

https://github.com/AliveToolkit/alive2/blob/9f7f1f103f83b0dead7143051bbed7822876a5ef/ir/state.cpp#L920-L922

I confirmed that `local_blk_kind` is added during the processing of the alloc commands for `%src` and `%dest`.
I need some guidance on which part I should look into further.

**Comment by nunoplopes** [comment]
> I confirmed that these condition arise from the code below because the values for `local_blk_kind`, `local_blk_size`, and `local_blk_align` of the memory are empty.

Sounds like the State::addFnCall is producing an empty memory for some reason. Check the emplace that stores the call information. It creates the memory state after the call & etc.

**Comment by IamYJLee** [comment]
I found the cause of the incorrect `local_blk_kind`, `local_blk_size`, and `local_blk_align` values. The problem comes from the fact that the `refinedBy` function is member of the `FnCallInput` structure, not the `State` class. 
I looked into how the `fn_call_data` structure is created from the `State` class and found that when the `memory attribute` is present, the `memory.dupNoRead()` function is called. 

https://github.com/AliveToolkit/alive2/blob/9f7f1f103f83b0dead7143051bbed7822876a5ef/ir/state.cpp#L1107-L1114

However, this function doesn't copy the values for `local_blk_kind`, `local_blk_size`, and `local_blk_align`.

https://github.com/AliveToolkit/alive2/blob/9f7f1f103f83b0dead7143051bbed7822876a5ef/ir/memory.cpp#L1452-L1457

Also, if the `memory attribute` exists, is attrs.mem #b0101010101 correct?"
