### ISSUE TITLE
sameness up to UB

### ISSUE THREAD

**Issue by DaKnig** [AliveToolkit/alive2#1088]
is it possible to check whether src and tgt are same "up to UB"?
currently for what I am constructing, alive2 returns one of three results (if it doesnt timeout):
- they are the same
- not same, plus counterexample
- one is more defined than the other

I'd like to omit the third, as in, how can I tell alive2 to find all inputs for which the output is defined and different?

**Comment by nunoplopes** [comment]
Right now you can't because it does the queries in sequence. First it checks that source is at least as UB as the target.
If you want, you can flip the orders of the queries in tools/transform.cpp (search for CHECK).

**Comment by DaKnig** [comment]
yeah flipping the order will do it. can you please help me change it locally?

**Comment by nunoplopes** [comment]
Just move this line up: https://github.com/AliveToolkit/alive2/blob/5e88326d85d92adfda410a9891fb759edfb6952a/tools/transform.cpp#L706-L707

**Comment by DaKnig** [comment]
should I just replace `dom && !value_cnstr` with true then?

**Comment by nunoplopes** [comment]
> should I just replace `dom && !value_cnstr` with true then?

no, you need to move the definitions of those variables as well.
