### ISSUE TITLE
Assume initialized memory

### ISSUE THREAD

**Issue by DaKnig** [AliveToolkit/alive2#1099]
I'd like to say that "both src and tgt take a struct (by value)" and in C that is equivalent to the assumption that all values there are not poison nor undef (in C it is UB to call by value with uninitialized memory, UB in caller side), how can I do it?

**Comment by nunoplopes** [comment]
Could you give an example? I'm not sure I understand what you want.
BTW, the `-disable-poison-input` guarantees that the initial memory is not poison. Is that what you want?

**Comment by DaKnig** [comment]
oh that was the option I was missing! thanks!
