### ISSUE TITLE
malloc can return null

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#110]
Currently it is assumed that malloc always returns a valid pointer, but malloc can return null in runtime, meaning that refinement may not hold.

We can make malloc nondeterministically return null, but this will make many practical programs raise UB.

One possible solution is to support a flag such as `malloc_can_return_null` & run TV with the flag set as true and false.

**Comment by nunoplopes** [comment]
Actually LLVM and gcc assume that malloc cannot return null. AFAIR LLVM attaches a nonnull tag to the return value.

**Comment by aqjune** [comment]
LLVM seems to attach `dereferenceable_or_null` to malloc: https://godbolt.org/z/vTpHQ_ .
`new` operator attaches `dereferenceable` (because it raises bad_alloc if there is no storage), and it has nonnull as well.

I think we need a test to see what happens if  malloc is defined as returning null nondeterministically. Having a command line flag that switches the semantics will be helpful for the test, I believe.

**Comment by aqjune** [comment]
Implementing `dereferenceable` and `dereferenceable_null` seems interesting; I'll do that. :) Given
```
%ptr = call dereferenceable(4) i8* @new(i64 4)
```
, we can say that `%ptr` is dereferenceable (with 4 bytes) at this program point.
I have #112 ongoing, and #106 and #108 to investigate unit test changes; I can do this dereferenceable thingy after these.

**Comment by aqjune** [comment]
As this is addressed by #114, I'll open a separate issue for dereferenceable thingy.
