### ISSUE TITLE
fails when tbaa metadata exists

### ISSUE THREAD

**Issue by DaKnig** [AliveToolkit/alive2#1103]
https://alive2.llvm.org/ce/z/dTy6a-

if you remove the tbaa metadata in line 5 then ths suddenly works.
I'd rather have it working and ignoring tags it does not understand, than fail with the error "ERROR: Unsupported metadata: 1"

**Comment by DaKnig** [comment]
it could also be cool if it could omit where it found the error that bothers it, like line number

**Comment by nunoplopes** [comment]
This is the intended design. If we just ignore stuff we don't know, then false positives will start showing up.
