### ISSUE TITLE
dumping the smtlib code

### ISSUE THREAD

**Issue by DaKnig** [AliveToolkit/alive2#1112]
how can I dump what its trying to currently prove? maybe I could for example on long runs insert SLOT or whatever other tech , for my own use, to help it prove stuff? I have some proofs that take quite long (hours)

**Comment by nunoplopes** [comment]
`-smt-verbose` dumps each query to the screen
`-smt-bench=<directory>` creates an smt2 file per query in the specified directory

**Comment by DaKnig** [comment]
is it possible to instruct it to also just quit after dumping said query?

**Comment by nunoplopes** [comment]
Alive2 stops issuing queries on the first timeout of each program. If you want any other behavior, you must change tools/transform.cpp
