### ISSUE TITLE
Could you please provide advice on the issue of long processing times related to memcpy?

### ISSUE THREAD

**Issue by IamYJLee** [AliveToolkit/alive2#1146]
If the source code contains many `memcpy` instructions, `Z3_substitute_vars` in `Memory::toSMT` takes a long time to process. How can I solve this problem? Here is the profiling data for this case.

![image](https://github.com/user-attachments/assets/53153d88-1f87-4534-bd6b-319782010ff9)

**Comment by nunoplopes** [comment]
Can you please test this patch for Z3: https://github.com/Z3Prover/z3/pull/7481 ?
Thanks!

**Comment by IamYJLee** [comment]
Thank you for your response!

> I've introduced a check to bypass substitute() when memory is getting full. Please let me know if that improves performance.

I am currently running tests using a specific version of LLVM. Therefore, I plan to cherry-pick the patch to proceed with the testing. Is the patch you mentioned the one with the commit hash https://github.com/AliveToolkit/alive2/commit/84196acbaf7fea1faa4c5b1d60f03a773647a980?

> Can you please test this patch for Z3: https://github.com/Z3Prover/z3/pull/7481 ?

And I will test the Z3 solver after applying the patch mentioned above.

**Comment by nunoplopes** [comment]
No, cherrypick this one: https://github.com/AliveToolkit/alive2/commit/2f7ede89ae99d2f2ee40dd749f5b94e88c20fdc9

**Comment by nunoplopes** [comment]
I think the problem is solved. My benchmarking shows >10x speedups in large functions.
