### ISSUE TITLE
Support dereferenceable_or_null, dereferenceable tag

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#117]
```
%ptr = call dereferenceable(4) i8* @f(i64 4)
```
For the semantics of this flag, we have two choices:
(1) If the returned pointer is not dereferenceable with 4-byte access, it raises UB
(2) If not dereferenceable, `%ptr` is poison.
It is not specified in LangRef:
```
dereferenceable(<n>)

This indicates that the parameter or return pointer is dereferenceable.
This attribute may only be applied to pointer typed parameters.
A pointer that is dereferenceable can be loaded from speculatively without a risk of trapping.
The number of bytes known to be dereferenceable must be provided in parentheses.
It is legal for the number of bytes to be less than the size of the pointee type.
The nonnull attribute does not imply dereferenceability (consider a pointer to one element past the end of an array), however dereferenceable(<n>) does imply nonnull in addrspace(0) (which is the default address space).
```

**Comment by LebedevRI** [comment]
By `@new`, do you mean the C++'s `new`? (i.e. ` @_Znwm`)
It is throwing, so we can safely assume that C++'s throwing `new` returns dereferenceable pointer.

**Comment by aqjune** [comment]
@LebedevRI yep, it is C++'s `new`, and it should be allowed that `dereferenceable` tag can be safely added to the function. :)

**Comment by aqjune** [comment]
@LebedevRI I just understood what you were asking, and found the text was a bit misleading :/ I updated the contents.
The function `@new` was used there because I did copy-and-paste from a llvm test that adds `dereferenceable` to the `@_Znwm` call (and replaced `@_Znwm` with `@new`).

**Comment by aqjune** [comment]
I'll give it a quick try for this - I'll let it yield poison, implementing this wouldn't be hard. If the result makes sense, I'll make PR.

**Comment by aqjune** [comment]
Turns out that it is nontrivial to implement this right now; for known functions like malloc/etc, they are not FnCall; for unknown functions its semantics is not implemented yet.

**Comment by nunoplopes** [comment]
Closing this as we've ways to track what's missing from LLVM.
