### ISSUE TITLE
alive-tv fails with src/tgt having same code when malloc is involved

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#120]
```
$ pwd
/Users/juneyounglee/alive2/tests/alive-tv/memory
$ ../../../build/alive-tv malloc-null.src.ll malloc-null.src.ll 

----------------------------------------
define i64 @malloc_null() {
%0:
  %ptr = malloc i64 1
  %i = ptrtoint * %ptr to i64
  ret i64 %i
}
=>
define i64 @malloc_null() {
%0:
  %ptr = malloc i64 1
  %i = ptrtoint * %ptr to i64
  ret i64 %i
}
Transformation doesn't verify!
ERROR: Value mismatch

Example:

Source:
* %ptr = pointer(local, block_id=256, offset=0)
i64 %i = #x0000000000001000 (4096)

Target:
* %ptr = pointer(local, block_id=256, offset=0)
i64 %i = #x0000002000000000 (137438953472)
Source value: #x0000000000001000 (4096)
Target value: #x0000002000000000 (137438953472)
```
The reason is because the addresses of local blocks are not quantified?
Bug found by @Dongjoo-Kim

**Comment by aqjune** [comment]
BTW, what do you think about making `ninja check` run `alive-tv` with same files (e.g. alive-tv <a.ll> <a.ll>)?

**Comment by nunoplopes** [comment]
> BTW, what do you think about making ninja check run alive-tv with same files (e.g. alive-tv <a.ll> <a.ll>)?

That's a good idea, yes!

**Comment by nunoplopes** [comment]
There's this new test failure that might be related: `InstCombine/all-bits-shift.ll`

**Comment by aqjune** [comment]
`InstCombine/all-bits-shift.ll` was related with #119 . I made PR  #121 that resolves it.

Regarding the identity check, I'll make a PR that also contains fix to the `malloc-null.src.ll` bug. :)

**Comment by nunoplopes** [comment]
This is working now. Thanks for discovering this issue!
