### ISSUE TITLE
Add per-input vector element undef/poison support

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#136]
Right now it's either all elements poison/undef or none.
Plus audit implementation of -disable-undef/poison-input for vectors.

**Comment by aqjune** [comment]
Relevant input: cmpv2f32()  vs rrcmpv2f32() in https://bugs.llvm.org/show_bug.cgi?id=32078 ; it should fail, but succeeds due to this issue

**Comment by aqjune** [comment]
Possible solutions that I have in my mind..

(1) maintain an array of TyVars?

(2) Explode aggregate arguments?

**Comment by nunoplopes** [comment]
The solution is to have an arbitrary mask that can either pick the undef var or the input value. Right now it's a boolean; it should be a bit-vector mask + OR instead.  Not complicated; though perf may suffer substantially.

**Comment by nunoplopes** [comment]
Fixed here: https://github.com/AliveToolkit/alive2/commit/ad4479966563cafe9b1157963a9198f19756b48b
