### ISSUE TITLE
StateValue's non_poison has an inverted value when converted to BV

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#145]
```
StateValue Type::toBV(StateValue v) const {
  expr val = toBV(move(v.value));
  auto bw = val.bits();
  return { move(val),
           expr::mkIf(v.non_poison, expr::mkUInt(0, bw), expr::mkInt(-1, bw)) };
}
```

Is this intended? I'll add a comment about this to `non_poison` field in the upcoming PR then.

**Comment by nunoplopes** [comment]
It was intended because being non-poison should be the common case, hence 0. I didn't measure the effect, though
Anyway, the users to StateValue aren't suppose to notice the difference. It's all hidden under these toBV/fromBV APIs. It should, at least.

**Comment by aqjune** [comment]
The non-poison value was linked to Byte's non-poison bits definition because Byte was created from the result of toBV API.
I'll add a comment to Byte's definition instead.
