### ISSUE TITLE
Add SMT rewrite: (bvule foo const) -> true

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#147]
Add rewrite for things like:
```
(bvule (concat #b000000000000000000000000000 foo)
       #x0000001f)
```

This formula is `true`.

Maybe extend the function `min_leading_zeros()` to compute known 0s/1s.

**Comment by regehr** [comment]
yikes, we need our own instcombine??

**Comment by regehr** [comment]
we already have a knownbits in souper for pruning synthesis candidates. what if we moved this infrastructure to alive2? then it could be used for multiple purposes.

**Comment by nunoplopes** [comment]
We need the MLIR thing so we can reuse instcombine across LLVM IR, SMT, and everything else :)

**Comment by LebedevRI** [comment]
> We need the MLIR thing so we can reuse instcombine across LLVM IR, SMT, and everything else :)

Now that MLIR is imported into LLVM project, is there anything specific in mind?
I'd maybe like to help if possible..

**Comment by nunoplopes** [comment]
> > We need the MLIR thing so we can reuse instcombine across LLVM IR, SMT, and everything else :)
> 
> Now that MLIR is imported into LLVM project, is there anything specific in mind?
> I'd maybe like to help if possible..

I don't have anything concrete in mind, just ideas. I know @regehr & @zvonimir have more thoughts on this as well.
Our thinking was to have a language to specify the semantics of MLIR idioms, such that optimizations could work with any idiom. It's in the same spirit of what folks are working on ATM, but a bit further. Right now the semantics of idioms' instructions is specified using attributes like in LLVM (readonly, no memory access, etc), but that is insufficient to produce e.g. an instcombine that works for multiple idioms.
There's one Google folk working on the rewriter for MLIR (essentially the InstCombine framework for MLIR), but the rules it takes as inputs are still specific to one idiom.
So right now I don't think we have any specific set of tasks, it's more exploratory. But if you have time/interest, we would be happy to discuss further :)

**Comment by LebedevRI** [comment]
> > > We need the MLIR thing so we can reuse instcombine across LLVM IR, SMT, and everything else :)
> > 
> > 
> > Now that MLIR is imported into LLVM project, is there anything specific in mind?
> > I'd maybe like to help if possible..
> 
> I don't have anything concrete in mind, just ideas. I know @regehr & @zvonimir have more thoughts on this as well.

> Our thinking was to have a language to specify the semantics of MLIR idioms, such that optimizations could work with any idiom.

And by language you don't mean simply lowering to Z3 like it is currently being done in [alive2 llvm_util/llvm2alive.cpp](https://github.com/AliveToolkit/alive2/blob/38055f48787c9ba8b239ea43db514af0f8f0996f/llvm_util/llvm2alive.cpp) / [alive2 smt/expr.cpp](https://github.com/AliveToolkit/alive2/blob/38055f48787c9ba8b239ea43db514af0f8f0996f/smt/expr.cpp) / [souper lib/Extractor/KLEEBuilder.cpp
](https://github.com/google/souper/blob/c0e8973bbb4bb2324ae76fde09bff0629f3964e4/lib/Extractor/KLEEBuilder.cpp) (and raising, like in [souper lib/Codegen/Codegen.cpp](https://github.com/google/souper/blob/c0e8973bbb4bb2324ae76fde09bff0629f3964e4/lib/Codegen/Codegen.cpp))?

> It's in the same spirit of what folks are working on ATM, but a bit further. Right now the semantics of idioms' instructions is specified using attributes like in LLVM (readonly, no memory access, etc), but that is insufficient to produce e.g. an instcombine that works for multiple idioms.

Right, of course.

> There's one Google folk working on the rewriter for MLIR (essentially the InstCombine framework for MLIR), but the rules it takes as inputs are still specific to one idiom.

Interesting.
I don't know about that, but i'd guess it's in the similar spirit to the GISelCombiner

> So right now I don't think we have any specific set of tasks, it's more exploratory. But if you have time/interest, we would be happy to discuss further :)

I do have _some_ interest in this, yes.

**Comment by nunoplopes** [comment]
I think lowering to Z3 is a good starting point, though probably a bit too low level. Alive's expr.h language is slightly higher level.

Some links to MLIR's rewriting engine:
https://github.com/llvm/llvm-project/blob/master/mlir/docs/GenericDAGRewriter.md
https://github.com/llvm/llvm-project/blob/master/mlir/docs/QuickstartRewrites.md
