### ISSUE TITLE
alive-tv crash in debug mode

### ISSUE THREAD

**Issue by pranavk** [AliveToolkit/alive2#159]
Came across this llvm file while playing with alive-tv:
```
; ModuleID = '/home/pranavk/uiuc/seanopt/functions/FvppiE/0/1591417.bc'
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-musl"

%0 = type opaque
%1 = type opaque
%2 = type opaque

; Function Attrs: norecurse sspstrong uwtable
define void @0(%0* nocapture %0, %1* readonly %1, i32 %2) #0 align 2 {
  %4 = zext i32 %2 to i64
  %5 = or i64 %4, -281474976710656
  %6 = inttoptr i64 %5 to %2*
  %7 = bitcast %0* %0 to %2**
  store %2* %6, %2** %7, align 8
  ret void
}

attributes #0 = { norecurse sspstrong uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="4" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
```

Opaque globals are not supported yet but when I run alive-tv (Release build) on this file, it verifies without any problem, even though according to alive IR printer, the generated IR seems malformed:

```
define void @(* %0, * %1, i32 %2) {
%3:
  %4 = zext i32 %2 to i64
  %5 = or i64 %4, -281474976710656
  %6 = int2ptr i64 %5 to * 
  %7 = bitcast * %0 to *
  store * %6, * %7, align 8
  ret void
}
```
Shouldn't we complain here instead of outputting transformation is correct?

**Comment by nunoplopes** [comment]
Uhm, not sure there's anything wrong here. Alive doesn't distinguish between pointer types, hence here the translation seems fine.
Or am I missing something?

**Comment by pranavk** [comment]
yeah, i didn't look close enough before but this makes sense now. This specific example however failed on a debug build for me due to an assertion failure. Could be worth investigating.

**Comment by nunoplopes** [comment]
ok, thanks, I'll have a look

**Comment by pranavk** [comment]
ah, okay. So it all boils down to int2ptr is not being implemented yet. `%6` above returns a nullptr and then `store` tries to store into it which makes one of the assertion go wrong in debug build.

**Comment by aqjune** [comment]
For implementation of `inttoptr`, there are two choices for its semantics:
(1) Use naive semantics: lookup the memory & find the memory block that the integer points into
(2) Implement the twin-memory model.
My suggestion for the plan is that I can implement (2) first (which will involve addition of a physical pointer), then adding a command line flag that turns off usage of physical pointers will support (1).
