### ISSUE TITLE
Check encoding of global variables with undef initializer

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#170]
This is likely wrong due to order of quantifiers.

**Comment by aqjune** [comment]
This would be problematic for constant global vars only, as plain global vars' initial values are never used.

**Comment by aqjune** [comment]
What about interpreting undef initializer for global constant as poison? Local blocks are already initialized with poison value, not undef value.

**Comment by nunoplopes** [comment]
Also, memory passed as argument must be allowed to be undef.

**Comment by aqjune** [comment]
Would putting `store undef, @glbvar` at the initializer basic block work? It is being added at #187 .

**Comment by nunoplopes** [comment]
> Would putting `store undef, @glbvar` at the initializer basic block work? It is being added at #187 .

that helps, yes. But then we still need to handle the remaining non-local blocks and non-initialized globals.

**Comment by aqjune** [comment]
Should we support undef bit? I guess we should, because there are loads like `load i5`.
If a program does not include such type, having a notion of undef byte would make sense, I think. `bytesToValue` can create a new quantifier whenever the byte is undef.

**Comment by nunoplopes** [comment]
Right now we can't mix global constants initialized with undef and memcpy.
This hits an issue in Z3: https://github.com/Z3Prover/z3/issues/2792

As seen, for example, in `Transforms/GVN/pr17732.ll`
