### ISSUE TITLE
Refinement of memory with constant globals (unused in tgt)

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#178]
This example fails:
```
@x = constant i8 3

define i8 @f() {
  %v = load i8, * @x, align 1
  ret i8 %v
}
=>
define i8 @f() {
  ret i8 3
}
```

This is because src writes the constant to memory, but tgt doesn't because the variable isn't used.
Two options come to mind:
 - Have tgt reuse the initialized memory from src
 - Store list of idxs stored in each program and just check for those (essentially unroll the quantifier by hand). This avoids constant data "for free".

Or a mix of both. First option has the advantage that it saves time re-initializing all globals. On the other hand, it increases size of initial memory. Though then it's shared with the src program, so syntactically equal (good).

**Comment by aqjune** [comment]
I think we need support the inversed case as well:
```
define i8 @f() {
  ret i8 3
}
=>
@x = constant i8 3

define i8 @f() {
  %v = load i8, * @x, align 1
  ret i8 %v
}
```
We can generate the initial memory separately by aggregating global variables in both src and tgt, and then let both src and tgt start at that.

**Comment by aqjune** [comment]
At 21f25b5, there are 38 mismatch in memory errors in LLVM unit tests.
I'll start with implementing the first option and check how many of them disappear.

**Comment by aqjune** [comment]
In order to correctly implement the first option, copying memory should be done per global variable, because definitions of global variables may differ.
```
@x = global i32
...
=>
@x = constant i32 0
...
```
In terms of implementation cost, the second option seems to be more lightweight.

**Comment by aqjune** [comment]
For the second option, I implemented it at here: https://github.com/aqjune/alive2/commit/e65d7b89da5e6807aca2a38582a1f4dbf96b2593

**Comment by aqjune** [comment]
Resolves 10 unit test failures, 14 Mismatch in memory error, +3 Value mismatch / +1 Source is more defined than target

**Comment by nunoplopes** [comment]
This is fixed now.
The inverse problem is tracked in https://github.com/AliveToolkit/alive2/issues/212
