### ISSUE TITLE
'x86_fp80' support

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#196]
In https://bugs.llvm.org/show_bug.cgi?id=44188, it would be useful to proof that https://godbolt.org/z/vJPBNd is an miscompilation.
But currently there is no support for the type in question:
```
$ ./alive-tv /tmp/{old,new}.ll 
ERROR: Unsupported type: x86_fp80
ERROR: Unsupported instruction:   store x86_fp80 0xK3FFF8000000000000000, x86_fp80* %1, align 16
ERROR: Could not translate 'main' to Alive IR
Summary:
  0 correct transformations
  0 incorrect transformations
  1 errors
```

**Comment by nunoplopes** [comment]
This is non-trivial to implement because Z3 doesn't support x86's FP80 type. We could emulate it by catching all special cases, but this is quite low in our priority list (which is quite long still..).
We do have several scripts to track missing LLVM features, so I'm closing this report for now.
