### ISSUE TITLE
Generating counterexamples without undef?

### ISSUE THREAD

**Issue by avanhatt** [AliveToolkit/alive2#201]
I'm giving a lecture on Alive, and for the purpose of a demo I want to show a counterexample for an obviously wrong optimization.  I'd like the first example to not use `undef`. However, using ` -disable-undef-input`, I still get `undef` in the output:

```
$ ./build/alive  -disable-undef-input -disable-poison-input tests/incorrect-add.opt 
Processing tests/incorrect-add.opt..

----------------------------------------
Name: IncorrectAdd
  %r = add %a, 1
  ret %r
=>
  %r = %a
  ret %r

ERROR: Value mismatch for i1 %r

Example:
i1 %a = undef
Source value: undef
Target value: undef
```
(This is following the README build suggestions, from ToT master 12/3/19)

I would expect `-disable-undef-input` to prohibit `i1 %a = undef` from being part of the counterexample. Am I misunderstanding this flag? Is there a way to force defined/concrete counterexamples?

Thanks!

**Comment by nunoplopes** [comment]
The flag `-disable-undef-input` does exactly what you expect: it disallows inputs to be undef. In this case, `%a` isn't allowed to be undef or poison; it has to be a concrete value.

See this example:
```
$ ./alive foo.opt
Processing foo.opt..

----------------------------------------
  %r = mul i8 %a, 2
  ret i8 %r
=>
  %r = add %a, %a
  ret %r

ERROR: Value mismatch for i8 %r

Example:
i8 %a = undef
Source value: #x00 (0)  [based on undef value]
Target value: #x01 (1)
```

It fails because undef can take any value each time is read. But if we disable undef inputs, the transformation becomes correct:

```
$ ./alive -disable-undef-input foo.opt
Processing foo.opt..

----------------------------------------
  %r = mul i8 %a, 2
  ret i8 %r
=>
  %r = add %a, %a
  ret %r

Done: 1
Optimization is correct!
```

What's happening in your example is a bug in the counterexample printing. We have a test to check if the optimization is wrong for any value we assign to a variable. We use this test to say the variable is undef.
In this case, the transformation is incorrect for any value we give to `%a`, so it prints `undef`. But this is wrong. We need to distinguish these two cases.
We have a couple more bugs related with printing counterexamples. I'll have a look soonish. Thanks for the report!

**Comment by nunoplopes** [comment]
BTW, you have a few slide decks here on Alive: http://web.ist.utl.pt/nuno.lopes/pres/
Feel free to let us know if you have questions :)

**Comment by avanhatt** [comment]
Got it, thank you for the explanation (and the pointer to the slides)!

**Comment by avanhatt** [comment]
Hi @nunoplopes, apologies for a hopefully very silly/quick question: what is the new syntax for constants in Alive2?

I'm trying to run the example PR20186 from the PLDI paper in Alive2 (in original Alive: https://github.com/nunoplopes/alive/blob/df211719ade477d8f1205b484da34885d8a7ef74/tests/unit/PR20186.opt), and it fails with:

```
Processing tests/PR20186.opt..
Parse error in line: 3: expected token: LPAREN, got: REGISTER
```

I can't seem to find this same example, or any that I understand to use the same type of generic constant, in this repo. Thanks again!

**Comment by nunoplopes** [comment]
Ah, that sounds like another bug. Right now constants need to be followed by a number.  Replacing `C` with `C1` should work.

**Comment by avanhatt** [comment]
Hm, still not able to parse the negation in the target (despite trying to change whitespace/parens):

```
%a = sdiv %X, C1
%r = sub 0, %a
  =>
%r = sdiv %X, -C1
```

```
alive2 (master) $ ./build/alive -smt-to:1000000 tests/PR20186.opt 
Processing tests/PR20186.opt..
Parse error in line: 4: [Lex] couldn't parse: '-C1'
alive2 (master) $ ./build/alive -smt-to:1000000 tests/PR20186.opt  // (-C1)
Processing tests/PR20186.opt..
Parse error in line: 4: [Lex] couldn't parse: '-C1)'
alive2 (master) $ ./build/alive -smt-to:1000000 tests/PR20186.opt // (- C1)
Processing tests/PR20186.opt..
Parse error in line: 4: [Lex] couldn't parse: '- C1)'
alive2 (master) $ ./build/alive -smt-to:1000000 tests/PR20186.opt  // (0 - C1)
Processing tests/PR20186.opt..
Parse error in line: 4: Expected constant expression; got: NUM
```

**Comment by regehr** [comment]
I can probably make a bit of time to hack on the parser if you want, Nuno, or else see if Pranav can do it

**Comment by nunoplopes** [comment]
The undef cex printing bug is fixed. There's some work left to track undefs properly, but that's tracked elsewhere.
