### ISSUE TITLE
Refinement between poison int byte and poison pointer byte

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#233]
Refinement between int poison byte and pointer poison byte is not encoded, and it causes this example to fail:

```
define void @f(i8* %p, i1 %cond) {
  %v = load i8, i8* %p
  br i1 %cond, label %A, label %B
A:
  store i8 %v, i8* %p 
  ret void
B:
  ret void
}
=>
define void @f(i8* %p, i1 %cond) {
  ret void
}
```

I made this very simple patch, but it still fails: https://github.com/aqjune/alive2/commit/d242d0bf7c96761a11c8fb8eb8027fc37749a091
I couldn't figure out the reason, do you have any idea?

**Comment by nunoplopes** [comment]
You were almost there :)
The bug was using isAllOnes(). That function returns a bool and not an expr. Due to automatic conversion from bool to expr, it magically "worked" even though it wasn't doing the right thing.

**Comment by aqjune** [comment]
Oh I see, thanks!
