### ISSUE TITLE
Z3 memory_max_size option and assertion violation

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#243]
There are pairs in bzip2/gzip causing alive-tv consume huge amount of memory, and I'm trying to set the maximum memory usage of Z3 to resolve the issue.
https://github.com/aqjune/alive2/commit/faeb0d91ba408bdf092db33560f3bafd00ac04ef
This patch works in general but causes alive-tv raise m_ref_count error on a specific input:

[input.zip](https://github.com/AliveToolkit/alive2/files/4002622/input.zip)

error (Z3 compiled with -d, 991e587):

```
ERROR: SMT Error: out of memory                             
                                                            
Summary:                                                    
  0 correct transformations                                 
  0 incorrect transformations                               
  1 errors                                                  
ASSERTION VIOLATION                                         
File: ../src/ast/ast.h                                      
Line: 491                                                   
m_ref_count > 0                                             
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

This happens when -max-mem=4096 (4gb) but not in different settings.

Do you have any idea?

Thanks,

**Comment by nunoplopes** [comment]
It's not safe to use Z3's max memory option; Z3 must terminate the process when it triggers a mem out. Timeout is the only option that is safe, as well as other things that indirectly control memory like mbqi instantiations, etc.

**Comment by aqjune** [comment]
I see, thanks
