### ISSUE TITLE
Precondition is false error when aggregate global is given as a fn arg

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#259]
```
$ cat aa.ll
%struct.stat = type { i64, i64 }

@fileMetaInfo = global %struct.stat undef, align 1
declare i32 @stat(%struct.stat*)

define void @saveInputFileMetaInfo() {
entry:
  call i32 @stat(%struct.stat* @fileMetaInfo)
  ret void
}
```

Running `alive-tv aa.ll aa.ll` raises `Precondition is always false` error.
The error disappears if `%struct.stat` is defined to have only one element (`{ i64 }`).
Seems to be introduced at d8ab263

**Comment by nunoplopes** [comment]
https://github.com/AliveToolkit/alive2/commit/66f172a33e8082598d5853411507549fdcfd0b9f
