### ISSUE TITLE
TV fails same code with branch and function call.

### ISSUE THREAD

**Issue by Dongjoo-Kim** [AliveToolkit/alive2#264]
TV fails validation with the following example.

```
declare i8 @g(i8* %p) 

define void @f(i1 %cmp, i8* %p) {
entry:
  br i1 %cmp, label %if, label %exit

if:
  %q = call i8 @g(i8* %p) 
  br label %exit

exit:
  ret void
}
```

The error message is 'Mismatch in memory' when %cmp is undef value, but printed result is same.

**Comment by nunoplopes** [comment]
I can't reproduce this one.
Can you upgrade Z3 to latest version and check if this still reproduces?  Thanks!

**Comment by Dongjoo-Kim** [comment]
After update Z3 to pre-release(commit 20618ff) from latest release(4.8.7), this error is removed.
Sorry for confusing you.
