### ISSUE TITLE
Sort mismatch error

### ISSUE THREAD

**Issue by Dongjoo-Kim** [AliveToolkit/alive2#265]
Between bd74b2f and 6ccbfe4, Sort mismatch error is introduced.
Juneyoung and I tried to find the reason, but failed.

Error message is `ERROR: SMT Error: Sort mismatch at argument #1 for function (declare-fun = ((_ BitVec 32) (_ BitVec 32)) Bool) supplied sort is (_ BitVec 11)`.
I attached the input files.
The command is `./alive-tv sort_mismatch.src.ll sort_mismatch.tgt.ll`

[sort_mismatch.zip](https://github.com/AliveToolkit/alive2/files/4044674/sort_mismatch.zip)

**Comment by nunoplopes** [comment]
This was a bug in Z3. Fixed here: https://github.com/Z3Prover/z3/commit/0b14f1b6f6bb33b555bace93d644163987b0c54f
