### ISSUE TITLE
Simple transform times out

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#27]
Getting this with latest alive2 on OS X.

```
Johns-MacBook-Pro:build johnregehr$ ./alive foo2.opt
Processing foo2.opt..

----------------------------------------
  %a = add i64 %b, %b
=>
  %a = shl %b, 1

ERROR: Timeout

Johns-MacBook-Pro:build johnregehr$ ./alive foo3.opt
Processing foo3.opt..

----------------------------------------
  %a = add i65 %b, %b
=>
  %a = shl %b, 1

Doesn't type check!
Johns-MacBook-Pro:build johnregehr$ 
```

**Comment by nunoplopes** [comment]
Ah, for types > 64 bits, you need to fully specify the types everywhere (Alive1 had the same limitation).
So this should work:
```
  %a = add i65 %b, %b
=>
  %a = shl i65 %b, 1
```

For the timeout, I need to investigate. It should be canonicalized anyway.

**Comment by regehr** [comment]
ah, makes sense, thanks!

I think I never tried larger widths with Alive1, and only really care about them here since Souper sometimes sees them

**Comment by manasij7479** [comment]
Current Alive2 is working fairly well with Souper, I am seeing less timeouts in general. Thanks!
(This particular example still seems to time out with i13 and above.)

**Comment by regehr** [comment]
Now that alive2 is pretty mature and capable, I'd like to return and maybe spend some time working on performance issues. I have some time for this over the summer. For example the query below is one that I would naively expect to be fast, but it times out on volta, a very fast and otherwise idle machine. 
http://volta.cs.utah.edu:8080/z/CLAnvb

I haven't looked into this yet, but I assume that a quantifier is making it to bit blasting? Nuno, I know that you're miles ahead of me on this stuff-- do you have a bit of time to discuss what might be the best places to start attacking these issues?

```
define i16 @src(i16 %x) {
    %r = add i16 %x, %x
    ret i16 %r
}

define i16 @tgt(i16 %x) {
    %r = shl i16 %x, 1
    ret i16 %r
}
```

**Comment by nunoplopes** [comment]
Right, that examples gets a quantifier due to the undef values.
It should be easy yes. The quantifier just needs to guess that the 3 undefs need to be equal to prove it correct. For some reason, Z3's MBQI algorithm is failing to find that instantiation.
The MBQI algorithm is conceptually simple. I think it's a good place to look at. Leo has an intro here, including e-matching & MBQI: https://leodemoura.github.io/files/SAT-SMT-2012.pdf
For smaller bitwidths, we should just plugin the tactic that fully unrolls the quantifiers. I've been forgetting to do this.

**Comment by regehr** [comment]
Ok-- so if I understand correctly, small bitwidths can be done through some tactic tweaking in alive2 and larger ones will require some reasonably easy z3 hacking?

**Comment by nunoplopes** [comment]
> Ok-- so if I understand correctly, small bitwidths can be done through some tactic tweaking in alive2 and larger ones will require some reasonably easy z3 hacking?

yep! These are the relevant files in Z3:
entry point: https://github.com/Z3Prover/z3/blob/master/src/smt/smt_quantifier.cpp
https://github.com/Z3Prover/z3/blob/master/src/smt/smt_model_checker.cpp
https://github.com/Z3Prover/z3/blob/master/src/smt/smt_model_finder.cpp

and the new finite domain solver, which doesn't outperform the current SMT loop for some unknown reason, though it really should (must have a bug somewhere): https://github.com/Z3Prover/z3/blob/master/src/tactic/fd_solver/smtfd_solver.cpp

**Comment by nunoplopes** [comment]
Nikolaj has been playing with a new UF solver inside the SAT solver: https://github.com/Z3Prover/z3/tree/master/src/sat/smt
Essentially it's a reimplementation of SMT on top of Z3's "new" SAT solver, as the main SMT engine still uses the old SAT solver. This initial version supports bit-vectors + UFs through lazy ackermannization + pseudo-boolean constraints.
This doesn't handle quantifiers (but could if someone implemented that 😉).

anyway, just FYI. It's ongoing work; not ready for prime time, but already ok to play with.

**Comment by nunoplopes** [comment]
FWIW, smtfd solver is to be removed and fully replaced by the code in sat/smt dir I mentioned above. It's the way forward, but doesn't support quantifiers yet. We could discuss with Nikolaj what's the plan to integrate mbqi there. Or we simply ignore sat/smt for now.

**Comment by nunoplopes** [comment]
MBQI is now integrated: https://github.com/Z3Prover/z3/blob/master/src/sat/smt/q_mbi.cpp

**Comment by aqjune** [comment]
Another simple transformation that timeouts:
```
; -smt-to=20000
define i32 @src(i32 %x, i32 %y) {
  %v = add nsw i32 %x, %y
  ret i32 %v
}

define i32 @tgt(i32 %x, i32 %y) {
  %v = add nsw i32 %y, %x
  ret i32 %v
}
```

I'm not 100% sure, but maybe one possible direction to explore would be to simplify %v by extending strip_undef and using at BinOp::toSMT.
-se-verbose currently shows:
```
%v = (bvadd (ite (= #b0 isundef_%x) %x undef!0) (ite (= #b0 isundef_%y) %y undef!1)) /
 (and np_%x
     np_%y
     (= (bvadd ((_ sign_extend 1) (ite (= #b0 isundef_%x) %x undef!0))
               ((_ sign_extend 1) (ite (= #b0 isundef_%y) %y undef!1)))
        ((_ sign_extend 1)
          (bvadd (ite (= #b0 isundef_%x) %x undef!0)
                 (ite (= #b0 isundef_%y) %y undef!1)))))
```
But I think it is okay to be:
```
%v = (bvadd %x %y) /
  (and np_%x np_%y
     (= #b0 isundef_%x) (= #b0 isundef_%y) 
     (= (bvadd ((_ sign_extend 1) %x) ((_ sign_extend 1) %y))
        ((_ sign_extend 1) (bvadd %x %y))))
```

**Comment by nunoplopes** [comment]
Those simplifications are complicated. We need to stop somewhere; we can't keep adding infinite rules until we have an instcombine nightmare.

**Comment by aqjune** [comment]
I think it can be succinctly written if we have Input::match helper (which is embedded at #664):
https://gist.github.com/aqjune/2ba8819bbe1229e4bab984807cef2c7a

Maybe I can run LLVM unit tests to see how much performance improves; nsw/nuw flags are frequent, so it might bring a nice performance boost at the cost of only minor implementation.

**Comment by aqjune** [comment]
It has a nice performance boost..! Total # timeout: 5302 -> 5134 (-3%)
What I've implemented looks like this: https://github.com/aqjune/alive2/commit/bb671c379bf6b21449752b255f39c45ecc6a3258
What do you think?

**Comment by nunoplopes** [comment]
Let me close this. There's nothing else we can do on the Alive2 side. This has to be fixed on the Z3 side.
