### ISSUE TITLE
Vector load/store broken with element size not a multiple of 8

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#277]
Encoding of the following is broken:
```
define i32 @fn(<4 x i4>* %p ) {
    store <4 x i4> <i4 3, i4 5, i4 2, i4 3>, <4 x i4>* %p
    ret i32 0
}
```

**Comment by aqjune** [comment]
I'll make a patch for this

**Comment by nunoplopes** [comment]
LLVM test failing: https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=b636d1f9d0bd9caf&test=Transforms%2FSROA%2Fvector-promotion-different-size.ll

store size of <3 x i1> is 1 byte, not 3.
