### ISSUE TITLE
An error message with src/tgt with a loop

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#281]
[loop-precond.zip](https://github.com/AliveToolkit/alive2/files/4140496/loop-precond.zip)
alive-tv says transformation is correct, not precondition is false.
If an identical pair is given (`alive-tv loop-precond.src.ll loop-precond.src.ll`), the output is `precondition is false`.
Would this be a bug, or a behavior that is allowed?

The precondition is returning SAT even though the loop is iterating constant times.

**Comment by nunoplopes** [comment]
This is the expected behavior. There's nothing else we can do ATM.
