### ISSUE TITLE
Poison-ness of nonnull argument

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#289]
```
define void @f(i8* nonnull %p) {                                                    
  ; Can %p be poison?
}                                                                                  
```
I think %p cannot be poison because it is UB for a caller to pass a poison value as a nonnull argument.
If it is well-defined for a caller to pass poison, the following transformation does not hold:
```
call @f(poison); // well-defined
->
call @f(null); // UB
```

**Comment by regehr** [comment]
Hi Juneyoung, do you have a reference for "it is UB for a caller to pass a poison value as an argument"? I haven't seen this.

**Comment by aqjune** [comment]
Hello. It meant it is UB to pass poison as a nonnull argument; sorry for the ambiguous expression.
The running example is here: https://godbolt.org/z/g8cgb3
The optimized program is directly passing null to g(nonnull), which is UB according to LangRef. Therefore the source program should raise UB too (which is passing poison to g()).

**Comment by regehr** [comment]
Ah, thanks, I missed the nonnull attribute in your example!

If you have to prove non-poison to use the nonnull attribute, I expect that almost all uses of it will become unsound, since proving non-poison is generally hard. Is this your impression also?

**Comment by aqjune** [comment]
Yes I think so; interprocedural analysis that adds nonnull flag will become unsound in general.
We cannot simply add freeze (e.g. %x -> freeze %x in the example above) as well, because %x should not be freezed into null.
