### ISSUE TITLE
-se-verbose does not show attributes of nonlocal blocks that are not global vars

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#299]
-se-verbose does not show attributes of nonlocal blocks pointed by function arguments:

```
$ cat a.srctgt.ll
define i8 @src(i8* %ptr) {
  %v = load i8, i8* %ptr
  ret i8 %v
}
...
$ ./build/alive-tv a.srctgt.ll -se-verbose
...
MEMORY
======
...
BLOCK SIZE:
Non-local: {
#b0: #x0 // this is for the null block
// There's no #b1
}
...
```

**Comment by nunoplopes** [comment]
This is by design, since those blocks don't have fixed attributes.
The attributes of other blocks are only fixed if there's a counterexample. I need to implement memory counterexample printing, but that's a different issue.

**Comment by aqjune** [comment]
I see, so it was for a general use regardless of validation success/failure.
