### ISSUE TITLE
Root checking doesn't handle possible multiple users

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#3]
Alive2 accepts the following, but shouldn't since there might be multiple users:
```
%x = freeze i4 undef
  =>
%x = undef
```

**Comment by regehr** [comment]
is the fix to add an extra clause to the refinement check that looks for this specific case?

**Comment by nunoplopes** [comment]
I think so. The only concern is how to do it efficiently as detecting undef is usually expensive.
