### ISSUE TITLE
a few tests always fail

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#303]
Even with the very latest Z3 and --smt-to=60000, I still get test suite fails.
```
Failing Tests (3):
    Alive2 :: alive-tv/memory/alloca-removal.src.ll
    Alive2 :: alive-tv/memory/store-nan.src.ll
    Alive2 :: alive-tv/memory/storeptr.src.ll
```

For example, this one from `alloca-removal.src.ll`:

```
----------------------------------------
define * @f_observed(i64 %size) {
%entry:
  %items.addr = alloca i64 4, align 8
  %call = malloc i64 %size
  %unused = ptrtoint * %call to i64
  ret * %call
}
=>
define * @f_observed(i64 %size) {
%entry:
  %call = malloc i64 %size
  %unused = ptrtoint * %call to i64
  ret * %call
}
ERROR: Timeout
```

Is there anything else I should try, in order to get these to pass?

**Comment by nunoplopes** [comment]
alloca-removal passes on CentOS, but not the other 2.
We need to optimize the encoding of these tests a bit. Though I think at least one of them is an issue in Z3 that doesn't find the right quantifier instantiation AFAIR.

**Comment by regehr** [comment]
of course feel free to close the issue if it's not helpful -- just wanted to keep track of this, thanks

**Comment by aqjune** [comment]
FYI, I see the same list of failures too on Mac OS.
Would it be due to a different z3 configuration?
I am giving `--single-threaded` when running mk_make.py, and adding `-march=native` to build/config.mk's CFLAGS/CXXFLAGS.

**Comment by nunoplopes** [comment]
Ok, I've made timeout tests pass so the only tests that fail now are real problems. And we have 3 of them ATM, which need fixing (one was known).
