### ISSUE TITLE
Showing which instruction in tgt raised UB

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#325]
Would this format be ok?

```
Transformation doesn't verify!
ERROR: Source is more defined than target

Example:
...

Source:

SOURCE MEMORY STATE
===================

Target:

TARGET MEMORY STATE
===================

TARGET INSTRUCTIONS RAISING UB
===========================
```

**Comment by regehr** [comment]
I totally agree we need to give this information to users.
As an alternative to an extra section in the output, we might consider putting a signifier in the code output, something like `<=== UB` pointing to an instruction in @tgt maybe?

**Comment by aqjune** [comment]
`<=== UB` seems good; it is succinct and seems to carry the message with least verbosity.

Just realized that register values can also be described in a similar way.

This may be going too far at this point, but in the future we can possibly move towards actively adding more information at the src/tgt printing section (currently the section just prints Alive2 instructions), such as register values, which branch was taken, etc.
Showing the control flow that makes counter example will be a great feature for users. Clang static analyzer had a similar functionality (output format of which was a HTML document, so more graphical than text)

**Comment by nunoplopes** [comment]
Right I think we should stop printing the counterexample when it hits UB.
This is what's described in https://github.com/AliveToolkit/alive2/issues/64
