### ISSUE TITLE
Increase the limit of array constant's length? 

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#334]
[input.tar.gz](https://github.com/AliveToolkit/alive2/files/4395000/input.tar.gz)

```
alive-tv 27324.bc 27336.bc --func=strHash
```

This fails because the number of elements is larger than 128 (which is hard-coded at llvm_type2alive)

In the past, this pair succeeded because `llvm-extract` did not extract the initializer of a constant.

**Comment by nunoplopes** [comment]
We can't increase this much or expressions get too big.
Better is to avoid encoding constants altogether unless required by the optimization.
