### ISSUE TITLE
Refinement from undef ptr to undef int

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#345]
https://web.ist.utl.pt/~nuno.lopes/alive2/index.php?hash=b636d1f9d0bd9caf&test=Transforms%2FMemCpyOpt%2Ffca2memcpy.ll

In src,

```
store {*, i8, i24, i32} undef, * %dst, align 8
```

stores undef pointer at %dst.
After transformation,

```
memset * (bitcast %dst) align 8, i8 undef, i64 16
```

This problem can be resolved by adding a refinement between pointer byte to null and integer byte.
More specifically, we can say that a pointer byte ((nullblock, i), ofs) is refined by an integer ((i >> ofs) & 0xFF).

**Comment by nunoplopes** [comment]
We decided this is not really correct, since a subsequent load would read an int like a pointer, yielding poison rather than undef.
