### ISSUE TITLE
something weird with poison and range metadata

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#35]
here's a test that's just making sure that instcombine adds the appropriate range metadata for a ctpop call. alive is saying that source is more defined than target, but then %res ends up being poison both before and after, so I'm not sure what's going on but at the very least the printed output is confusing to read.

anyhow (regardless of the actual problem with this test case) it does seem like inserting fake icmp/and instructions may lead to UB problems and that we may need a separate flavor of instruction here that simply adds constraints without UB-related entanglements.

```
declare i1 @test4(i8 %arg) {
%0:
  %cnt = ctpop i8 %arg
  %res = icmp eq i8 %cnt, 2
  ret i1 %res
}
=>
declare i1 @test4(i8 %arg) {
%0:
  %cnt = ctpop i8 %arg
  $range_l$0%cnt = icmp sge i8 %cnt, 0
  $range_h$0%cnt = icmp slt i8 %cnt, 9
  $range$0%cnt = and i1 $range_l$0%cnt, $range_h$0%cnt
  assume i1 $range$0%cnt
  %res = icmp eq i8 %cnt, 2
  ret i1 %res
}
Transformation doesn't verify!
ERROR: Source is more defined than target

Example:
i8 %arg = poison

Source:
i8 %cnt = poison
i1 %res = poison

Target:
i8 %cnt = poison


LLVM ERROR: Alive2: Transform doesn't verify; aborting!
FileCheck error: '-' is empty.
FileCheck command line:  /home/regehr/llvm/build/bin/FileCheck /home/regehr/llvm/test/Transforms/InstCombine/ctpop.ll
```

**Comment by regehr** [comment]
test case is ```test/Transforms/InstCombine/ctpop.ll```

**Comment by nunoplopes** [comment]
I added a flag to assume to ignore cases where input is poison. This matches the semantics of a lot of things in LLVM, so seems sufficient and useful.
Thanks for the test case!
