### ISSUE TITLE
ninja check does not run alive-tv with identical inputs

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#365]
Given a `.src.ll`/`.tgt.ll` pair, ninja check currently runs alive-tv with `.src.ll .src.ll` and `.tgt.ll .tgt.ll` as well.
However, for a .srctgt.ll, ninja check isn't doing this. This should be supported.

**Comment by nunoplopes** [comment]
https://github.com/AliveToolkit/alive2/commit/8d1e2f9732d63a1b4a9abfbbe9e86f8337a4bf9a

**Comment by nunoplopes** [comment]
I see now 19 test failures. Some are timeouts, but at least one (vectors-i12.srctgt.ll) is a crash; fixing that one now..

**Comment by aqjune** [comment]
I see that most of the failing tests are those at alive-tv/bugs . I think it is likely that they raise timeouts on src - src because src tends to be large.
What do you think about adding something like `lit.cfg.py` at the alive-tv/bugs directory to temporarily disable their identity check? If it makes sense, I'll have a try.
