### ISSUE TITLE
A function call may exit even without noreturn flag, and encoding of UB should consider this

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#375]
When a function explicitly has noreturn flag, it is addressed by #309 now.
However, in general, a function without the flag can still exit, and this should be correctly encoded as well.

https://bugs.llvm.org/show_bug.cgi?id=27953 is a relevant bug.
This has a function pointer to an unknown function. Currently Alive2 does not support function pointer, but once it is supported, this will raise false negative due to this issue.

**Comment by nunoplopes** [comment]
see also alive-tv/bugs/pr33673.srctgt.ll

**Comment by nunoplopes** [comment]
Done; now missing support for willreturn.
