### ISSUE TITLE
Using -O0 for debug?

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#395]
LLDB doesn't seem to properly show the contents of variables when running alive2 compiled as a debug mode. If it is compiled with -O0, everything is fine.
-Og seems to be problematic in environment other than my machine too: https://github.com/AliveToolkit/alive2/pull/394/commits/418a786f83f422cb7f2ea0f7ceb42ed821485c39 also has a log for using -O0 instead. :/
Shall we use -O0 instead of -Og for debug mode? It will be great if we identify why -Og is not working here, but I currently don't have bandwidth for it.. :(

**Comment by nunoplopes** [comment]
I haven't had any issues with gdb. Complain to Apple instead :)

**Comment by aqjune** [comment]
Well, I want to use clang more than gcc. :)
Hope a [PLDI'20 paper](https://helloqirun.github.io/papers/pldi20_yuanbo1.pdf) makes things better.
