### ISSUE TITLE
PHINode from the same predecessor

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#396]
Consider this example:
```
define i32 @src(i32 %x) {
ENT:
    %c = icmp eq i32 %x, 10
    br i1 %c, label %A, label %A
A:
    %x2 = phi i32 [%x, %ENT], [%x, %ENT]
    ret i32 %x2
}

define i32 @tgt(i32 %x) {
ENT:
    %c = icmp eq i32 %x, 10
    br i1 %c, label %A, label %A
A:
    %x2 = phi i32 [10, %ENT], [%x, %ENT]
    ret i32 %x2
}
```
http://volta.cs.utah.edu:8080/z/L7TQAj

This is correct because %x is 10 if true branch is taken.

The problem here is that even if the location of %x and 10 is switched it still says the transformation is correct:
http://volta.cs.utah.edu:8080/z/m7Ehqi

If both is set to 10, it answers correctly:
http://volta.cs.utah.edu:8080/z/b7GZo2

I cannot come up with a solution for this immediately.
It seems like it is hard to distinguish which edge was taken to get to the phi. I'll ask llvm-dev about this.

**Comment by nunoplopes** [comment]
The order of operands of PHI doesn't matter. You can't distinguish the edges.
Alive's behavior seems correct to me. As long as [%x, %ENT] is in the arguments of phi there's a refinement.

**Comment by LebedevRI** [comment]
`@tgt` will not pass `-verify`, it's invalid IR.

**Comment by aqjune** [comment]
Refinement may pass if encoded in an existential manner, but I wasn't sure about the semantics of phi in this case - whether tgt(9) evaluates to 9 or 10.
I checked that the output does not pass `-verify`. Lucky that I didn't send a mail yet. :)

**Comment by nunoplopes** [comment]
Thanks @LebedevRI!
Yeah, if it doesn't even pass -verify let's not worry about it. From a theoretical point of view it would be fine; just adds non-determinism.
