### ISSUE TITLE
memcmp on pointers should be well-defined

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#444]
Currently memcmp uses `s.getMemory().load((p1 + i)(), IntType("i8", 8), 1)` to loads each byte, but this makes memcmp on pointers yield poison.

**Comment by nunoplopes** [comment]
implemented, but LLVM test `Transforms/MergeICmps/X86/pair-int32-int32.ll` still fails. Needs further investigation.

**Comment by nunoplopes** [comment]
> implemented, but LLVM test `Transforms/MergeICmps/X86/pair-int32-int32.ll` still fails. Needs further investigation.

The test is actually buggy; same bug already reported to LLVM.
Nothing left to do then, closing.
