### ISSUE TITLE
An identical input that makes Alive2 raise a failure

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#455]
[gzip.ll.zip](https://github.com/AliveToolkit/alive2/files/5056108/gzip.ll.zip) (updated)

Running alive-tv with gzip.ll gzip.ll makes alive-tv answer incorrectly.

```
define i32 @fill_inbuf(i1 %cond) {
entry:
  br label %do.body

do.body:
  br i1 %cond, label %do.end, label %if.then5

if.then5:
  unreachable

do.end:
  %call14 = call i32* @readnone()
  store i32 0, i32* %call14, align 4
  tail call void @read_error()
  unreachable
}

declare i32 @f()
declare void @read_error() noreturn
declare i32* @readnone() readnone
```

**Comment by aqjune** [comment]
I investigated the reason, and it was as follows:
(1) State::addFnCall found that `call readnone` in target is equivalent to the one in src, so it didn't call mkFnRet. 
(2) `nextNonlocalPtr` wasn't called in target memory by mkFnRet
(3) `nextNonlocalPtr` was too small, causing Memory::mkAxioms not encode alignment ule between non-local blocks because nonlocal_used returned false
(4) Alive2 incorrectly found the counter-example that contains a block with shrinked alignment in target.

**Comment by nunoplopes** [comment]
Fixed, thanks!
It didn't link the commit: https://github.com/AliveToolkit/alive2/commit/5a1112231374a89f3b9ade99c6544989a6ae92cd
