### ISSUE TITLE
Unexpected behavior of fp 0 and -0

### ISSUE THREAD

**Issue by sridhargopinath** [AliveToolkit/alive2#460]
I am using Alive to test an fp optimization in LLVM. I have pasted Alive's output on the simplified version of a test case below.

```
----------------------------------------
  %0 = fadd float 0.000000, undef
  ret float %0
=>
  %0 = fadd float -0.000000, undef
  ret float %0

ERROR: Value mismatch for float %0

Example:
Source value: NaN	[based on undef value]
Target value: #x80000000 (-0.0)
```

The semantics of `fadd` seems to be different on `0.0` and `-0.0`. Is this behavior expected or am I missing something?

**Comment by aqjune** [comment]
Hi,
If the undef in target is chosen to be -0.0 (as described in the message), the result of fadd in target is -0.0 .
Alive2 proved that whatever undef in source is, the result of fadd in source cannot be -0.0.
According to https://www.fourmilab.ch/documents/univac/minuszero.html, the rule of add when +/-0 is involved is as follows:
```
+0 + +0 = +0 
+0 + −0 = +0 
−0 + +0 = +0 
−0 + −0 = −0
```
