### ISSUE TITLE
State should track definitely not poison vars

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#468]
As an optimization, we should propagate non-poisonness of things like:
```
%a = udiv %b, %c  ; implies %c is not-poison
use(%c)  ; should have np = true
```

This property depends on the control-flow, so needs to be tracked in state per BB, and merged between predecessors accordingly.
What's a good API to state inform a var can't be poison? (and perhaps call addUB() by iself?)
Also, can we also propagate non-undefness? (this needs carrying a different whole StateValue)

**Comment by aqjune** [comment]
What about simply updating s[%c].non_poison to true when the udiv is executed (BinOp::toSMT is called)?

**Comment by nunoplopes** [comment]
No, you can't do that since it's only non-poison is the current branch. Might not be in others. This is a control-flow specific property,

**Comment by aqjune** [comment]
Sorry, you're right.
Can we expand DomainPreds to contain the non_poison information?
Or, predecessor_data may have something like triple<DomainPreds, AnalysisInfo, DisjointExpr<Memory>>,  instead of pair<DomainPreds, DisjointExpr<Memory>>.
State::operator[] can use the AnalysisInfo to return an optimized value.

**Comment by nunoplopes** [comment]
Yep, I was thinking in something like that.
plus we need a new e.g. State::getNonPoison() that does [] + adds np to UB + stores info that it can't be poison.
Feel free to give it a try if you want (& benchmark so we see if it helps at all). I'm a bit short on time ATM.

**Comment by aqjune** [comment]
Okay, I'll give it a try and see its performance change.
