### ISSUE TITLE
possible tv bug

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#470]
I definitely expected this one to give a "target is less defined than source" error or similar

https://alive2.llvm.org/ce/z/k8faux

```
define i1 @src() {
%0:
  %foo = freeze i1 undef
  ret i1 %foo
}
=>
define i1 @tgt() {
%0:
  ret i1 undef
}
Transformation seems to be correct!
```

**Comment by nunoplopes** [comment]
Gah, I really need to fix this. Sorry, it's a dup of https://github.com/AliveToolkit/alive2/issues/3

**Comment by regehr** [comment]
aha, sorry, forgot that was there!
