### ISSUE TITLE
memset(ptr, undef) should be able to fill different bit patterns per offset

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#481]
Relevant test: https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=0b0c43f83ca53e7d&test=Transforms%2FGVN%2FPRE%2Frle.ll

The failure happened because memset(ptr, undef) filled the same bit pattern for every offset.

Fixing it without performance hit does not seem straightforward. Left an issue here to record.

**Comment by nunoplopes** [comment]
I think the semantics of memset is fine as-is. memset can only be lowered to a loop if the value is frozen first.
