### ISSUE TITLE
audit byval & readonly implementation

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#482]
LangRef says:
`The copy is considered to belong to the caller not the callee (for example, readonly functions should not write to byval parameters).`

Need to audit the implementation to ensure conformance.

**Comment by aqjune** [comment]
A relevant test: https://alive2.llvm.org/ce/z/y6T68r
LangRef update: https://github.com/llvm/llvm-project/commit/2a1d8bace1f823c49ab9981b4939a62d44793daa (goes back to 2008)
Would it work if Alive2 adds readonly to %x when lowering it to Alive2 IR?

**Comment by aqjune** [comment]
It seems readonly itself isn't fully implemented yet: https://alive2.llvm.org/ce/z/VDKcUD
Another test: https://alive2.llvm.org/ce/z/jcvY-a 
This shows readonly callee does not touch nonlocal byval %x.

Passing local blocks passed as function arguments isn't shipped to here yet. It should start with e.g. local block mapping patch.
