### ISSUE TITLE
Inconsistent implementation of nonnull & dereferenceable for function calls

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#493]
In `unpack_inputs` we have the following code:
```cpp
Pointer p(s.getMemory(), move(value.value));
p.stripAttrs();
if (argflag.has(ParamAttrs::Dereferenceable))
  s.addUB(p.isDereferenceable(argflag.derefBytes, bits_byte / 8, false));
if (argflag.has(ParamAttrs::NonNull))
  s.addUB(p.isNonZero());
```

`value.non_poison` is never mentioned. It has to be, as `value.value` is not meaningful when `value.non_poison=false`

Then we have in `pack_return`:
```cpp
if (ty.isPtrType() && (isDeref || isNonNull)) {
  Pointer p(s.getMemory(), ret.value);
  s.addUB(ret.non_poison);
  if (isDeref)
    s.addUB(p.isDereferenceable(attrs.getDerefBytes()));
  if (isNonNull)
    s.addUB(p.isNonZero());
}
```

Here we assume nonnull & dereferenceable imply non-poison.
LangRef is omissive in this case.

It seems some optimizations in LLVM assume that a nonnull pointer might be pointer. For example, this transformation happens:
```llvm
%q = gep inbounds * %p, 1
%c = call i32 @f(* %q)
  =>
%q = gep inbounds * %p, 1
%c = call i32 @f(nonnull * %q)
```

We need:
- [ ] audit how LLVM relies on these attributes to understand the desired semantics
- [ ] clarify the semantics in LangRef
- [ ] fix `unpack_input` to mention `value.non_poison` somehow (depending on chosen semantics)
- [ ] fix `pack_return` if needed (depending on chosen semantics)

**Comment by nunoplopes** [comment]
@aqjune you looked at this stuff not too long ago. Were there any conclusions back then? Can you handle this pls?

**Comment by aqjune** [comment]
`poisonImpliesUB()` returns true when the attribute is nonnull or dereferenceable. `FnCall::toSMT` checks it and calls `getAndAddPoisonUB` instead. Currently we're assuming that passing poison to derefernceable and nonnull attributes is UB.
After ongoing patches on LLVM (malloc and GVN) has landed, I will send a mail to llvm-dev to clarify the semantics of nonnull and dereferenceable. A good news is that now we have noundef attribute in LLVM, so the current behavoir of nonnull/dereferenceable can be achieved by using noundef.

**Comment by aqjune** [comment]
It seems that noundef + nonnull is more undefined than the current nonnull; to make them equivalent, it should be something like *nopoison* + nonnull instead.
