### ISSUE TITLE
Not building with Debug option

### ISSUE THREAD

**Issue by nimisha-agarwal** [AliveToolkit/alive2#494]
I tried to build the tool in Debug mode using the following commands: 

`cmake -GNinja -DCMAKE_PREFIX_PATH=~/llvm/build -DBUILD_TV=1 -DCMAKE_BUILD_TYPE=Debug -DCLANG_PLUGIN=1 ..`
`ninja`

I am getting the following errors:

> [31/73] Building CXX object CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o
FAILED: CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o 
/usr/bin/c++   -I../ -I. -I/home/nimisha/llvm/llvm/include -I/home/nimisha/llvm/build/include -Wall -Werror -march=native -fPIC  -g -Og -g   -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o.d -o CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o -c ../llvm_util/llvm2alive.cpp
In file included from /home/nimisha/llvm/llvm/include/llvm/IR/InstrTypes.h:24,
                 from /home/nimisha/llvm/llvm/include/llvm/Analysis/ValueTracking.h:22,
                 from ../llvm_util/llvm2alive.cpp:8:
/home/nimisha/llvm/llvm/include/llvm/ADT/Twine.h: In static member function ‘static _Res std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Res = IR::Value*; _Functor = {anonymous}::llvm2alive_::get_operand(llvm::Value*)::<lambda(auto:22)>; _ArgTypes = {llvm::ConstantExpr*}]’:
/home/nimisha/llvm/llvm/include/llvm/ADT/Twine.h:232:16: error: ‘<anonymous>.llvm::Twine::RHS.llvm::Twine::Child::twine’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  232 |           !RHS.twine->isBinary())
      |            ~~~~^~~~~
cc1plus: all warnings being treated as errors
[36/73] Building CXX object CMakeFiles/alive2.dir/ir/instr.cpp.o
ninja: build stopped: subcommand failed.

It is building correctly when `-DCMAKE_BUILD_TYPE=Release` is used in cmake command. Is there a problem with llvm build or Alive2?

**Comment by nunoplopes** [comment]
That's a known issue in LLVM. You can use this patch:

```diff
diff --git a/llvm/include/llvm/ADT/Twine.h b/llvm/include/llvm/ADT/Twine.h
index 4140c22aad3..2dc7486c924 100644
--- a/llvm/include/llvm/ADT/Twine.h
+++ b/llvm/include/llvm/ADT/Twine.h
@@ -153,11 +153,11 @@ namespace llvm {

     /// LHS - The prefix in the concatenation, which may be uninitialized for
     /// Null or Empty kinds.
-    Child LHS;
+    Child LHS = {0};

     /// RHS - The suffix in the concatenation, which may be uninitialized for
     /// Null or Empty kinds.
-    Child RHS;
+    Child RHS = {0};

     /// LHSKind - The NodeKind of the left hand side, \see getLHSKind().
     NodeKind LHSKind = EmptyKind;
```
