### ISSUE TITLE
Fn call refinement wrong for freeze(undef) -> undef

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#499]
Alive2 considers the following correct (continuation of #490):
```llvm
define i8 @src(i8 %x) {
  %freeze = freeze i8 undef
  %r = call i8 @f(i8 %freeze)
  ret i8 %r
}

define i8 @tgt(i8 %x) {
  %r = call i8 @f(i8 undef)
  ret i8 %r
}

declare i8 @f(i8)
```

**Comment by aqjune** [comment]
(For those who want to avoid this issue until it is resolved: passing it to a function call multiple times will work. https://alive2.llvm.org/ce/z/QFgCsQ)

**Comment by nunoplopes** [comment]
nice idea @aqjune. Just implemented that lowering internally.

**Comment by aqjune** [comment]
Thank you for making the patch instead! Now it's time for me to write a code for Alive2..
