### ISSUE TITLE
Add support for more llvm.assume bundles

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#508]
e.g.. we miss support for align() assume bundle in AlignmentFromAssumptions/simple.ll

**Comment by aqjune** [comment]
Encoding `align` using assume + udiv + ptrtoint might pessimize optimizations.
One possible hack is to use memset with access size 0 and the wanted alignment. But, it is relying on the semantics of memset.
Would it be good if a new `align` option is added to assume?

**Comment by nunoplopes** [comment]
I agree, adding an assume_aligned or whatever is probably the best option. I guess we can change the current assume to have an enum to allow for multiple types of assumes?
We may consider changing the lowering of ranges to this style as well?

**Comment by aqjune** [comment]
Yes. I'll work on it.
