### ISSUE TITLE
Make clang plugin run parallel

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#512]
Clang plugin should be able to run in parallel.

fork - wait seems working, trying to limit the max # of processes

**Comment by regehr** [comment]
in opt-fuzz I did this by putting a condition variable in shared memory https://github.com/regehr/opt-fuzz/blob/master/opt-fuzz.cpp#L156-L165

see also `increase_runners()` and `decrease_runners()`

**Comment by aqjune** [comment]
Thank you!
