### ISSUE TITLE
Encoding I/O builtins as unknown fn calls in InstCombine pass

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#522]
Since I/O builtin calls like `printf` are optimized at InstCombinePass only, it is practically okay to regard them as unknown fn calls in non-InstCombine passes.

However, this requires maintaining two versions of Alive2 Functions - the one encoded with `io_nobuiltin=true` and another one encoded with `io_nobuiltin=false` at each pass.
Otherwise, it is impossible to recover the other version when needed.

For example: assumpe JumpThreading, InstCombine, SimplifyCFG are applied consecutively (F, F', F'', F''' are Alive2 functions) 

F -- JumpThreading -- F' -- InstCombine -- F'' -- SimplifyCFG -- F'''

F, F''' should be built with `io_nobuiltin=true`, but what about F' and F''?

Two possible solutions:

(1) Get the list of passes in advance somehow and use it. But I can't find the way to get it. :/ Do we need a separate invocation of clang process with no TV enabled?
(2) By default, get functions with `io_nobuiltin=true` and maintain it. When the pass is InstCombine, get functions with both `io_nobuiltin=true` and `false`, use the latter one to verify, store the former one for the upcoming passes. Question is its soundness; I think it is okay.

**Comment by nunoplopes** [comment]
Why not store the flag in FnCall itself?
Skip verification if tgt fncall has known fn = true. But do verify otherwise.
This only fails if instcombine may remove a fncall from src. which I guess it probably does remove `printf("")`.
So we may need a global flag in Function?

**Comment by aqjune** [comment]
Aha.. understood, makes sense. Then we don't need to generate Alive2 Function twice.

Will make a patch for this; after this, I believe I can give the first shot for various C benchmarks that we discussed.

The list of programs:
glib, PHP, cpython, sqlite3

Maybe we can run C benchmarks from SPECCPU 2017 too:
500.perlbench_r, 502.gcc_r, 505.mcf_r, 525.x264_r, 557.xz_r, 519.lbm_r, 538.imagick_r, 544.nab_r

Actually I want to start with small benchmarks in SPECCPU 2017 today, because it is straightforward to compile (no dependency issue, custom setting, etc)

What Crellvm had: SPECCPU 2006 C benchmarks + sendmail, emacs, gimp, ghostscript

**Comment by aqjune** [comment]
Irrelevant with this specific issue, but related with clang plugin:

`Transform::preprocess` is modifying function, and this causes a false positive when the next function cannot be preprocessed in the same way.
[b.c.zip](https://github.com/AliveToolkit/alive2/files/5408786/b.c.zip)
In 6. SROA , it has memory mismatch because the src's initializers are optimized away by `Transform::preprocess` whereas the tgt couldn't.

What can we do to address this issue?

**Comment by nunoplopes** [comment]
Ok, I see the preprocessor issue. That needs fixing, yes. The same issue will appear later with non-uniform unrolling.
The "naive" option would be to duplicate functions and store the pristine version and preprocess a copy. The issue is that it's non-trivial to duplicate a Function because of all the function pointers.
An alternative would be to tag instructions as "dead" and cleanup those bits between optimizations. That is sufficient for eliminating instructions, but not for the non-uniform unrolling, where we may want different unroll factors for different optimizations. So I don't know if we can do better than duplicating Functions.
Any other suggestion?

**Comment by aqjune** [comment]
I think duplicating Function is the simplest answer. Maybe this part should require some engineering, but will be possible to handle:
```
  // constants used in this function
  std::vector<std::unique_ptr<Value>> constants;
  std::vector<std::unique_ptr<Predicate>> predicates;
  std::vector<std::unique_ptr<Value>> undefs;
  std::vector<std::unique_ptr<AggregateValue>> aggregates;
  std::vector<std::unique_ptr<Value>> inputs;
```

**Comment by aqjune** [comment]
Fixing this has dependency on #510

**Comment by nunoplopes** [comment]
Instead of adding code to duplicate the function, an alternative is to re-translate from LLVM IR. That's a quick process.
*If needed* we can add a flag to preprocess to indicate if it did anything, for example.
This functionality is needed for both the clang & opt plugins.

**Comment by aqjune** [comment]
Yes, that should work. Let me write a code for this.

**Comment by nunoplopes** [comment]
Can we close this or is there anything left to do?

**Comment by aqjune** [comment]
This issue is fully resolved, closing this
