### ISSUE TITLE
Crash caused by mishandling of empty BBs in remove_unreachable_bbs() 

### ISSUE THREAD

**Issue by zhengyangl** [AliveToolkit/alive2#540]
When a function has BBs that do not contain any instructions (for example, #sink), remove_unreachable_bbs() would crash due to the back() call in L1111

https://github.com/AliveToolkit/alive2/blob/2eeb5ff3b88c634f08b7e12dcc03c43fc0026050/tools/transform.cpp#L1111

**Comment by zhengyangl** [comment]
Seems to me that instruction iterator for functions is also assuming each basic block has at least one instruction, see

https://github.com/AliveToolkit/alive2/blob/2eeb5ff3b88c634f08b7e12dcc03c43fc0026050/ir/function.cpp#L235

**Comment by zhengyangl** [comment]
Should we fix the iterator and remove_unreachable_bbs(), or just fill in some place holder ("assume true") to #sink?

**Comment by aqjune** [comment]
+1 for `assume false`, because it corresponds to `unreachable` in LLVM IR which is also a termiantor.

**Comment by nunoplopes** [comment]
I've just added a simple check to remove_unreachable_bbs(). #sink must remain empty to avoid false positives.
