### ISSUE TITLE
An input that crashes when unrolled

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#571]
```
define i32 @src() {
entry:
  br label %head1

head1:
  %i0 = phi i32 [ 0, %entry ], [ %i.next, %body_2 ]
  br label %body_1

body_1:
  %i = phi i32 [ %i.next, %body_2 ], [ %i0, %head1 ]
  %i.next = add i32 %i, 1
  %cond = icmp sgt i32 %i.next, 2
  br i1 %cond, label %exit, label %body_2

body_2:
  %cond2 = icmp sgt i32 %i.next, 1
  br i1 %cond2, label %body_1, label %head1

exit:
  ret i32 %i
}

define i32 @tgt() {
  ret i32 2
}
```

When alive-tv is executed with `-src-unroll=2`, the example above crashes.
CFG:
![src](https://user-images.githubusercontent.com/6484889/98444887-c2436480-2157-11eb-84ab-9a3e5d2258fa.png)

The reason seems to be related with the `exit` block's phis after unrolled. They look like this:
```
%exit:
  %i#phi#0 = phi i32 [ %i, %body_1 ], [ %i#2, %body_1#2 ], [ %i, %body_1#1#2 ], [ %i#2, %body_1#1#2#2 ], [ %i, %body_1#exit ], [ %i#2, %body_1#exit#2 ]
  store i32 %i#phi#0, * %i#ptr#2, align 16
  %i#phi#1 = phi i32 [ %i, %body_1 ], [ %i#1#2, %body_1#1#2 ], [ %i#exit, %body_1#exit ]
  store i32 %i#phi#1, * %i#ptr#3, align 16
  %i.next#phi#0 = phi i32 [ %i.next, %body_1 ], [ %i.next#1#2, %body_1#1#2 ], [ %i.next#exit, %body_1#exit ]
...
```

Notice that the phis have different numbers of slots.
`%i#phi#1` and `%i.next#phi#0` don't have incoming values from `%body_1#2`, `%body_1#1#2#2`, and `%body_1#exit#2`.

**Comment by aqjune** [comment]
Another example that creates a phi with missing slots:
[report.zip](https://github.com/AliveToolkit/alive2/files/5505192/report.zip)
Reproducer: `alive-tv -src-unroll=2 -tgt-unroll=2 src.ll tgt.ll`

`vimdiff src.alive2.txt tgt.alive2.txt` shows a nice diff. At `%while.cond2:`, there is a phi with a missing slot.

**Comment by aqjune** [comment]
Interestingly all missing edges are from 'body' blocks. :/

**Comment by nunoplopes** [comment]
Doesn't crash anymore at least.
Can you confirm the output looks good and make a PR with correct & fail test cases so we don't regress pls?

**Comment by aqjune** [comment]
Thanks..!
Sure, I'll check whether things are now okay.

**Comment by aqjune** [comment]
```
%exit:
  %i.next#phi#0 = phi i32 [ %i.next, %body_1 ], [ %i.next#1#2, %body_1#1#2 ], [ %i.next#exit, %body_1#exit ]
  %i#ptr#3#load = load i32, * %i#ptr#3, align 16
  %i#ptr#2#load = load i32, * %i#ptr#2, align 16
  ret i32 %i#ptr#3#load
```

I see that the phi at `%exit` has a few missing incoming edges, but the phi isn't used anymore, so it works fine. Maybe this is intended?
The missing edges are from:
```
body_1#2
body_1#1#2#2
body_1#exit#2
```

Since the original example is working, I'll close this and make a PR.
