### ISSUE TITLE
Stores incorrectly introduced by unroll, and critical edge splitting

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#573]
```
$ cat reduced.ll
; reduced from Transforms/NewGVN/pr31594.ll
define i8* @patatino(i8* %blah, i32 %choice) {
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.body, %entry
  %foo = phi i8* [ %blah, %entry ], [ null, %while.body ]
  switch i32 %choice, label %while.body [
    i32 -1, label %while.end
    i32 40, label %land.end
  ]

land.end:                                         ; preds = %while.cond
  br label %while.end

while.body:                                       ; preds = %while.cond
  br label %while.cond

while.end:                                        ; preds = %land.end, %while.cond
  ret i8* %foo
}
```

Running `alive-tv reduced.ll reduced.ll  -tgt-unroll=1` fails because one of stores introduced by loop unroll is incorrectly placed.

Actually, I found that there is no place to introduce store. :/
Doing critical edge splitting before unroll seems helpful to resolve this issue. https://github.com/aqjune/alive2/commit/05539f98fdcfcbd7b2c89db3c97ef6fdf34d7425
It resolves multiple failures actually:
```
Transforms/NewGVN/pr31594.ll
Transforms/LICM/sinking.ll 
https://github.com/AliveToolkit/alive2/issues/564
```

**Comment by aqjune** [comment]
The last two bbs after running `alive-exec reduced.ll -unroll=1`:
```
%land.end:
  %foo#phi#1 = phi * [ %foo, %while.cond ], [ %foo#exit, %while.cond#exit ]
  store * %foo#phi#1, * %foo#ptr#2, align 16
  br label %while.end

%while.end:
  %foo#phi#0 = phi * [ %foo, %while.cond ], [ %foo#exit, %while.cond#exit ]
  store * %foo#phi#0, * %foo#ptr#2, align 16
  ^^^^^  This store hides the first store
  %foo#ptr#2#load = load *, * %foo#ptr#2, align 16
  ret * %foo#ptr#2#load
}
```

**Comment by nunoplopes** [comment]
I committed a fix (https://github.com/AliveToolkit/alive2/commit/012ff502b8f3e5a28b36754e92d67e34ab0b6882) to move the stores to where the value is produce, entirely removing phis. This is the easiest solution for now.
You are right that if we decide to get rid of this "slow path" we need to split critical edges. But I think for now we are good; let's evaluate perf first.
Thanks for reducing the test case! 😎
