### ISSUE TITLE
Source is more defined than target when running LLVM test suite with unrolling 

### ISSUE THREAD

**Issue by zhengyang92** [AliveToolkit/alive2#574]
1. reduced case from LoopUnroll/pr45939-peel-count-and-complete-unroll.ll (minimal unroll=8)

https://alive2.llvm.org/ce/z/M8N47b

Commandline for rewriting src to tgt:

```$opt -loop-unroll -unroll-peel-count=2  -S -o tgt.ll src.ll```

2. reduced case from Transforms/LoopVectorize/gcc-examples.ll (function: example21, min unroll=4)

https://alive2.llvm.org/ce/z/m8bH6C

Commandline for rewriting src to tgt:

```$opt -basic-aa -loop-vectorize -force-vector-width=4 -force-vector-interleave=1 -dce -instcombine -S -o tgt.ll src.ll```

3. case from LoopVectorize/interleaved-accesses.ll (function: PR27626_4, min unroll=4)

https://alive2.llvm.org/ce/z/EYZjjx

Commandline for rewriting src to tgt:

```$opt -loop-vectorize -instcombine -force-vector-width=4 -force-vector-interleave=1 -enable-interleaved-mem-accesses=true -runtime-memory-check-threshold=24 -S -o tgt.ll src.ll```

**Comment by nunoplopes** [comment]
Are these bugs in Alive2 or in LLVM? What's the bug?

**Comment by zhengyang92** [comment]
Hi @nunoplopes , for the first one, I think the last store added to tgt in L61 (https://alive2.llvm.org/ce/z/M8N47b) is wrong. What do you think? 

I am looking at the second and the third one.

**Comment by zhengyang92** [comment]
The third one, LLVM generates a GEP inbound with -1 as index (L52 in https://alive2.llvm.org/ce/z/EYZjjx). This should be a bug in LLVM.

**Comment by nunoplopes** [comment]
> In the third case LLVM generates a GEP inbound with -1 as index (L52 in https://alive2.llvm.org/ce/z/EYZjjx) which brings in poison to target while in source it's poison free. This one should also be a bug in LLVM.

Agreed, can't do a gep inbounds with negative offset on an pointer given as argument to a function. Can you report that to LLVM pls? And send a PR to tests/alive-tv/bugs pls so we make sure we don't regress on finding this bug 😀

**Comment by zhengyang92** [comment]
> In the third case LLVM generates a GEP inbound with -1 as index (L52 in https://alive2.llvm.org/ce/z/EYZjjx) which brings in poison to target while in source it's poison free. This one should also be a bug in LLVM.

The second case  is similar to above one. LLVM adds gep inbounds %p, -3 to the tgt, (L54 in https://alive2.llvm.org/ce/z/m8bH6C ).

**Comment by zhengyang92** [comment]
> Hi @nunoplopes , for the first one, I think the last two store added to tgt in L60 and L61 (https://alive2.llvm.org/ce/z/M8N47b) is wrong and it should be a bug in LLVM. Both of them write out-of-bounds.

Hey @nunoplopes and @aqjune , could you comment on this one? The reason seems straightforward but I want to make sure I don't make stupid mistakes.

**Comment by zhengyang92** [comment]
> Agreed, can't do a gep inbounds with negative offset on an pointer given as argument to a function. Can you report that to LLVM pls? And send a PR to tests/alive-tv/bugs pls so we make sure we don't regress on finding this bug 😀

Yes, will do both report and PR tmr.

**Comment by nunoplopes** [comment]
> > Hi @nunoplopes , for the first one, I think the last two store added to tgt in L60 and L61 (https://alive2.llvm.org/ce/z/M8N47b) is wrong and it should be a bug in LLVM. Both of them write out-of-bounds.
> 
> Hey @nunoplopes and @aqjune , could you comment on this one? The reason seems straightforward but I want to make sure I don't make stupid mistakes.

It's a bug in the loop peeling. It peels off the first 2 iterations but it doesn't adjust the iteration checker. So it checks whether it can do 2 iterations, but then it does 10 iterations.
So it ends up doing 2 out-of-bounds stores.

**Comment by regehr** [comment]
this is great, @zhengyang92. are these the only bugs of this type that you ran into that are triggered by unrolling?

do we know why the OOB stores are not causing problems for LLVM users? I assume because no IR pass is smart enough to take advantage of the extra UB, and then they are translated benignly by the backends?

I saw a lot of "mismatch in memory" while fuzzing usingYARPGen but am not going to look into it further until PLDI is done.

**Comment by nunoplopes** [comment]
@regehr I was wondering the same. The answer is simple: peeling is not enabled by default. (on the backends I checked at least; the default is target dependent).

Closing this report as these are all bugs in LLVM and @zhengyang92 will take care of reporting those.

**Comment by zhengyang92** [comment]
Hey Nuno, I just reported the bugs. These are the links :)

https://bugs.llvm.org/show_bug.cgi?id=48125
https://bugs.llvm.org/show_bug.cgi?id=48126
https://bugs.llvm.org/show_bug.cgi?id=48127

**Comment by zhengyang92** [comment]
@regehr yes, these are all the bugs that comes from test suite tv runs with unrolling factor from 3 to 32 (Yes, I diff'ed each pair of results). Here's some other fact for the result logs.

- On high unroll factors most TVs with loops are either time'd out or kill'ed because of using too much memory. 
- For the cases that are reporting unroll factor is not enough, alive2 now just skips those cases. However, I counted how many times it complains "not enough" for each unroll factor and below is the data. Note: some cases are killed because time out or using too much memory and there's some indeterminism in it, the # of "not enough" is not decreasing monotonically.

```
unroll factor | # of "not enough" reports
1 | 1202
-- | --
2 | 1108
3 | 1084
4 | 1044
5 | 1036
6 | 1036
7 | 1028
8 | 987
9 | 1004
10 | 987
11 | 977
12 | 974
13 | 963
14 | 957
15 | 950
16 | 924
17 | 924
18 | 920
19 | 891
20 | 869
21 | 863
22 | 862
23 | 860
24 | 855
25 | 840
26 | 833
27 | 836
28 | 834
29 | 832
30 | 831
31 | 830
32 | 816
```

**Comment by regehr** [comment]
nice!
do you have the graphs we want to consider for the paper, such as time taken, tests successfully validated vs not, and number of defects found as you increase unroll factors to 32?

**Comment by zhengyang92** [comment]
@regehr I planed to reran the unroll again tonight since there's some changes in unrolling code after my last run. For each unrolling factor we need run single threaded because we want run each test cases in order so that later we can run diff on the result. Meanwhile we can start runs for different unroll factors in parallel. The whole experiment will take less than 10 hours.

I'll collect timing and all raw logs in this run.

**Comment by regehr** [comment]
all sounds good, but I don't understand running them in order -- aren't you using a report directory where each test case's output goes into a separate file?

**Comment by zhengyang92** [comment]
![Screen Shot 2020-11-09 at 9 28 57 PM](https://user-images.githubusercontent.com/2017989/98631597-9dbfc780-22d2-11eb-85df-81c16745e485.png)

@regehr I am diff'ing the output of lit. The execution of each test case must be in order so that diff would only reports changes.

**Comment by aqjune** [comment]
I guess there is a list of failed tests at the end of the output if you were using the same command as me. You can use it if it has :)
