### ISSUE TITLE
Unit tests for clang plugin

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#585]
I think it would be great if we have unit tests that use clang plugin if `-DCLANG_PLUGIN` is set.

I'd like to revive https://github.com/AliveToolkit/alive2/pull/541 , but the patch is pretty complex, so I'd feel more comfortable if there is a test for this.

If this direction seems okay, I'll prepare a PR that adds support for .c/.cpp unit tests to lit.

**Comment by aqjune** [comment]
(Maybe on Wed or after then, since I'll be offline for a few days)

**Comment by regehr** [comment]
I think we should definitely have tests for this. I'd also like to add Compiler Explorer support for C/C++.
