### ISSUE TITLE
Support puts and printf

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#595]
Nuno's idea: it would be a good start to encode `printf` with a non-format string ending with `\n` into `puts` first.
Encoding of `puts` needs to be only as precise as LLVM assumes

One issue with `puts` is that its first argument is marked as readonly.
```
// BuildLibCalls.cpp
  case LibFunc_puts:
...
    Changed |= setRetAndArgsNoUndef(F);
    Changed |= setDoesNotThrow(F);
    Changed |= setDoesNotCapture(F, 0);
    Changed |= setOnlyReadsMemory(F, 0);
```

Alive2 doesn't support it yet.

**Comment by nunoplopes** [comment]
Let's close this. We have statistics on the missing libcall semantics.
