### ISSUE TITLE
searching for missed-alarm bugs

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#604]
We already have a good story for finding false alarm bugs: run alive2 on lots of code, and investigate any alarms that come up. We're motivated to do this because every alarm is either a bug in Alive2 or in LLVM.

So far we have no good story for finding missed alarm bugs. These are fundamentally more difficult because they require pairs of functions that are inequivalent, but that have the same signature. Easy ideas like creating inequivalent pairs using a mutation-testing tool for LLVM IR won't work well because mutation-testing tools tend to create lots of pairs that look different, but that are functionally identical. We need pairs that are reliably inequivalent. 

Anyway, it seems useful to collect our thoughts here. I really would like to do random testing of this kind of alive2, just not yet sure how to make it happen.

**Comment by aqjune** [comment]
.. implementing a verified Alive2 that has only a small number of features/optimizations and compare results with C++ Alive2?
A sad thing is that without optimizations memory programs won't be verified quite well. :/

If we're focusing on the optimizations implemented in Alive2, we can compare the output of VCGen with/without optimizations using Z3.
Alive2 has a lot of optimizations, from simple instcombine-like ones on SMT expressions, to high-level ones such as limiting the number of memory blocks or omitting null pointer encoding.

**Comment by regehr** [comment]
What I'd like is a testing-based approach:
1. start with an IR function
2. mutate it randomly using an existing tool, several of these exist
3. use testing (a fuzzer or whatever) to prove that the original and mutated versions are inequivalent
4. make sure alive2 can prove inequivalence

all of this is easy except for step 3, which probably requires some sort of UB-aware LLVM interpreter, to make sure that the divergence is in a defined execution.

**Comment by aqjune** [comment]
I see.
Can we use Vellvm? It contains an interpreter. This will naturally show that Vellvm's semantics and Alive2 share the same semantics, which would be great.

**Comment by regehr** [comment]
this could work!

**Comment by aqjune** [comment]
I'll check whether https://github.com/vellvm/vellvm compiles successfully on my machine (installing dependencies take some time and sometimes weren't trivial IIRC) and the interpreter runs on the latest LLVM.

**Comment by nunoplopes** [comment]
I like the fuzzing idea. if it can prove 2 tests are not equivalent, so should Alive2.
For UB, it would be best if both tests didn't execute UB. Though that also limits the coverage.

The K folks have a paper claiming to have a spec for most of the IR. If that works, it would be another option to explore.

**Comment by aqjune** [comment]
This is a script that I used to compile vellvm: [vellvm.sh.zip](https://github.com/AliveToolkit/alive2/files/5659351/vellvm.sh.zip) Using opam package manager worked well.
This is a docker image for vellvm: https://hub.docker.com/repository/docker/aqjune/vellvm (it is in /root/vellvm)
This works for x86-64 machines; loading this on ARM machine raises an error that does not tell the architecture mismatch.
`vellvm -intepret` can run an .ll file that has the main function. If the program has UB, it emits an error like this:
```
Fatal error: exception Failure("Undefined Behaviour: Unsigned division by 0.")
```
Returning undef or poison:
```
Program terminated with: UVALUE_Undef
Program terminated with: UVALUE_Poison
```

I found that K-LLVM is outdated a bit; it supports LLVM 6.0 only.

**Comment by regehr** [comment]
thanks for looking into this, Juneyoung! I think we have all the pieces now. how about this?

- I make a small LLVM program using one of our random C generators
- mutate it using Mull or another similar tool
- use the interpreter to verify that the original and mutated codes behave differently and are defined
- flag an error if alive2 does not believe they are different from each other

what I'd really like to do is run this on codes found in the wild, but then I'm not sure how to automate it all, but this should work at least to get started.

**Comment by aqjune** [comment]
Yes, it looks great.
I quickly looked at what kind of mutations mull is doing. They are mostly about arithmetic operations, so we may need to add mutation operators for memory instructions in the future. I think it is feasible to implement those using this: https://github.com/mull-project/libirm
I think creating loops with constant iterations and using the unroll flags would work to deal with loops. I remember it was feasible to write an LLVM pass that replaces the iteration number with a constant as well (for detectable loops only).
Maybe I can give it a try to run it in a few days. What is a good way of generating small random C programs?

**Comment by regehr** [comment]
here is my student's random code generator:
https://github.com/intel/yarpgen
this current master branch is focusing on loop generation. it is my student developing it, so if we need any features, we can ask him to do it. right now I'm waiting for him to generate C code, it just does C++. this isn't a big problem for alive2 (we can compile with exceptions disabled) but C++ makes C-Reduce work less well, so I prefer to work with C when possible.

this is the old version which does support C, but does not support loops:
https://github.com/intel/yarpgen/tree/v1

I was also thinking about just flipping bits in bitcode files as a mutation strategy. it might be a stupid idea.

**Comment by regehr** [comment]
ok... I think I may have an easy thing for us to try first:

yarpgen has an UB-aware interpreter built into it, that works at the C/C++ level, which should be good enough for our purposes here. Vsevolod says that it should not be too hard to make a small random change to the generated code and then use his interpreter to verify that both the original and modified versions are UB-free, and also that they produce different results for at least one input.

so what we could do is put both of these functions into a single compilation unit and pass them through the clang plugin, and then ensure at every step of the optimization pipeline that alive2 believes there is a value mismatch. this necessitates a tiny bit of alive2 hacking but I don't expect that it'll be obtrusive.

**Comment by aqjune** [comment]
> so what we could do is put both of these functions into a single compilation unit and pass them through the clang plugin, and then ensure at every step of the optimization pipeline that alive2 believes there is a value mismatch. this necessitates a tiny bit of alive2 hacking but I don't expect that it'll be obtrusive.

I think this can be done by creating Transform/TransformVerify instance from the clang side and calling verify() twice (since their equivalence should be checked).

I think I can finish the NPM stuff today. Another thing that I have in my queue is to add support for a few library calls (related to #595)... but it shouldn't be too complex (hopefully, please)

**Comment by nunoplopes** [comment]
Closing this; it's more of a research topic. Nothing I can do right away 😀
