### ISSUE TITLE
function calls can't be dropped (unless readonly)

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#61]
```
Johns-MacBook-Pro:build johnregehr$ cat foo1.ll

declare i32 @getc(%struct.__sFILE* nocapture) local_unnamed_addr #1

%struct.__sFILE = type { i8*, i32, i32, i16, i16, %struct.__sbuf, i32, i8*, i32 (i8*)*, i32 (i8*, i8*, i32)*, i64 (i8*, i64, i32)*, i32 (i8*, i8*, i32)*, %struct.__sbuf, %struct.__sFILEX*, i32, [3 x i8], [1 x i8], %struct.__sbuf, i32, i64 }
%struct.__sFILEX = type opaque
%struct.__sbuf = type { i8*, i32 }

define i32 @foo(%struct.__sFILE* nocapture) {
  %2 = tail call i32 @getc(%struct.__sFILE* %0)
  ret i32 3
}
Johns-MacBook-Pro:build johnregehr$ cat foo2.ll

declare i32 @getc(%struct.__sFILE* nocapture) local_unnamed_addr #1

%struct.__sFILE = type { i8*, i32, i32, i16, i16, %struct.__sbuf, i32, i8*, i32 (i8*)*, i32 (i8*, i8*, i32)*, i64 (i8*, i64, i32)*, i32 (i8*, i8*, i32)*, %struct.__sbuf, %struct.__sFILEX*, i32, [3 x i8], [1 x i8], %struct.__sbuf, i32, i64 }
%struct.__sFILEX = type opaque
%struct.__sbuf = type { i8*, i32 }

define i32 @foo(%struct.__sFILE* nocapture) {
  ret i32 3
}
Johns-MacBook-Pro:build johnregehr$ ./alive-tv foo1.ll foo2.ll

----------------------------------------
define i32 @foo(* %0) {
%1:
  %2 = call i32 @getc(* %0)
  ret i32 3
}
=>
define i32 @foo(* %0) {
%1:
  ret i32 3
}
Transformation seems to be correct!
```

**Comment by regehr** [comment]
would side effects be best modeled, perhaps, by having function calls tweak a piece of the state object, perhaps by incrementing a counter that we put there?

**Comment by nunoplopes** [comment]
This is not implemented yet. It requires knowing the set of objects that a function can potentially override. Also, we are not checking refinement of memory just yet :)  It's quite non-trivial.

**Comment by regehr** [comment]
yeah, just to be clear, I'm talking about modeling side effects that alive can't capture, like the potential to issue system calls. 
so even when a function has no memory footprint, we can't change the number of times it's called along any path, and associating a counter with each function seems like a good way to do that, we'll need something like this even when the memory model is complete. I'll work on this if you think it's a reasonable way to proceed.

**Comment by nunoplopes** [comment]
A counter is not sufficient, since we need to account that system calls must be called for the same number of times, but also using the same parameters. This includes the memory state.
I think function calls should just be reflected in the memory state, which should include an extra memory block to account for all the potential side-effects that cannot account for.
On the other hand, if a function really doesn't read/write memory, it can go away because it cannot possibly call a system call (which, since we don't model it, can potentially write to the whole memory).

**Comment by regehr** [comment]
got it, thanks. fine w/me to close or leave this open until someone gets to this work.

**Comment by nunoplopes** [comment]
This has been fixed a while back. This particular test uses a "known function", so nothing is checked, but with a different fn call Alive flags the error.
