### ISSUE TITLE
[Q] Any user-side tips for achieving better performance?

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#627]
For example, i'm trying to run https://reviews.llvm.org/D87188#2448374 miscompile reproducer through `alivecc`,
and even with 
```
$ cat Makefile 
all:
        + /repositories/alive2/build-Clang-release/alivecc -target aarch64-w64-mingw32 -c -O2 vc1_block-p-block2.c -mllvm -tv-smt-to=3600000 -mllvm -tv-max-mem=1024 -mllvm -tv-parallel-jobserver -mllvm -tv-report-dir=report
```
+`make -j9` it's kinda slow (it's been running for an hour already).
I don't expect it to finish in under a minute, but still.

Is there some unwritten knowledge on how, e.g., z3 should be compiled,
or some obscure configuration option that should be specified, 
or something else amiss?

**Comment by nunoplopes** [comment]
Z3 can be compiled with --single-threaded. But that gives you up to 20% perf improvement only. And if queries timeout, you won't see any end-to-end speedup.
`-tv-smt-to=3600000` is just too much. That's 1 hour of timeout for each SMT query. We haven't see a benefit beyond 5 minutes. Even 1 minute is already a lot. Z3 usually either finds bugs quickly or doesn't find them ever. For programs with smallish functions, 10 seconds is enough.

There's no other magic. We are working on improving performance on several fronts. I hope we'll have something by the end of the year.

**Comment by LebedevRI** [comment]
Thanks

**Comment by regehr** [comment]
This function is interesting because we should be able to support it.

I ran this with `-tv-disable-undef-input` and it completed reasonably quickly with just 4 resource exhaustion errors. Of course disabling undef input could have hidden the bug. Alive doesn't find anything suspicious but I'm listing the errors below. Both function pointers and simple inline asm are things that we could support.

Nuno, would you like me to ask Zhengyang to look into the inline asm? I assume we would simply model it as an opaque function call, and that that would almost always work.

Roman, it doesn't really help you right now but I had reasonable success in compiling to ARM, lifting back to LLVM using the Trailofbits tools (Remill etc.) and then using Alive to compare the original and lifted IRs. I plan to get back to that work soonish, but I don't even have the tools compiling at the moment.

```
regehr@ohm:~/tmp$ grep ERROR vc1_block-p-block2.txt | sort | uniq -c
      3 ERROR: SMT Error: smt tactic failed to show goal to be sat/unsat memout
      1 ERROR: Timeout
     39 ERROR: Unsupported instruction:   %0 = call i32 asm "rev ${0:w}, ${0:w}", "=r,0"(i32 %x) #6, !srcloc !6
     24 ERROR: Unsupported instruction:   %1 = call i32 asm "rev ${0:w}, ${0:w}", "=r,0"(i32 %0) #6, !srcloc !6
      9 ERROR: Unsupported instruction:   %4 = call i32 asm "rev ${0:w}, ${0:w}", "=r,0"(i32 %3) #5, !srcloc !6
      9 ERROR: Unsupported instruction:   call void %21(i16* %22)
     35 ERROR: Unsupported instruction:   call void %3(i16* %block)
     11 ERROR: Unsupported instruction:   call void %3(i16* %block) #3
     54 ERROR: Unsupported instruction:   call void %3(i16* %block) #4
     54 ERROR: Unsupported instruction:   call void %3(i16* %block) #5
     19 ERROR: Unsupported instruction:   call void %3(i16* %block) #6
    187 ERROR: Unsupported instruction:   tail call void %3(i16* %block) #3
regehr@ohm:~/tmp$ 
```

**Comment by LebedevRI** [comment]
Thanks @regehr!

**Comment by nunoplopes** [comment]
> Nuno, would you like me to ask Zhengyang to look into the inline asm? I assume we would simply model it as an opaque function call, and that that would almost always work.

That would help, yes.
Though I do an impression that LLVM has optimizes for inline assembly. We would need to implement those as well to avoid false-positives.

**Comment by nunoplopes** [comment]
FYI indirect calls are high on my todo list, but unlikely to get there this year.

**Comment by regehr** [comment]
> Though I do an impression that LLVM has optimizes for inline assembly. We would need to implement those as well to avoid false-positives.

I took a quick look and didn't see anything obvious in lib/Transforms, but could have missed it. in any case, as long as there aren't any unforeseen complications, I think we should try to support this as opaque and just whitelist any passes that end up generating false alarms. I'll talk to Zhengyang about it.

**Comment by LebedevRI** [comment]
I don't recall ever seeing any optimizations for inline assembly.

**Comment by aqjune** [comment]
> +make -j9 it's kinda slow (it's been running for an hour already).
> I don't expect it to finish in under a minute, but still.

To me these two tricks were helpful:
- `-tv-subprocess-timeout=` to give a hard timeout for each invocation
- `-tv-func=<funcname>` to validate specific functions only

**Comment by aqjune** [comment]
I remember disable-undef-input was quite helpful too. Frequently it is VCGen (LLVM IR -> SMT query) that takes a very long time (its time complexity is often more than linear, in order to encode the input program's precise semantics w.r.t. undef), and the flag reduces the burden.

**Comment by aqjune** [comment]
Inlining assembly seems interesting..!
Its semantics (whether it is allowed to raise UB, the output variables can be undef/poison) might be an issue to settle. But would using Alive2's approach for library calls (encode as precise as what LLVM does) work?
Sorry for leaving multiple comments. :)

**Comment by regehr** [comment]
my quick take is that asm should be allowed to raise UB. one way to make this argument is to observe that of course inline asm might contain idiv, memory references, instructions with alignment requirements, etc. but maybe a better way to make this argument is to say that this gives the desired semantics, which is that the compiler is not allowed to spuriously add inline asms.

regarding poison/undef, I think we should start with the conservative assumption that it might produce both of these, and see if this causes false alarms.

regarding memory references in inline asm, I hope that it follows the same rules as external function calls. does that seem right?

**Comment by regehr** [comment]
I'll tell you what -- instead of continuing a conversation in a closed issue, let me make a new issue for inline assembly
