### ISSUE TITLE
can we support inline assembly?

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#628]
in this issue we continue a discussion started here:
  https://github.com/AliveToolkit/alive2/issues/627
the question is whether we can model inline assembly using our existing opaque function call machinery. this seems very likely to work, but we must answer some tricky questions about what inline asm is allowed to do, especially WRT undefined behavior.

**Comment by aqjune** [comment]
> regarding memory references in inline asm, I hope that it follows the same rules as external function calls. does that seem right?

(answering a question at #627 to this thread) I agree it should do so. Allowing it to touch function-local blocks would be overly restrictive. Inline assembly may be hidden under a plain function call as well.
