### ISSUE TITLE
Does select based on undef result in undef?

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#63]
Come up in https://reviews.llvm.org/D63060
```
----------------------------------------
  %sat = usub_sat i8 %a, %b
  %res = add i8 %sat, %b
=>
  %sat = usub_sat i8 %a, %b
  %t0 = icmp ult i8 %a, %b
  %res = select i1 %t0, i8 %b, i8 %a

ERROR: Value mismatch for i8 %res

Example:
i8 %a = undef
i8 %b = #x10 (16)
i8 %sat = undef
i1 %t0 = undef
Source value: undef
Target value: #x02 (2)
```
So we're selecting based on `%t0`, which is `undef`.
The result should be `undef`, too, right?

CC @nikic.

**Comment by LebedevRI** [comment]
(retranslating from https://reviews.llvm.org/D63060#1535589)

So the main question here may be
```
$ ./third_party/alive2/build/alive /tmp/test.opt 
Processing /tmp/test.opt..

----------------------------------------
Name: to zero
  %r = usub_sat i8 undef, 16
=>
  %r = i8 0

Done: 1
Optimization is correct!

----------------------------------------
Name: to undef
  %r = usub_sat i8 undef, 16
=>
  %r = udiv i8 0, 0

Done: 1
Optimization is correct!
```

We are correct that saturating subtraction from `undef` is `undef`?

**Comment by nunoplopes** [comment]
The transformation seems wrong to me, so Alive is correct in complaining. The counterexample is bogus.
Essentially the LHS is not undef. E.g. take a = undef  &  b = 0x80.
```
%sat = undef - 0x80 = [0, 0x7F]
%sat + 0x80 = [0x80, 0xFF]
```

RHS is undef because we get: `undef < 0x80 ? 0x80 : undef`, which is `undef ? 0x80 : undef`, which is `undef`.

**Comment by LebedevRI** [comment]
@nunoplopes thank you!
