### ISSUE TITLE
Clarify semantics of nocapture wrt returned args

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#644]
Is it legal to return a nocapture pointer? LangRef doesn't forbid that but Alive2 does.
Also, many libcalls that may return an argument ptr have it declared as nocapture.
We need to clarify this.

**Comment by aqjune** [comment]
I think it should be forbidden, because CaptureTracking stops traveling if a pointer is passed to fncall's nocapture argument without further seeing its return value:
```
      // Not captured if only passed via 'nocapture' arguments.  Note that
      // calling a function pointer does not in itself cause the pointer to
      // be captured.  This is a subtle point considering that (for example)
      // the callee might return its own address.  It is analogous to saying
      // that loading a value from a pointer does not cause the pointer to be
      // captured, even though the loaded value might be the pointer itself
      // (think of self-referential objects).
      if (Call->isDataOperand(U) &&
          !Call->doesNotCapture(Call->getDataOperandNo(U))) { << does not check return value
        // The parameter is not marked 'nocapture' - captured.
        if (Tracker->captured(U))
          return;
      }
      break;         << skips this call instruction
```

I looked through llvm/test/Transforms/InferFunctionAttrs/annotate.ll, and to me the pointer arguments that can be returned doesn't seem nocapture marked, perhaps..? For example, memcpy does not have the first argument marked as nocapture.

Should we suggest adding a short sentence ('nocapture ptr cannot be returned') to LangRef as well?

**Comment by nunoplopes** [comment]
LLVM doesn't seem to be able to optimize this simple example: https://gcc.godbolt.org/z/GvjrYj
If a nocapture pointer couldn't be returned then we could do store forwarding in that example. Anyway, doesn't prove anything 😀

I agree, let's just clarify that in LangRef. I can't find again the function in BuildLibCalls.cpp that triggered me looking into semantics of nocapture, though.
Also, we should also clarify what capturing means, because LangRef says it's just about doing a copy of the pointer. But it seems that storing a pointer to that object (any offset) would be invalid.

**Comment by aqjune** [comment]
A patch is here: https://reviews.llvm.org/D94386

**Comment by aqjune** [comment]
> Also, we should also clarify what capturing means, because LangRef says it's just about doing a copy of the pointer. But it seems that storing a pointer to that object (any offset) would be invalid.

A condition '.. that outlive the callee' seems to work. But, I definitely agree that this should be more concrete in the future. For example, it isn't clear whether casting it into integer / comparing it with another pointer and doing something is also capturing the pointer.

**Comment by aqjune** [comment]
Okay, we can close this issue! :)
