### ISSUE TITLE
undef global pointers shouldn't alias with local blocks

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#645]
```llvm
@g = internal unnamed_addr constant i8* undef, align 8

define i8 @src()  {
  %x22 = alloca i8, align 8
  %v = load i8*, i8** @g
  ret i8 0
}

define i8 @tgt() {
  ret i8 0
}
```

```
$ ./alive-tv test.srctgt.ll

Transformation doesn't verify!
ERROR: Mismatch in memory

Mismatch in pointer(non-local, block_id=1, offset=0)
Source value: pointer(local, block_id=7, offset=0), byte offset=0
Target value: pointer(non-local, block_id=4, offset=0), byte offset=0
```

**Comment by regehr** [comment]
I look at mismatches as I go through TV results and this pattern looks very familiar: I bet I've seen a lot of false alarms that stem from this.

**Comment by nunoplopes** [comment]
Really? Are there that many undef globals out there? Or you mean from fuzzing?
BTW, this came up today when investigating a possible bug in LLVM though https://github.com/ziglang/zig/issues/7325  (though it doesn't seem like it's a bug in LLVM after all, just in Alive 😅)

**Comment by regehr** [comment]
Cool example!
I don't remember the details but I'll keep an eye out for this when I'm reading results.
