### ISSUE TITLE
FP fast-math flags support

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#667]
It is possible this is a duplicate, but i have failed to find an original bugreport.
E.g. in https://reviews.llvm.org/D96648, it would be helpful to prove https://alive2.llvm.org/ce/z/4_v7TJ
but that fails with `ERROR: The program uses the following unsupported features: reassoc, arcp`

**Comment by nunoplopes** [comment]
The online version is a bit old. This is the current output:
```
ERROR: Couldn't prove the correctness of the transformation
Alive2 approximated the semantics of the programs and therefore we
cannot conclude whether the bug found is valid or not.

Approximations done:
 - Unknown libcall: @llvm.pow.f32
 - arcp
 - reassoc
```

In summary, we haven't implemented those things yet. It's in the todo list, but none of these is easy to implement. I'm quite busy ATM; can't promise when I'll get to this, sorry.
We do have a way of tracking missing support for intrinsics and fast-math flags. There's no need for a bug report.

**Comment by LebedevRI** [comment]
> We do have a way of tracking missing support for intrinsics and fast-math flags. There's no need for a bug report.

If there is no bugreport, it is entirely unobvious whether something is known or not.

**Comment by nunoplopes** [comment]
> > We do have a way of tracking missing support for intrinsics and fast-math flags. There's no need for a bug report.
> 
> If there is no bugreport, it is entirely unobvious whether something is known or not.

I know, sorry. I need to post the statistics we have on the dashboard. Essentially we compile a bunch of programs and track the top-20 missing features. Right now the top one is function pointers and we need to sort that out.
"easy" missing things like libcalls and intrinsics are easily tracked (as Alive2 complains). Things that are worth reporting are about half-backed features (on which Alive2 does not complain). Anyway, in doubt just report and we filter 😀

**Comment by regehr** [comment]
oops-- the other week I ran out of time to fix the header file problem we discussed, Nuno -- working on it now and hopefully will have the Alive2 used by the web site updated very soon
