### ISSUE TITLE
Non-inbounds GEP encoding bug?

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#684]
From https://reviews.llvm.org/D97665
https://alive2.llvm.org/ce/z/YQsJq3

```
target datalayout = "e-p:64:64:64-p1:16:16:16-p2:32:32:32-p3:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64"

@g = external global i8

; Ensure the comparison is not incorrectly folded into `false`.
define i1 @src() {
; CHECK-LABEL: @compare_non_inbounds_gep_zero(
; CHECK-NEXT:    ret i1 icmp eq (i8* getelementptr (i8, i8* @g, i64 0, i64 sub (i64 0, i64 ptrtoint (i8* @g to i64))), i8* null)
;
  %cmp = icmp eq i8* getelementptr (i8, i8* @g, i64 sub (i64 0, i64 ptrtoint (i8* @g to i64))), null
  ret i1 %cmp
}

define i1 @tgt() {
  ret i1 true
}
```

```
----------------------------------------
@g = global 1 bytes, align 1

define i1 @src() {
%0:
  %__constexpr_2 = ptrtoint * @g to i64
  %__constexpr_1 = sub i64 0, %__constexpr_2
  %__constexpr_0 = gep * @g, 1 x i64 %__constexpr_1
  %cmp = icmp eq * %__constexpr_0, null
  ret i1 %cmp
}
=>
@g = global 1 bytes, align 1

define i1 @tgt() {
%0:
  ret i1 1
}
Transformation doesn't verify!
ERROR: Value mismatch

Example:

Source:
i64 %__constexpr_2 = #x0000000000000002 (2)
i64 %__constexpr_1 = #xfffffffffffffffe (18446744073709551614, -2)
* %__constexpr_0 = pointer(non-local, block_id=1, offset=-2)
i1 %cmp = #x0 (0)

SOURCE MEMORY STATE
===================
NON-LOCAL BLOCKS:
Block 0 >	size: 0	align: 1	alloc type: 0	address: 0
Block 1 >	size: 1	align: 1	alloc type: 0	address: 2

Target:
Source value: #x0 (0)
Target value: #x1 (1)
```

I'm not quite clear as to why that is the case, `uint64_t(@g) - uint64_t(@g) == 0`,
so should be `@g - uint64_t(@g) == nullptr`, no?

CC @LemonBoy.

**Comment by nunoplopes** [comment]
gep doesn't change provenance of pointers, so any `gep @g, off` returns a pointer within `@g`. If the gep has no inbounds then the resulting pointer may be out of bounds, but it can be brought back in bounds (of `@g`) and dereferenced.
So, no gep over a non-null pointer can result in a null pointer.
However, comparison is a different thing. Comparison has to work a bit harder than just comparing object ids/offsets because LLVM does complicated optimizations. Alive2 doesn't have a full implementation of pointer comparison as we don't know yet what the right semantics is. @aqjune has this on his todo list for this month(?).
Off the top of my head, I can't tell if your example if correct or not, I'm afraid.

**Comment by aqjune** [comment]
Yes, the semantics of pointer comparison is unclear ATM. I'm planning to explore a bit to find the right one.

**Comment by jdoerfert** [comment]
> So, no gep over a non-null pointer can result in a null pointer.
Why, if it's not inbounds:
```c
p = ...
while (p) --p;
use(p);
```

**Comment by nunoplopes** [comment]
Pointers in C/C++/LLVM have provenance, so even gep wo/ inbounds can't jump between objects.
The short explanation is this paper: https://web.ist.utl.pt/nuno.lopes/pubs/llvmmem-oopsla18.pdf

We will present in due time a proposal to fix/clarify the semantics of pointer comparisons. We don't have one ATM.
We appreciate this bug report and we will take it into consideration when drafting the proposal.

**Comment by jdoerfert** [comment]
> Pointers in C/C++/LLVM have provenance, 

Agreed, until they loose it.

> so even gep wo/ inbounds can't jump between objects.

They can if you allow the provenance to change (to wildcards).

>  The short explanation is this paper: https://web.ist.utl.pt/nuno.lopes/pubs/llvmmem-oopsla18.pdf

Hm, I feel like this is linking to the standard document and saying it's in there, just read.

> We will present in due time a proposal to fix/clarify the semantics of pointer comparisons. We don't have one ATM.
We appreciate this bug report and we will take it into consideration when drafting the proposal.

I'm looking forward to that, we might start a discussion on the LLVM list earlier, keep an eye out :)

**Comment by LemonBoy** [comment]
Following the model described in the paper and [this transform of the SCEV implementation](https://github.com/llvm/llvm-project/blob/21280d35d652788309176831bd88257b58f674f9/llvm/lib/Transforms/Utils/ScalarEvolutionExpander.cpp#L401,L406) (that's the source of this weird GEP) looks unsound.

The transform replaces the sequence
```
T0 = ptrtoint X
T1 = f(T0)
T2 = inttoptr(T2)
```
into a `gep X, [...]`. But according to section 4.5 the `inttoptr` returns a pointer with no provenance info, while the `gep` retains the provenance of the base pointer `X` despite not having the `inbounds` tag.

**Comment by nunoplopes** [comment]
LLVM has several incorrect optimizations around `inttoptr`. We know about them. Some have been fixed (thanks @LebedevRI), but there are quite a few left. It's on the todo list 😀

**Comment by LebedevRI** [comment]
> LLVM has several incorrect optimizations around `inttoptr`. We know about them. Some have been fixed (thanks @LebedevRI), but there are quite a few left. It's on the todo list

Well then, i will fix this one too!111

**Comment by nikic** [comment]
I think the recent fix to pointer icmp semantics has fixed this issue as well.

**Comment by nunoplopes** [comment]
Ah, yes, thank you!

We changed the pointer comparison semantics to compare addresses, which seems to be what LLVM implements. However this makes one optimization wrong (fold comparison of ptrs to different objects that are not guaranteed to be inbounds to false). This needs fixing in LLVM. Don't remember if we have a bug report tracking this or not.
