### ISSUE TITLE
align assume bundle

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#692]
(not to forget)

LLVM :: Transforms/Util/assume-builder-counter.ll
```
define void @test(* %P, * %P1, * %P2, * %P3) {
  call void @func_many(align(8) * %P1)'
}
=>
define void @test(* %P, * %P1, * %P2, * %P3) {
  assume_align * %P1 i64 8
  call void @func_many(align(8) * %P1)'
}
```

"align" also can take an extra argument.

**Comment by aqjune** [comment]
A suggested fix: https://reviews.llvm.org/D98228

**Comment by nunoplopes** [comment]
Alive2 fix: https://github.com/AliveToolkit/alive2/pull/694

TODO is LangRef patching

**Comment by aqjune** [comment]
LangRef patch: https://reviews.llvm.org/D98684

**Comment by aqjune** [comment]
Bug fix: https://reviews.llvm.org/D98759
