### ISSUE TITLE
Padding in non-byte-aligned-type vectors should be non-deterministic

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#701]
This test case from https://github.com/llvm/llvm-project/commit/1470f94d71c544327f76b85c55cb6f7cb43a6cbb breaks Alive2's fixed way of padding:
```llvm
define i17 @vec_store_load_first_odd_size(i17* %p) {
; CHECK:    ret i17 1
  %p2 = bitcast i17* %p to <2 x i17>*
  store <2 x i17> <i17 1, i17 2>, <2 x i17>* %p2
  %load = load i17, i17* %p
  ret i17 %load
}
```

Memory layout of vectors now described in https://llvm.org/docs/LangRef.html#vector-type

**Comment by nunoplopes** [comment]
A similar example from @regehr for non-byte integers:
```
define void @src(%rec* %in) {
  %in2 = getelementptr %rec, %rec* %in, i16 0, i32 1
  %val2 = load i28, i28* %in2, align 4
  store i28 %val2, i28* %in2, align 4
  ret void
}

define void @tgt(%rec* %in) {
  ret void
}
```

It breaks because we assume the padding is always zero.

**Comment by aqjune-cryptolab** [comment]
Maybe I can have a look at this issue in Jan. 25 or later. The fix won't be very hard, I believe.

**Comment by aqjune** [comment]
Maybe I can have a look at this issue in Jan. 25 or later. The fix won't be very hard, I believe. :)
