### ISSUE TITLE
The semantics of strtol 

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#708]
To precisely approximate the semantics of some functions like strtol, Alive2 needs something like 'conditionally-nocapture':

```
// SimplifyLibCalls can do this kind of reasoning
char *p, **q;
strtol(p, q, 10); // captures p to q
strtol(p, null, 10); // p is not captured -> attaches nocapture to p at callsite
```

strtol isn't supported by Alive2 yet, but if it is supported, this information should be properly encoded; otherwise it will raise false positives.

**Comment by aqjune** [comment]
Another possible encoding is to emit strtol as something like:
```
strtol(nocapture p, 10)
if (q != null)
  *q = gep p, delta
```
Then the problem is that we should know what delta is. :(

I believe there are various approaches to calculate delta, but if the goal is to remove false positives, simply we can assume that updating *q never happens even if q isn't null.
Actually to me this looks like an open problem indeed.

**Comment by nunoplopes** [comment]
That's fine. whoever implements strtol needs to worry about that. Same for all the other libcalls we don't have semantics for.
I think we don't need a bug report open for each missing libcall. We know where they are 😀
