### ISSUE TITLE
uadd_overflow with undef

### ISSUE THREAD

**Issue by nikic** [AliveToolkit/alive2#71]
From https://reviews.llvm.org/D63065#1545052:

```
$ ./src/alive2/build-Clang-release/alive -root-only /tmp/test.opt 
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Processing /tmp/test.opt..

----------------------------------------
Name: uadd_overflow
  %X = uadd_overflow i8 %a, undef
  %Op = extractvalue {i8, i1} %X, 0
  %Ov = extractvalue {i8, i1} %X, 1
  %OpIsZero = icmp eq %Op, 0
  %NoOverflow = icmp eq %Ov, 0
  %Zero = and i1 %OpIsZero, %NoOverflow
  ret i1 %Zero
=>
  ret i1 1

Done: 1
Optimization is correct!
```

I don't understand why this optimization is correct. If `%a` is 1, then I don't see any choice of undef for which both the result is 0 and there is no overflow.

**Comment by LebedevRI** [comment]
It is possible that i'm again stumbling into `root-only` vs `undef` vs `???`, but it escapes me here.

**Comment by nunoplopes** [comment]
It's correct because of the semantics of `undef` in which each read may return a different value. So for the evaluation of `%Op` and `%Ov` undef can take different values. It can yield overflow or no-overflow and return whatever addition value it wants regardeless of the overflow bit.

**Comment by nunoplopes** [comment]
(but please don't use udiv by 0 instructions in the input or it won't be proving anything as it is simply UB and thus anything is allowed to happen).

**Comment by nikic** [comment]
@nunoplopes I'm not sure I follow the reasoning here, as there is only a single use of undef. Undef can take a different value for each direct use, but not for each chain of operations (unless the intermediate ones also yield undef) ... or not?

**Comment by nikic** [comment]
Or more specifically, expanding `uadd_overflow %a, %b` into `{add %a, %b; does_add_overflow %a, %b}` is illegal because it duplicates uses -- but your reasoning, if I understand it correctly, seems to be based on such an expansion?

**Comment by nunoplopes** [comment]
There are 2 uses of %x. Since `x + undef` is `undef`, the 2 uses of %X can evaluate to any value.
`undef` may evaluate to any value in any recursive use. For example:
```
%x = undef
%y = %x + 1
%z = %y + 2
use(%z)  ; can be replaced with use(undef)
use(%z)  ; can also be replaced with use(undef)
```

**Comment by nikic** [comment]
There are two uses of `%X`, but `%X` itself is not undef.

**Comment by nunoplopes** [comment]
actually it is (if %a != 0):
```
----------------------------------------
  %X = uadd_overflow i8 1, undef
  %Op = extractvalue {i8, i1} %X, 0
  %Ov = extractvalue {i8, i1} %X, 1
=>
  %X = uadd_overflow i8 1, undef
  %Op = undef
  %Ov = undef

Done: 1
Optimization is correct!
```

**Comment by LebedevRI** [comment]
The particular fold i'm trying to prove:
```
$ ~/src/alive2/build-Clang-release/alive -smt-to:100000 /tmp/test.opt 
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Processing /tmp/test.opt..

----------------------------------------
Name: res is undef
  %X = uadd_overflow i8 %a, undef
  %Op = extractvalue {i8, i1} %X, 0
  %Ov = extractvalue {i8, i1} %X, 1
=>
  %X = uadd_overflow i8 %a, undef
  %Op = undef
  %Ov = 0

Done: 1
Optimization is correct!
```
(finally tried `-smt-to:100000`)
