### ISSUE TITLE
Perf regression with integer-based ptr comparison

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#717]
I'm seeing a significant perf regression after https://github.com/AliveToolkit/alive2/commit/2b4ee318b5b1f939439cf4fc65debc8096694163. Subsequent optimization didn't help much @aqjune.
gzip shows no regression. bzip2 (worst in perf), oggenc, ph7, sqlite3, gcc (worst in % drop in verified).

The most common pattern is comparison of a ptr arg with null, e.g.:
```c
if (p == null)
  return;
*p = 42;
```
(sometimes with a gep before the store/load)

I also see comparisons of return of fncalls with null. And comparison of loaded gvar with an argument.

A useful observation is that addresses are never observed in these functions. For the program above there are 4 cases:
1. p is null (early return)
2. p is OOB and zero (early return)
3. p is OOB and non-zero (UB)
4. p is in-bounds

The exact address of p is irrelevant. However, detection of case 2. requires to prove that `-offset == base_addr`.
Moreover, in these functions the overlapping of addresses between blocks is irrelevant, as they are not observed. (though important for counter-examples, but let's ignore that for a second).

Some ideas:
 - Skip emission of non-overlapping addresses axiom when addresses are not observed (with a more relaxed definition). This might be harder than it sounds as e.g. `p + i == null && q + i == null` cannot imply that p/q are equal.
 - Change non-local overlapping addresses axiom to use a quantifier when using more than x arguments, or when we think addresses aren't observed (no int2ptr/ptr2int or only 1). Hopefully Z3 will only instantiate the axioms lazily and therefore we save some formula size.
 - Specialize pointers to have an extra `is_zero` bit to cover functions that don't do int2ptr/ptr2int but do comparisons with null only (to cover case 2. above).
 - Split observability into local/non-local to avoid instantiating axioms unnecessarily

Other cases that can be optimized:
- [x] non-eq/ne between inbounds ptrs of same base ptr.

Other crazy ideas?

**Comment by aqjune** [comment]
> A useful observation is that addresses are never observed in these functions. For the program above there are 4 cases:
> 
> 1. p is null (early return)
> 2. p is OOB and zero (early return)
> 3. p is OOB and non-zero (UB)
> 4. p is in-bounds

The second case seems problematic indeed.
A random thought is that in the source language (C) an OOB pointer cannot be passed as an input argument.
I don't know whether allowing it will miss any bug in practice... what do you think?

> 
> The exact address of p is irrelevant. However, detection of case 2. requires to prove that `-offset == base_addr`.
> Moreover, in these functions the overlapping of addresses between blocks is irrelevant, as they are not observed. (though important for counter-examples, but let's ignore that for a second).
> 
> Some ideas:
> 
> * Skip emission of non-overlapping addresses axiom when addresses are not observed (with a more relaxed definition). This might be harder than it sounds as e.g. `p + i == null && q + i == null` cannot imply that p/q are equal.

Would having separate flags for observedness of local block addresses and non-local block addresses work?
For example, if we know that all icmps and ptrtoints have nonlocal pointers as operands, local blocks' address encoding isn't necessary.

> * Specialize pointers to have an extra `is_zero` bit to cover functions that don't do int2ptr/ptr2int but do comparisons with null only (to cover case 2. above).

This would sounds like an interesting idea to me.

> Other cases that can be optimized:
> 
> * [ ]  non-eq/ne between inbounds ptrs of same base ptr.

This won't be very complex...

> Other crazy ideas?

I'll leave my idea here whenever I get one.

**Comment by nunoplopes** [comment]
>> 1. p is null (early return)
>> 2. p is OOB and zero (early return)
>> 3. p is OOB and non-zero (UB)
>> 4. p is in-bounds
> 
> The second case seems problematic indeed.
> A random thought is that in the source language (C) an OOB pointer cannot be passed as an input argument.
> I don't know whether allowing it will miss any bug in practice... what do you think?

Nah, cmon, we can't do that. Loop optimizations + function outlining can easily pass OOB pointers around.

(sorry, edited your comment instead of quoting. I've reverted to the original state hopefully)

**Comment by aqjune** [comment]
Okay, I'll send a patch for the non-eq/ne between inbounds ptrs of same base ptr first. This will be super simple.

I can test having separate flags for observedness of local block addresses and non-local block addresses as well, but for bzip2/gzip benchmarks only

The obstacle from running oggenc is that a weird assertion failure from Memory::alloc is happening. I didnt' try ph7 and above yet. I should look into this.

**Comment by nunoplopes** [comment]
I fear the optimization of ptr comparison is not correct w.r.t. to undef ptrs:
```llvm
%p = gep undef, 0
%q = gep %p, 1
%r = gep %p, 2

%cmp = icmp eq %q, %r
```

While %q/%r have the same base, their bid may be different. In practice it may not matter as it's highly unlikely LLVM would replace %p with different ptrs. But keeping this here for future reference.
