### ISSUE TITLE
[Q] Not modelling `Optimization outside atomic` correctly

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#735]
If i'm reading https://llvm.org/docs/Atomics.html#optimization-outside-atomic / https://reviews.llvm.org/D107281#2922901
correctly, this should not verify: https://alive2.llvm.org/ce/z/F7ctum

**Comment by nunoplopes** [comment]
Right, it's true it's generally illegal to introduce stores. The test case you refer should fail to verify, yes.
Alive2 doesn't model any concurrency ATM. We already have a ticket open about this: https://github.com/AliveToolkit/alive2/issues/183

Can't promise any timeline to implement support for this stuff, sorry. Need a new student 😅
