### ISSUE TITLE
Printing single varvals after UB has been triggered

### ISSUE THREAD

**Issue by ezyang** [AliveToolkit/alive2#739]
I'm trying to understand the meaning of the output of Alive2 in https://alive2.llvm.org/ce/z/KUy5dq , specifically the counterexample on this function:

```
define i1 @tgt(* %0, i8 %1, * %2, i8 %3) {
%4:
  %7 = icmp ne i8 %1, 0
  %8 = icmp ne i8 %3, 0
  %9 = xor i1 %7, %8
  br i1 %9, label %6, label %5

%5:
  %10 = icmp ne * %0, %2
  %11 = select i1 %8, i1 %10, i1 0
  br label %6

%6:
  %12 = phi i1 [ 1, %4 ], [ %11, %5 ]
  ret i1 %12
}

Example:
* %0 = poison
i8 %1 = #x00 (0)
* %2 = poison
i8 %3 = poison

Target:
i1 %7 = #x0 (0)
i1 %8 = poison
i1 %9 = poison
i1 %10 = poison
i1 %11 = poison
i1 %12 = any
```

If I understand correctly, in this example, %9 is poison and we branched on it triggering immediate UB. But Alive2 then soldiers on and prints out all the varvals, as well as a very confusing "any" variable for the last value (ostensibly because it's unconstrained post UB.) Would it be better for Alive2 not to print the varvals after the UB, and instead say "hey, UB happened on the instruction that computed %9, nothing left to do pack it up go home"?

I think I might be able to write this patch, if y'all agree it would be useful. To be explicit, I'm imagining the output looks instead like:

```
Target:
i1 %7 = #x0 (0)
i1 %8 = poison
i1 %9 = undefined behavior triggered
```

**Comment by regehr** [comment]
I'm not sure that this patch would be straightforward, but Nuno of course is the best person to answer that.

But also, we're working on a different solution to this problem, which is an interpreter based on alive. Once that's working better, we can explain counterexamples in terms interpreter results, which naturally will not contain the problem you describe here.

**Comment by aqjune** [comment]
You might want to look into the discussion in #64 as well.
There are at least two possible approaches I think:
1. Refactor `State` to store UB-per-instruction info when symbolically executing src/tgts
2. Re-run symbolic execution of the target with the concretized input and see where we should stop (probably symexec.cpp  should be slightly updated to support this, but not sure).

**Comment by nunoplopes** [comment]
I agree, the best way is to keep track of UB per instruction. Then because of undef we may need additional SMT queries to determine whether it's UB or not (as we do determine whether a value is fully undef or not).

**Comment by ezyang** [comment]
Thanks for the commentary. Happy to wait for the interpreter to show up!
