### ISSUE TITLE
Alive2 seems to not consider calls may unwind or not return before @llvm.assume.

### ISSUE THREAD

**Issue by fhahn** [AliveToolkit/alive2#742]
It looks like Alive2 does not consider that calls before `@llvm.assume` may unwind or may not return.

Consider the example below. The `llvm.assume` may not execute, e.g.  if `@may_unwind_or_not_return` does not return or raise an exception. In that case, I do not think we can assume that the condition of the `@llvm.assume` holds and cannot simplify `%c.1` to false.

But Alive2 verifies the code below as correct: https://alive2.llvm.org/ce/z/QKvWYR

```
declare void @llvm.assume(i1 noundef)
declare void @may_unwind_or_not_return()
declare void @use(i1)

define i1 @src(i8 %a, i8 %b, i1 %c) {
  %c.1 = icmp ne i8 %a, %b
  call void @use(i1 %c.1)

  call void @may_unwind_or_not_return()

  %c.2 = icmp eq i8 %a, %b
  call void @llvm.assume(i1 %c.2)
  ret i1 %c.1
}

define i1 @tgt(i8 %a, i8 %b, i1 %c) {
  %c.1 = icmp ne i8 %a, %b
  call void @use(i1 false)

  call void @may_unwind_or_not_return()

  %c.2 = icmp eq i8 %a, %b
  call void @llvm.assume(i1 %c.2)
  ret i1 %c.1
}
```

**Comment by nunoplopes** [comment]
oh dear, this uncovered quite a few bugs in LLVM.
New test failures:
```
+  LLVM :: Transforms/EarlyCSE/globalsaa-memoryssa.ll
+  LLVM :: Transforms/LoopIdiom/X86/arithmetic-right-shift-until-zero.ll
+  LLVM :: Transforms/LoopIdiom/X86/left-shift-until-zero.ll
+  LLVM :: Transforms/LoopIdiom/X86/logical-right-shift-until-zero-debuginfo.ll
+  LLVM :: Transforms/LoopIdiom/X86/logical-right-shift-until-zero.ll
+  LLVM :: Transforms/LoopUnroll/loop-remarks.ll
+  LLVM :: Transforms/LoopUnswitch/preserve-analyses.ll
+  LLVM :: Transforms/SimpleLoopUnswitch/delete-dead-blocks.ll
+  LLVM :: Transforms/SimpleLoopUnswitch/nontrivial-unswitch-cost.ll
```

**Comment by LebedevRI** [comment]
Hah, i was pretty much confident this/#726 (please fix it!1) would expose problems in loopidioms (:

**Comment by nunoplopes** [comment]
I'm a bit confused now, though.
Going to LangRef I realized there's willreturn, nounwind, and mustprogress! Trying to figure out what's the correct condition to remove a function call.

**Comment by fhahn** [comment]
> Going to LangRef I realized there's willreturn, nounwind, and mustprogress! Trying to figure out what's the correct condition to remove a function call.

IIUC the main reason `willreturn` has been introduced is to remove the previously implicit assumption that LLVM IR functions always return (and hence not returning is UB). Now not returnin/looping infinitely is a valid side effect and we cannot remove a function call unless we know it will return. This effectively requires the called function to be `willreturn` (or the calling function is `willreturn`, which implies `willreturn` for all called functions). For example, see https://reviews.llvm.org/D94106 which updated `wouldInstructionBeTriviallyDead` to handle `willreturn`.

I'm not surprised that there are places that get this wrong at the moment, as the enforcement of the attribute is relatively new and not all transforms have been updated. Thanks to Alive2 we can now surface more sources of issues :)

**Comment by nunoplopes** [comment]
> > Going to LangRef I realized there's willreturn, nounwind, and mustprogress! Trying to figure out what's the correct condition to remove a function call.
> 
> IIUC the main reason `willreturn` has been introduced is to remove the previously implicit assumption that LLVM IR functions always return (and hence not returning is UB). Now not returnin/looping infinitely is a valid side effect and we cannot remove a function call unless we know it will return. This effectively requires the called function to be `willreturn` (or the calling function is `willreturn`, which implies `willreturn` for all called functions). For example, see https://reviews.llvm.org/D94106 which updated `wouldInstructionBeTriviallyDead` to handle `willreturn`.

Thanks for the pointers!

Ok, so the correct condition for call deletion is something like: `willreturn && nounwind && nowrite`, which is what the mentioned patch does.
Alive2 doesn't support exceptions yet, though. Arg, infinite todo list 😅
