### ISSUE TITLE
Missing support for inaccessiblememonly

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#746]
Test `SLPVectorizer/int_sideeffect.ll` is now failing because of missing support for `inaccessiblememonly`:
```llvm
  call void @foo() inaccessiblememonly
```

In that file we also miss support for:
```llvm
  call void @llvm.sideeffect()
```
(whatever that is 😀)

**Comment by aqjune** [comment]
Would it make sense if it is encoded as a function that only touches `num_nonlocals_src - 1`? It is a block reserved for encoding the memory touched by calls.
If it is okay, maybe I can try to write a pull request for this. I hope it won't be too complicated.

**Comment by nunoplopes** [comment]
But then other functions can still access that memory.
I guess we need one extra block per each inaccessiblememonly function.

**Comment by aqjune** [comment]
I see, so an unknown function call cannot touch the inaccessible memory.

Hmm.... I became to think that the meaning of inaccessiblememonly is not clear. :(
Perhaps it requires the background about why the attribute was introduced, which is what I don't have.

I listed a few transformations that involve the attribute.
It is assumed that `g()` and `g2()` are inaccessiblememonly whereas `f()` is a plain function.

1. `f(); g(); => g(); f();` <- must be supported, IIUC

2. `g(1); g(2); => g(2); g(1);`

2-1.
```
  if (x) { g(1); } else { g(2); }
=>
  g(x ? 1 : 2);
```

3. `g(); g2(); => g2(); g();`

I think calls to the same inaccessiblememonly function must touch the same block to support 2-1.
To me, it isn't clear whether 3 must be supported or not; the documentation only says that it touches the memory that is not accessible by the module being compiled.

**Comment by nunoplopes** [comment]
The idea is a function may access e.g. a global variable but no other function can touch that global variable.
So the function reads & writes memory, but *only* accesses private state to that function.
Calls to such functions can't be reordered wrt to each other nor be removed.

e.g. if f has inaccessiblememonly tag:
```
f(); store => store; f()   : valid
f(1); f(2); => f(2); f(1)  : invalid
f(); g() => g(); f()       : valid if f() is willreturn & nounwind
```

All functions can touch the fn block. We could restrict them to touch a single byte of that block, true. It's just a question of what's the simplest (or better performing) encoding 😀

**Comment by aqjune** [comment]
Okay, then what about this -- there is one inaccessiblememonly block, and each inaccessiblememonly function f_i can touch i'th byte of the block only. The block's size is exactly N bytes where N is # of inaccessiblememonly fns.

**Comment by nunoplopes** [comment]
sounds good!
