### ISSUE TITLE
"The source program doesn't reach a return instruction." due to newly created phi instruction

### ISSUE THREAD

**Issue by BalaRishi-AMD** [AliveToolkit/alive2#757]
**Facing "ERROR: The source program doesn't reach a return instruction." when phi instruction was introduced.**

$ diff issue_2_1.ll issue_2_2.ll
'41c41,42
'<   %sext = shl i64 %c.pn.add.i, 32
'---
'>   %c.pn.add.i.lcssa = phi i64 [ %c.pn.add.i, %while.cond.i ]
'>   %sext = shl i64 %c.pn.add.i.lcssa, 32

$ alive-tv issue_2_1.ll issue_2_2.ll | tail -8
ERROR: The source program doesn't reach a return instruction.
Consider increasing the unroll factor if it has loops

Summary:
  1 correct transformations
  0 incorrect transformations
  1 failed-to-prove transformations
  0 Alive2 errors

Attached .ll files.

[issue_2.zip](https://github.com/AliveToolkit/alive2/files/7383713/issue_2.zip)

**Comment by nunoplopes** [comment]
The error is correct. The loop iterates twice before it exits (as you store 3 to `@f`; if you change that store to 0 the loop exits on the first iteration).

When dealing with loops you need to specify the unroll factor by hand as Alive2 can't do that for you automatically yet. For this example, if you run with `-src-unroll=2 -tgt-unroll=2` it goes through.
