### ISSUE TITLE
"ERROR: Precondition is always false" for change in order of add operands

### ISSUE THREAD

**Issue by BalaRishi-AMD** [AliveToolkit/alive2#764]
Issue, #752, is faced for add operands:

'$ diff  expr.tab_reduced.ll expr.tab_reduced_2.ll
'1536c1536
'<   %add42 = add i64 %yysize.0152, %call41
'---
'>   %add42 = add i64 %call41, %yysize.0152

'$ alive-tv expr.tab_reduced_1.ll expr.tab_reduced_2.ll | tail | head -1
'ERROR: Precondition is always false

Attached .ll files.
[issue_3.zip](https://github.com/AliveToolkit/alive2/files/7455292/issue_3.zip)

Thanks

**Comment by regehr** [comment]
so I suspect what might be happening here is the test case fundamentally boils down to "unreachable" and the swapped operands are simply allowing alive to bypass its refusal to check syntactically identical src+tgt pairs

**Comment by nunoplopes** [comment]
This is the same as #757: you need to specify the loop unrolling.
You can verify a file against itself by using `-always-verify` to skip the syntactic identity test. Something like this:
```./alive-tv expr.tab_reduced_1.ll expr.tab_reduced_1.ll -always-verify -src-unroll=4 -tgt-unroll=4 -smt-to=100000```
