### ISSUE TITLE
missing pred in icmp should fail to parse

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#78]
```
----------------------------------------
Name: zz
  %r = icmp i4 %o1, %y
=>
  %r = icmp eq i4 %o1, %y

Done: 1
Optimization is correct!

----------------------------------------
Name: z2
  %r = icmp i4 %o1, %y
=>
  %r = icmp ne i4 %o1, %y

Done: 1
Optimization is correct!

```

**Comment by regehr** [comment]
if you look in the parser, it parses this code as an ICmp::Any instead of erroring out, but then later Any is treated as unreachable. I'm not sure what Nuno was thinking about here, we should wait for him to weigh in (he has some vacation coming up so this may not be real soon).

**Comment by nunoplopes** [comment]
Right, the idea was to support optimizations that are generic on the comparison operator (like Alive does).
I don't think I finished implementing this feature. I'll have look, thanks!

**Comment by nunoplopes** [comment]
The transformation above fails verification now (as expected). The counterexample doesn't show the icmp predicate, but this feature isn't used enough ATM that warrants more time spent on this.

**Comment by LebedevRI** [comment]
Thank you for looking into it!
