### ISSUE TITLE
Transformation incorrectly verified as correct for function with infinite loop with an assume & regular function call

### ISSUE THREAD

**Issue by fhahn** [AliveToolkit/alive2#780]
Alive2 verifies the following transformation as correct https://alive2.llvm.org/ce/z/RUB57g. The only difference between `@src` and `@tgt` is

```
- call void @use(i1 %c.1)
+ call void @use(i1 true)
```

I believe the transformation is *incorrect*. The `@llvm.assuem` call may not be executed, e.g. if `@use` doesn't terminate or unwinds.

```
declare void @llvm.assume(i1)

declare void @use(i1)

define i1 @src(i16 %a, i1 %c) {
entry:
  br i1 %c, label %then, label %exit

then:
  %c.1 = icmp eq i16 %a, 0
  call void @use(i1 %c.1)
  call void @llvm.assume(i1 %c.1)
  br label %then

exit:
  %c.2 = icmp eq i16 %a, 0
  ret i1 %c.2
}

define i1 @tgt(i16 %a, i1 %c) {
entry:
  br i1 %c, label %then, label %exit

then:
  %c.1 = icmp eq i16 %a, 0
  call void @use(i1 true)
  call void @llvm.assume(i1 %c.1)
  br label %then

exit:
  %c.2 = icmp eq i16 %a, 0
  ret i1 %c.2
}
```

**Comment by nunoplopes** [comment]
This is a dup of #726.
Unfortunately Alive2 can't handle infinite loops ATM. I can't offer a timeline for implementing this as it's a big feature. Need to find a good student.

Apple doesn't fund academia, otherwise I would be knocking on your door to fund this 😅

**Comment by LebedevRI** [comment]
Are you sure it's the same bug?
It seems like calling non-`isGuaranteedToTransferExecutionToSuccessor()` function should effectively act as a "barrier" that splits the block into two.

**Comment by nunoplopes** [comment]
Yep, it's the same problem. Alive2 only verifies paths that reach a return instruction. Everything else is ignored. This loop has no exit edge, so nothing is checked regardless of the unroll factor.

What you wrote makes sense, and gave me an idea! But it's still a non-trivial change. I'm teaching until mid July.. It's unlikely I have time to focus on complex stuff in the meantime.
