### ISSUE TITLE
flags on phis?

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#793]
Here's one that alive-tv flags as a value mismatch: https://alive2.llvm.org/ce/z/rrampN

```llvm
define float @spec_select_fp5(float %a, float %b, float %c) {
entry:
  %t1 = fcmp oeq float %b, 0.0
  br i1 %t1, label %bb1, label %bb3

bb1:
  %t2 = fcmp ogt float %c, %c
  br i1 %t2, label %bb2, label %bb3

bb2:
  br label %bb3

bb3:
  %t4 = phi nsz float [ %a, %entry ], [ %b, %bb1 ], [ %c, %bb2 ]
  ret float %t4
}
```

@zhengyang92 says this is likely because we don't support flags on phi nodes, I guess we should try to either fix this or else error out so we don't get false or missed alarms

**Comment by aqjune** [comment]
I think this can be naturally supported if nsz/nnan/ninf fast math flags are splitted as an instruction in Alive2. For example:
```
%t4 = phi nsz float [ %a, %entry ], [ %b, %bb1 ], [ %c, %bb2 ]
```
=>
```
%t4.0 = phi float [ %a, %entry ], [ %b, %bb1 ], [ %c, %bb2 ]
%t4 = fast_math_flag nsz %t4.0
```
select and call also has fast math flags, and I guess it is likely that more ops will have fast math flags. This approach is extensible as it will still work after new ops are fast-math-flags added.

**Comment by nunoplopes** [comment]
@aqjune that doesn't work with some flags as some apply to both inputs as outputs. Plus reassoc is complicated to implement that way as you need the operation as well.

**Comment by aqjune** [comment]
I think in the argument case the input can be `fast_math_flag`-applied:
```
  %z = fadd ninf %x, %y
=>
  %x.0 = fast_math_flag ninf %x
  %y.0 = fast_math_flag ninf %y
  %z.0 = fadd %x.0 %y.0
  %z   = fast_math_flag ninf %x.0, %y.0
```
Limited to the three flags above (nsz/nnan/ninf) it would work. I think the existing code https://github.com/AliveToolkit/alive2/blob/master/ir/instr.cpp#L657 is implicitly implementing it.
