### ISSUE TITLE
feature request: log files contain info to duplicate the issue

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#807]
right now our log files contain the source filename and the alive2 output, but they don't say what opt pass was run. I tried to add this but found that it's hard to look at the command line options from our opt pass (of course this is easy from alive-tv where we control main, but that's not what I want here).

I'm not trying to get anyone to implement this, just wanted to discuss what might be the correct way to do it, so I can implement something clean.

**Comment by nunoplopes** [comment]
I don't know the answer from the top of my head.
But I've noticed that when the process crashes we get the full cmd line. So the answer may be in LLVM's crash handler.

**Comment by nunoplopes** [comment]
John added this already.
