### ISSUE TITLE
feature request: tools::Transform should allow more than one comparison on a function

### ISSUE THREAD

**Issue by nlewycky** [AliveToolkit/alive2#812]
Presently `tools::Transform` takes two `IR::Function`s by move-only since it takes them by ownership and `ir::Function` does not allow copying. Also, `Transform::preprocess()` operates on the two IR::Functions `src` and `tgt` in the Transform. It'd be nice to do one pass over all my functions in my candidate equivalence class and preprocess them as far as we can individually, all the way down to Z3 if possible, then do the comparisons. From the API design it looks like calling `Transform::preprocess()` is optional but preferred when possible, so it should be safe to create a parial-preprocess that works on a single function.

What I'd like to do is query a whole batch of functions for similarity because I'm looking to split them into equivalence classes, with the expected case being that they are all equivalent. Using "≤" to represent refines-into, I'd like to do fn0 ≤ fn1 ≤ fn2 ≤ ... ≤ fn`n` ≤ fn0. This is faster than bidirectional verification over each element pair.

**Comment by regehr** [comment]
that's a pretty interesting use case, can you say more about how this comes about?

**Comment by nlewycky** [comment]
Suppose you want to generate ConstantFold.cpp. One of the goals of the constant folder is that given two expressions that are equivalent, it should try to return one of them, so that the customer can use pointer-equality to trivially see that the expressions are equivalent (and if they aren't, trying to check for equality again is likely to be unfruitful).

I'm generating every expression up to a given size, then forming "likely" equivalence classes found by running a set of values through the expressions and looking at the result. With that done, I'd like to break it up into real equivalence classes based on Ailve2 results.

So one comparison pair fn0 and fn1 returns that I may refine fn0 into fn1. Then the next comparison I want to do is fn1 into fn2, continuing the chain of reasoning. Every fn will get be used in two comparisons in the best case. The final comparison checks that we may refine the last fn into fn0.

In the other case, we discover that the two functions are not equivalent. We extract the assignments that make this visible using #813 , then we evaluate all the functions in our list using that evaluator to see what outputs we get. The two that compared unequal must produce different values under this comparison, but there's no reason to expect that we'll only find two equivalence classes hiding in our list. We may find that this variable assignment produces many different values over the input expressions, despite them all being in our "likely" equivalence class. (In practice my largest "likely" equivalence class is 2.1 million functions because `udiv` and `sdiv` and `ashr` and `lshr` will produce `0` on a ton of different inputs.)

**Comment by nunoplopes** [comment]
The main issue is that right now we may be optimizing a bit too much for your use case.
We preprocess src,tgt pairs and optimize everything based on those programs. For example, we shrink the bitwidth of the internal pointer representation, we check whether a NULL block is needed, etc.
For that use case, we would need to do a union (worst-case) of all function pairs. Conceptually it's not complicated, but the code needs a bit of a refactoring to make it work.

I'm quite curious about what the heck you're brewing 🙂

**Comment by nunoplopes** [comment]
I'm closing this as Nick indicated he doesn't need this straight away and I think these features need to be developed together with a driver, otherwise they end up being over/under-engineered.
