### ISSUE TITLE
feature request: get the unsat-core model back from TransformVerify

### ISSUE THREAD

**Issue by nlewycky** [AliveToolkit/alive2#813]
When a `TransformVerify` fails, Alive2 prints out the counter-example. There doesn't seem to be a way to retrieve this unsat core model through the API without having Alive2 print it out. It'd be great to get the assignments of free variables to specific values back from Alive2, preferably in the form of `map<Value *, Constant *>` with the `GlobalVariable`/`LoadInst`/`Argument`/etc on the left.

It looks like this is pretty close to being possible in that `src_state` and `tgt_state` returned by `TransformVerify::exec()` probably have the right information, but exec() doesn't do all the work that `verify()` does, and verify() doesn't return the states.

**Comment by regehr** [comment]
there's a related project that we've not yet done much work on, which is to create a simplification loop for counterexamples. we should do things like:
- avoid undef unless no undef-free counterexample exists
- avoid poison unless no poison-free counterexample exists
- make integer constants have minimum magnitude
- make memory blocks as few and as small as possible
- make offsets into memory blocks as small as possible

**Comment by nunoplopes** [comment]
Do you need something low level such as the SMT model, or would you want something high-level like assignments to LLVM instructions?
If the latter, maybe we could add a callback to "print" the error and provide such info?

`exec()` doesn't do all the work, right. It was added just for alive-exec, so it can do symbolic execution line-by-line.
BTW, what's your use case? It would help me understand exactly what you need.

P.S.: Nice to see you around Nick!

**Comment by nlewycky** [comment]
Ultimately I want it in terms of my original representation, as an assignment of free variables (`llvm::Argument`s) to `int`s. I don't need the intermediate instructions. I could form this pretty easily given the argument number. My internal representation isn't an IR, it's a DAG represented as an adjacency list with some dense `vector<vector<uint8_t>>` paired with a `vector<enum WhatKindOfInstruction>` to indicate what each node's instruction is. It's intended to make brute-force enumeration of every expression as fast as possible.

I'm building equivalence classes starting off by running my own evaluator over my representation (allocates a fixed amount of memory, once, to evaluate a graph). I tried some values on my own to form equivalence classes before sending them to Alive2, then I use Alive2 to verify that my equivalence classes are correct. If that verification fails, I want to take the assignments for the free variables (llvm::Arguments) and try them out on my entire list to refine it into more new equivalence classes. Just checking on a single value-assignment will be faster than comparing every function pair with Alive2/Z3 for equality.

PS. Hey Nuno! Long time! I was googling for see how to use Z3 sorts so I could implement disjoint union of bitvec and "undef" in Z3, and found this really useful stackoverflow answer explaining that Z3 sorts aren't really useful. Of course, it was you who had asked the question, and for the exact same reason as me, but years earlier. Thanks!! :-)

**Comment by nunoplopes** [comment]
I'm closing this as Nick indicated he doesn't need this straight away and I think these features need to be developed together with a driver, otherwise they end up being over/under-engineered.
