### ISSUE TITLE
feature request: value synthesis

### ISSUE THREAD

**Issue by nlewycky** [AliveToolkit/alive2#814]
I'd like to check something like:
```
  %A = mul i32 %0, ?
  %r = add i32 %A, %1
=>
  %r = sub %1, %0
```
where Alive2 solves for the `?`. Syntactically, I think we could express this identifiably in llvm IR with a load of global variable with a special name (say, a "alive2.synthesize." prefix?):
```
@alive2.synthesize.foo = extern global i32
define i32 @src(i32, i32) {
  %A = load i32, i32* @alive2.synthesize.foo
  %B = mul %0, %A
  %C = add i32 %1, %B
  ret i32 %C
}
define i32 @tgt(i32, i32) {
  %A = sub i32 %1, %0
  ret i32 %A
}
```

This also lets us express reuse of the same synthesized value, multiple synthesized values, and sharing the same synthesized value across both `@src` and `@tgt` (for example, given `mul %x, cst = cst`, solve for `cst`).

I think that if lowered to an exists in Z3 then Z3 would solve it. We can further assume that the constant isn't undef or poison. Storing to the global should probably be disallowed for simplicity.

I'm not sure what the status is of the non LLVM IR parser. If we want this feature in there too, we could try adding `Pre: Synthesize(%x)`.

**Comment by regehr** [comment]
@zhengyang92 has an alive2-based synthesizer -- maybe you two can chat a bit, or we'll all have a call?

**Comment by zhengyang92** [comment]
Hi @nlewycky ,

Yes we do have a alive2 based synthesizer which can do value synthesis, and we have a separate command line interface for the task which is called `minotaur-cs` (abbr for minotaur constant synthesizer). There is some changes that needs to be done to fit your problem in `minotaur-cs`.

1) Because the research problem we're attacking, which is automatically discovering correct RHSs that refines the LHS, our synthesizer is only able to synthesize values in the RHS. We need some more effort if we want the synthesizer solve values on LHS.

2) And instead of using globals, we uses function parameters to specify which value to be synthesized.

For your problem, here's the tool's output

```
liuz@supermicro:~/minotaur/build$ cat foo.ll


define i32 @src(i32, i32, i32 %_reservedc) {
  %A = sub i32 %1, %0
  ret i32 %A
}


define i32 @tgt(i32, i32, i32 %_reservedc) {
  %B = mul i32 %0, %_reservedc
  %C = add i32 %1, %B
  ret i32 %C
}
liuz@supermicro:~/minotaur/build$ time ./minotaur-cs foo.ll

----------------------------------------
define i32 @src(i32 %0, i32 %1, i32 %_reservedc) {
%2:
  %A = sub i32 %1, %0
  ret i32 %A
}
=>
define i32 @tgt(i32 %0, i32 %1, i32 %_reservedc) {
%2:
  %B = mul i32 %0, %_reservedc
  %C = add i32 %1, %B
  ret i32 %C
}
;result
i32 %_reservedc = #xffffffff (4294967295, -1)

real    0m0.029s
user    0m0.004s
sys     0m0.026s
```

Our tool supports some larger examples,  such as this one
```
liuz@supermicro:~/minotaur/build$ cat ../tests/const/diff2.constsyn.ll
define <8 x i32> @src(<16 x i16> %0, <16 x i16> %_reservedc) {
entry:
    %1 = bitcast <16 x i16> %0 to <8 x i32>
    %2 = call <8 x i32> @llvm.x86.avx2.psrai.d(<8 x i32> %1, i32 16)
    %3 = call <8 x i32> @llvm.x86.avx2.pmadd.wd(<16 x i16> %0, <16 x i16> <i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0>)
    %4 = sub nsw <8 x i32> %3, %2
    ret <8 x i32> %4
}

define <8 x i32> @tgt(<16 x i16> %0, <16 x i16> %_reservedc) {
entry:
    %intr = call <8 x i32> @llvm.x86.avx2.pmadd.wd(<16 x i16> %0, <16 x i16> %_reservedc)
    ret <8 x i32> %intr
}


declare <8 x i32> @llvm.x86.avx2.pmadd.wd(<16 x i16>, <16 x i16>)
declare <8 x i32> @llvm.x86.avx2.psrai.d(<8 x i32>, i32)

liuz@supermicro:~/minotaur/build$ time ./minotaur-cs ../tests/const/diff2.constsyn.ll

----------------------------------------
define <8 x i32> @src(<16 x i16> %0, <16 x i16> %_reservedc) {
%entry:
  %1 = bitcast <16 x i16> %0 to <8 x i32>
  %2 = x86_avx2_psrai_d <8 x i32> %1, i32 16
  %3 = x86_avx2_pmadd_wd <16 x i16> %0, <16 x i16> { 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0 }
  %4 = sub nsw <8 x i32> %3, %2
  ret <8 x i32> %4
}
=>
define <8 x i32> @tgt(<16 x i16> %0, <16 x i16> %_reservedc) {
%entry:
  %intr = x86_avx2_pmadd_wd <16 x i16> %0, <16 x i16> %_reservedc
  ret <8 x i32> %intr
}
;result
<16 x i16> %_reservedc = < #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1), #x0001 (1), #xffff (65535, -1) >


real    0m0.205s
user    0m0.189s
sys     0m0.016s
```


Do these suit your need? Sure we can definitely have a call if you want know more.

**Comment by nlewycky** [comment]
That is very cool.

I am going to need the ability to refer to the same constant on both sides, though I can make use of using variables on one side only to start with. Using arguments is a fine API as long as I can refer to the same value on both sides, for instance by choosing the same name. I'll also need more than one, say by allowing "foo_reservedc" and "bar_reservedc" but I think that's easy to add now.

I'm going to keep reading through minotaur's AliveInterface.cpp and EnumerativeSynthesis.cpp and try to understand them.

**Comment by zhengyang92** [comment]
> I'll also need more than one, say by allowing "foo_reservedc" and "bar_reservedc" but I think that's easy to add now.

It supports multiple value synthesis, you just need to make sure the all the value to be synthesized has names start with `_reservedc`.

**Comment by regehr** [comment]
I think a reasonable way to proceed here would be for Nick to post a few examples that he'd like to synthesize and then Zhengyang either synthesizes them or else says why Minotaur current cannot do that. from there I think we will be able to rapidly understand where our current technology differs from what Nick needs!

also, separately, I will talk to Nick about Manasij's work, which is also highly relevant here

**Comment by zhengyang92** [comment]
> With my current code it seems it can handles constants in the LHS without any change, but I havent tested yet.

I just tested it with reserved constant used in the LHS, it works out-of-box.

**Comment by nunoplopes** [comment]
Dup of #83
