### ISSUE TITLE
TV report file name problem

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#82]
after a TV run with logging to file enabled, we end up with lots of files called something like 

```<stdin>_2776131420.txt```

not sure yet what's the best solution.

**Comment by nunoplopes** [comment]
There isn't nothing we can do to name the files properly since `opt` doesn't the receive the file name.
My idea was to print the file name when we detect a failure. We cannot always print the filename because some tests are really strict in the pattern matching of the output.

**Comment by regehr** [comment]
yeah. I'm trying to think of a solution that doesn't involve hacking lit. if we can't track outputs back to test cases it's really inconvenient for users.

**Comment by regehr** [comment]
Even when file names are available, I'm seeing a lot of this sort of thing:
```
Source: /home/regehr/llvm/build/test/Transforms/GCOVProfiling/Output/return-block.ll.tmp/2
```
of course in this case it's not hard to heuristically find the original test case file name (so we can link to it) but I'm thinking it may be better to just hack lit a bit to stash file names somewhere, does that seem reasonable, @nunoplopes ?

**Comment by nunoplopes** [comment]
The filename is retrieved from LLVM (https://github.com/AliveToolkit/alive2/blob/master/tv/tv.cpp#L158).
I agree the only reliable way would be to hack lit to pass a `-tv-report-name` or whatever to `opt`.
For statistics, probably we don't need to pin point the exact report for passing tests. Though it's probably useful to get the report for failing tests (hence my suggestion to print the filename for failed tests). I was just trying to avoid hacking lit. If we do it, I think we should push those patches upstream at least.

**Comment by regehr** [comment]
agreed. I'll look into it more.

**Comment by nunoplopes** [comment]
Ok, the opt plugin now prints the log name on error. It's sufficient to grep for that in lit's log.
