### ISSUE TITLE
Verification of small number of math operations with i8 inputs never completes, but all inputs can be exhaustively checked in <1 min

### ISSUE THREAD

**Issue by fhahn** [AliveToolkit/alive2#853]
It looks like Alive2 isn't able to verify the source snippet below in a reasonable amount of time; using a local alive2 build with a relatively large timeout (`-smt-to=9000000`) still times out.

The input tries to prove that it is safe to perform some math using `i16` types instead of `i32`.

https://alive2.llvm.org/ce/z/XY-Bk2

```
define i8 @src(i8 %a, i8 %b, i8 %c) {
  %conv = zext i8 %c to i32
  %sub = xor i32 %conv, 255
  %conv6 = zext i8 %a to i32
  %mul = mul i32 %sub, %conv6
  %conv9 = zext i8 %b to i32
  %mul10 = mul i32 %conv9, %conv
  %add = add i32 %mul10, %mul
  %div = udiv i32 %add, 255
  %conv11 = trunc i32 %div to i8
  ret i8 %conv11
}

define i8 @tgt(i8 %a, i8 %b, i8 %c) {
  %conv = zext i8 %c to i16
  %sub = xor i16 %conv, 255
  %conv6 = zext i8 %a to i16
  %mul = mul i16 %sub, %conv6
  %conv9 = zext i8 %b to i16
  %mul10 = mul i16 %conv9, %conv
  %add = add i16 %mul10, %mul
  %div = udiv i16 %add, 255
  %conv11 = trunc i16 %div to i8
  ret i8 %conv11
}
```

Unless I am missing something, the Python snippet below checks the equivalence for all possible i8 inputs and completes in < 1 minute on the same system where Alive2 times out.

```
def check(a, b, c):
    sub = 255 - c
    return ((a * sub) + (b * c))/255

def check_limit(a, b, c):
     sub = 255 - c
     return (((((a * sub) % 2**16) + ((b * c) % 2**16)) % 2 ** 16)/255)

 for a in range(0, 256):
     for b in range(0, 256):
         for c in range(0, 256):
            assert(check(a, b, c) == check_limit(a, b, c))
```

**Comment by fhahn** [comment]
Interestingly having the same code for `@src` and `@tgt` also times out: https://alive2.llvm.org/ce/z/3MnqUy . I didn't try this locally though.

**Comment by nunoplopes** [comment]
The problem is undef. If you run with `-disable-undef-input`, Alive2 is also pretty quick.
Reasoning about undef is pretty complicated: requires quantifiers and Z3 is not always smart about them. You're right that sometimes brute-force is faster, but Z3 doesn't have that smartness built-in.

I don't have any student working Alive2 right now. And it's unlikely any will show up this year, so I can't handle larger projects like improving Z3, sorry.
This bug report is related: https://github.com/Z3Prover/z3/issues/6299. Both can be solved by making Z3 learning about inversibility of bit-vector operators,

**Comment by fhahn** [comment]
Thanks for taking a look! `-disable-undef-input` is indeed much quicker.

It looks like https://github.com/Z3Prover/z3/issues/6299 is already fixed, so maybe the situation is already better in recent Z3?

**Comment by nunoplopes** [comment]
No, it wasn't fixed. See the comment in the closing commit: https://github.com/Z3Prover/z3/commit/6c165e89dcc88da56f7fdc8a51349478f0574947
It does give a blueprint to fix these invertible cases, but that's all.
