### ISSUE TITLE
Transform incorrectly reported as correct with nsz

### ISSUE THREAD

**Issue by arsenm** [AliveToolkit/alive2#854]
https://alive2.llvm.org/ce/z/vpFPxG

The following transform is reported as correct if the nsz flag is added to the fdiv:
```
define float @src(float %x) {
  %fdiv = fdiv nnan nsz float %x, 0.0
  ret float %fdiv
}

define float @tgt(float %x) {
  ret float 0x7FF0000000000000
}
```

Without the nsz, this is correctly rejected:

```
define float @src(float %x) denormal-fp-math=ieee,ieee {
%0:
  %fdiv = fdiv nnan float %x, 0.000000, exceptions=ignore
  ret float %fdiv
}
=>
define float @tgt(float %x) denormal-fp-math=ieee,ieee {
%0:
  ret float inf
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:
float %x = #xc0000008 (-2.000001907348?)

Source:
float %fdiv = #xff800000 (-oo)

Target:
Source value: #xff800000 (-oo)
Target value: #x7f800000 (+oo)
```

The counterexample is not a signed zero, so the nsz flag shouldn't be relevant.

**Comment by nunoplopes** [comment]
Note that nsz also applies to the constant 0.
The semantics is that we have to evaluate the fdiv with either 0 or -0. If you unroll it manually, we get this: https://alive2.llvm.org/ce/z/Z--77U
Which Alive2 says it's correct. So I think there's no bug here.
