### ISSUE TITLE
Transform that breaks sign of infinity incorrectly accepted

### ISSUE THREAD

**Issue by arsenm** [AliveToolkit/alive2#855]
Transforming fdiv nnan nsz x, 0 -> +inf is incorrectly reported as correct. The sign of the result should match the sign of the numerator, so fdiv nnan nsz -inf, 0 should be -inf

https://alive2.llvm.org/ce/z/P2ucrd
https://reviews.llvm.org/D136097

```
define float @src(float %x) {
  %fdiv = fdiv nnan nsz float %x, 0.0
  ret float %fdiv
}


define float @tgt(float %x) {
  ret float 0x7FF0000000000000
}

```
```
=>
define float @tgt(float %x) denormal-fp-math=ieee,ieee {
%0:
  ret float inf
}
Transformation seems to be correct!
```

**Comment by nunoplopes** [comment]
Alive2 is correct. I've left a comment in the LLVM patch.
nsw applies to both inputs and outputs of instructions.
