### ISSUE TITLE
llvm.canonicalize not supported

### ISSUE THREAD

**Issue by arsenm** [AliveToolkit/alive2#856]
https://alive2.llvm.org/ce/z/j_3eQA

ERROR: Couldn't prove the correctness of the transformation
Alive2 approximated the semantics of the programs and therefore we
cannot conclude whether the bug found is valid or not.

Approximations done:
 - Unknown libcall: @llvm.canonicalize.f32

**Comment by arsenm** [comment]
It's fuzzily defined but I'd expect it to be interpreted as quieting signaling nans and respecting denormal-fp-math

**Comment by nunoplopes** [comment]
Alive2 doesn't support signaling NaNs at the moment, so the work involved is a bit more involved than usual. So I can't promise an ETA for this functionality.

**Comment by nunoplopes** [comment]
I'm not an expert in floats, so the implementation may not be air tight. Please let me know if you find any issues. Thanks!
