### ISSUE TITLE
Store into pointer pointer introduces poison everywhere

### ISSUE THREAD

**Issue by katrinafyi** [AliveToolkit/alive2#859]
It seems that the presence of instructions like this:
```llvm
%MEMORY = alloca i64*, align 8
store i64* undef, i64** %MEMORY, align 8
```
will introduce poison in many unexpected places. 

For example, in the code below (https://alive2.llvm.org/ce/z/A4PRXh), these lines poison %use in _both_ src and tgt even with --disable-poison-input set.
```llvm
; --disable-undef-input --disable-poison-input
@X2 = global i64 0

define void @src() {
  %use = load i64, i64* @X2, align 8
  ret void
}

define void @tgt() {
  %use = load i64, i64* @X2, align 8

  %MEMORY = alloca i64*, align 8
  store i64* undef, i64** %MEMORY, align 8

  ; gadget to reveal poison values by introducing UB
  %i = icmp eq i64 %use, 0
  br i1 %i, label %end, label %end
end:
  ret void
}
```

This is unexpected, assuming that merely storing a value into a local variable should not affect anything else, and it certainly shouldn't affect the src. It happens regardless of where in the source or target these lines are placed, and regardless of the particular pointer stored. It does seem to only happen when the value stored is a pointer. 

What could be happening here and is it the expected behaviour? Why is this able to contradict --disable-poison-input?

**Comment by nunoplopes** [comment]
Something is wrong, yes. Thank you for the report!

We insert an axiom stating that memory cannot be poison here: https://github.com/AliveToolkit/alive2/blob/68a9e3b260aeba9f57814d01c9cc150f5e6c0e35/ir/memory.cpp#L1075-L1088

But it seems something is not working properly..

**Comment by nunoplopes** [comment]
Ok, so the bug was elsewhere.
It was in an optimization to shrink consider memory bytes are always non-pointers if there's no load/store with ptr type.
The deal is that type punning in LLVM yields poison. So if you load an integer, but someone stored a non-poison pointer there, you'll still get poison back.
