### ISSUE TITLE
False negative with compare of GEPs with negative offset

### ISSUE THREAD

**Issue by fhahn** [AliveToolkit/alive2#862]
Currently Alive2 verifies the snippet below as correct. I might be missing something, but shouldn't that fail verification. 

Assume `%dst == 1`, then 

* `%dst + 3 == 4`
* `%dst + 3 - (8 * 1) == -4`, 
* `icmp ule -4, 1 == false`

https://alive2.llvm.org/ce/z/GmeMWX

```
define i1 @src(ptr %dst) {
  %dst.add.3 = getelementptr inbounds i8, ptr %dst, i64 3
  %sub = getelementptr inbounds i64, ptr %dst.add.3, i64 -1
  %cmp = icmp ule ptr %sub, %dst
  ret i1 %cmp
}

define i1 @tgt(ptr %dst) {
  ret i1 true
}
```

**Comment by LebedevRI** [comment]
Isn't `%sub` must be at least `ugt null`, because you can't create nullptr,
can't wrap around, and null isn't a valid pointer in your case so no valid object can start at that offset?

**Comment by nunoplopes** [comment]
The second getp has `inbounds`, so it would given poison in the example you mention. 
If you remove `inbounds`, Alive2 reports a counterexample that is similar to your example 🙂

**Comment by fhahn** [comment]
Ah right, that's what I missed, thanks!
