### ISSUE TITLE
Alive2 seems to ignore implicit truncate for GEPs.

### ISSUE THREAD

**Issue by fhahn** [AliveToolkit/alive2#863]
It looks like Alive2 doesn't properly model implicit truncates of GEP indices.

The following example with implicit truncation of the GEP index `%off` to `i32` is verified as correct, while the same version with explicit truncate doesn't verify (as expected).

* Implicit truncate: https://alive2.llvm.org/ce/z/cLiY2i
* Explicit truncate: https://alive2.llvm.org/ce/z/LkHEFM

```
target datalayout = "p:32:32:32"

declare void @llvm.assume(i1)

define i1 @src(ptr %dst, i64 %off) {
  %pos = icmp sge i64 %off, 0
  call void @llvm.assume(i1 %pos)
  %gep.off = getelementptr inbounds i8, ptr %dst, i64 %off
  %cmp = icmp ule ptr %dst, %gep.off
  ret i1 %cmp
}

define i1 @tgt(ptr %dst, i64 %off) {
  ret i1 true
}
```

**Comment by nunoplopes** [comment]
I think this behavior is correct. The 2 programs (with and without trunc) are not equivalent.
LangRef says the following regarding gep being poison:
> If the type of an index is larger than the pointer index type, the truncation to the pointer index type preserves the signed value.

The assume forces `%off` to be >= 0 (64 bits). But the gep would be poison if the offset wasn't positive as well (32 bits).
Given that the gep is inbounds, and we have a positive offset, there's no overflow, and thus p+off >= p.
