### ISSUE TITLE
Mishandling of constant folded llvm.is.fpclass with nans

### ISSUE THREAD

**Issue by arsenm** [AliveToolkit/alive2#864]
alive-tv is rejecting any constant folding of is.fpclass on nans. It
must fold to true or false, but it says all of these are wrong. The
false cases error saying the counter example is true. If you invert
the return value, it says the counter example is false.

Is it trying to evaluate both IEEE specified signaling vs. quiet and
old mips style and complaining for one or the other or something?

https://alive2.llvm.org/ce/z/qHfNAU

```
; isqnan(qnan) -> true
define i1 @src() {
  %val = call i1 @llvm.is.fpclass.f64(double 0x7FF8000000000000, i32 2)
  ret i1 %val
}

define i1 @tgt() {
  ret i1 true
}

; issnan(snan) -> false
define i1 @src() {
  %val = call i1 @llvm.is.fpclass.f64(double 0x7FF0000000000001, i32 1)
  ret i1 %val
}

define i1 @tgt() {
  ret i1 false
}

; issnan(qnan) -> false
define i1 @src() {
  %val = call i1 @llvm.is.fpclass.f64(double 0x7FF8000000000000, i32 1)
  ret i1 %val
}

define i1 @tgt() {
  ret i1 false
}


; isqnan(snan) -> false
define i1 @src() {
  %val = call i1 @llvm.is.fpclass.f64(double 0x7FF0000000000001, i32 2)
  ret i1 %val
}

define i1 @tgt() {
  ret i1 false
}

declare i1 @llvm.is.fpclass.f64(double, i32 immarg)


```

**Comment by nunoplopes** [comment]
This behavior is correct, I think.

There's no specification for what the quiet and signaling payloads are, as they differ between platforms. Thus, we have to model it as non-deterministic.
If you change the last argument to 3, you can fold the NaN detection to true, as Alive2 realizes that a NaN must be either quiet or signaling.

The only way to fold these checks is to maybe add information to the Data Layout, to specify the signal bit or whatever.
Or you can fold patterns like this: https://alive2.llvm.org/ce/z/Ko8mv3  (not sure it's very interesting in practice, though)

**Comment by arsenm** [comment]
> There's no specification for what the quiet and signaling payloads are, as they differ between platforms. Thus, we have to model it as non-deterministic.

IEEE-754 2008 and 2019 prescribe the highest bit of the signifcand as indicating quietness. This is a question of how much water do we want to carry for antique mips targets for correct snan handling in a compiler that mostly doesn't model them.

**Comment by nunoplopes** [comment]
Ok, thank you! Please CC me so I know if there's anything to tweak here.
