### ISSUE TITLE
Wrong result for and when data type is less than 32bits

### ISSUE THREAD

**Issue by bcl5980** [AliveToolkit/alive2#865]
https://alive2.llvm.org/ce/z/qLstcM

```
define i1 @src(i16 %a) {
  %cmp1 = icmp eq i16 %a, 15
  %cmp2 = icmp eq i16 %a, 47
  %r = or i1 %cmp1, %cmp2
  ret i1 %r
}

```

This transform should be correct. But alive2 say it is wrong if the data type is less than 32btis.
And it looks the `and` value is wrong.

**Comment by nunoplopes** [comment]
It works for me locally.
@regehr it seems the VM has a badly broken version of Z3. Is it a release or was it compiled from git?

**Comment by nunoplopes** [comment]
It's working now. Thanks John!
