### ISSUE TITLE
Did alive recently get slower?

### ISSUE THREAD

**Issue by nikic** [AliveToolkit/alive2#866]
I recently started to get timeouts (in the online instance) for simple, low-bitwidth proofs, such as https://alive2.llvm.org/ce/z/5Pq-eb. Adding `-disable-undef-input` makes the instantaneous again, but I'm pretty sure this used to be fast without the flag until recently.

**Comment by nikic** [comment]
Slightly simplified example also times out: https://alive2.llvm.org/ce/z/GXds9f

And this one (which should not verify) produces an SMT error: https://alive2.llvm.org/ce/z/fBnC5x

> ERROR: SMT Error: smt tactic failed to show goal to be sat/unsat (incomplete quantifiers)

**Comment by nunoplopes** [comment]
@regehr, these examples work for me locally. Can you update the Z3 library on the VM pls?

**Comment by regehr** [comment]
sure, I'll build a new Z3+Alive2 today. I think this is the same issue I mentioned to you, Nuno, not sure what's going on.

**Comment by regehr** [comment]
ok, this is installed, please try again -- it's a fresh version of everything: Z3, LLVM, Alive2

**Comment by nunoplopes** [comment]
Seems to be working fine now. Thanks John!
