### ISSUE TITLE
Sub-byte globals with align 1 expose padding behaviour

### ISSUE THREAD

**Issue by katrinafyi** [AliveToolkit/alive2#882]
https://alive2.llvm.org/ce/z/NGHjN6

```llvm
@X2 = global i1 0, align 1

define void @src() {
    %use = load i1, ptr @X2, align 1, !noundef !{}
    ret void
}

define void @tgt() {
    %use = load i1, ptr @X2, align 1, !noundef !{}
    store i1 %use, ptr @X2, align 1
    ret void
}
```
```
Mismatch in pointer(non-local, block_id=0, offset=0)
Source value: #x02
Target value: #x00
```

Loading then storing the same value seems to zero some padding bits, which then compare not-equal. This mismatch does not happen if the variable is larger than a byte or if align is >1.

I assume the specific padding of i1 is architecture-dependent, but effects to this inaccessible padding shouldn't be part of the reasoning?

**Comment by nunoplopes** [comment]
Dup of #783.

BTW,  introducing stores is not legal in general. It's not something that Alive2 checks for yet, but your example shouldn't be marked as correct due to introducing a store to a global that wasn't present in the original program.
