### ISSUE TITLE
ASM memory model

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#896]
There's a need for an assembly memory model.
Essentially, it needs to treat pointers as addresses, not as block id + offset.
It also needs to allow type punning through memory:
```llvm
define void @src(ptr %0) {
  %2 = load ptr, ptr %0, align 8
  store i64 0, ptr %2, align 4
  ret void
}

define void @tgt(ptr %0) {
  %x = load i64, ptr %0, align 1
  %y = inttoptr i64 %x to ptr
  store i64 0, ptr %y, align 1
  ret void
}
```

For now, we have `-enable-approx-int2ptr`, but this should be replaced with a `-tgt-mem-model=asm` or something like that.

@regehr

**Comment by nunoplopes** [comment]
Perf test from John:
```llvm
define ptr @src(ptr noundef %0, i64 noundef %1) {
2:
   %_t = trunc i64 %1 to i32
   %3 = getelementptr inbounds i8, ptr %0, i32 8
   store i32 %_t, ptr %3, align 4
   ret ptr %3
}

define ptr @tgt(ptr noundef %0, i64 noundef %1) {
i32_8:
   %2 = ptrtoint ptr %0 to i64
   %a0_38 = freeze i64 %1
   %a0_39 = trunc i64 %a0_38 to i32
   %a0_44 = add i64 %2, 8
   %3 = inttoptr i64 %a0_44 to ptr
   store i32 %a0_39, ptr %3, align 1
   ret ptr %3
}
```

**Comment by nunoplopes** [comment]
The first example doesn't fail anymore with the new flag `-tgt-is-asm`, but it times out.
The int2ptr isn't very efficient and align=1 also makes the encoding a nightmare.
This needs a lot more work..

**Comment by nunoplopes** [comment]
Alive2 can now prove both examples. I need more complicated benchmarks please 🙂

**Comment by regehr** [comment]
awesome!!!! sorry, I got behind due to being overseas all last week, I'll dig stuff up soon!

**Comment by regehr** [comment]
ok, I'm updating arm-tv. if I understand correctly, I just unconditionally set the new `tgt_is_asm` flag and I can also remove the old `enable_approx_int2ptr` stuff?

**Comment by nunoplopes** [comment]
> ok, I'm updating arm-tv. if I understand correctly, I just unconditionally set the new `tgt_is_asm` flag and I can also remove the old `enable_approx_int2ptr` stuff?

Yes!

**Comment by regehr** [comment]
I'm getting quite a few test failures in the arm-tv branch due to this assertion failing:

`Assertion failed: (bytes.size() == bits_program_pointer / bits_byte), function bytesToValue, file memory.cpp, line 486.`

I'll report this in a separate issue, but first I need to take a bit of time to make sure I can repro this properly on the main branch
