### ISSUE TITLE
[bug] The control flow processing is incorrect.

### ISSUE THREAD

**Issue by vfdff** [AliveToolkit/alive2#901]
[test](https://alive2.llvm.org/ce/z/3BBPS_)

 * in the function @src, we use **[ false, %2 ]** in label 16
 * in the function @target, we use **[ true, %2 ]** in label 16

So it is clear they have different logic, why this is proved correctly

**Comment by nunoplopes** [comment]
Try this one instead: https://alive2.llvm.org/ce/z/dmXY4i

The target function should be called tgt, not target.

**Comment by vfdff** [comment]
Thanks
