### ISSUE TITLE
building alive2 on m1: ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by liamsemeria** [AliveToolkit/alive2#907]
Im trying to build dependencies for google/souper, and when the make file is trying to build alive2 it stops here:

[15/46] Building CXX object CMakeFiles/ir.dir/ir/instr.cpp.o
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/instr.cpp:4:
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/instr.h:6:
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/value.h:7:
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:6:
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/memory.h:111:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>(const AliasSet &rhs) const = default;
         ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/memory.h:89:23: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'local'
    std::vector<bool> local, non_local;
                      ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/memory.h:224:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>(const CallState &rhs) const = default;
         ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/memory.h:216:28: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'non_local_block_val'
    std::vector<smt::expr> non_local_block_val;
                           ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/memory.h:324:8: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
  auto operator<=>(const Memory &rhs) const = default;
       ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/memory.h:132:25: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'non_local_block_val'
  std::vector<MemBlock> non_local_block_val;
                        ^
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/instr.cpp:4:
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/instr.h:6:
In file included from /Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/value.h:7:
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:88:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>(const VarArgsData &rhs) const = default;
         ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:85:39: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'data'
    std::map<smt::expr, VarArgsEntry> data;
                                      ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:160:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>(const FnCallInput &rhs) const = default;
         ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:145:29: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'args_nonptr'
    std::vector<StateValue> args_nonptr;
                            ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:173:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>(const FnCallOutput &rhs) const = default;
         ^
/Users/Liam/Desktop/Projects/research/take2/souper/third_party/alive2/ir/state.h:164:29: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'retvals'
    std::vector<StateValue> retvals;
                            ^
6 warnings generated.
ninja: build stopped: subcommand failed.

It gets errors earlier on such as:

In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/set:440:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__tree:2027:35: error: no matching function for call to object of type 'std::__tree<std::__value_type<IR::State::FnCallInput, IR::State::FnCallOutput>, std::__map_value_compare<IR::State::FnCallInput, std::__value_type<IR::State::FnCallInput, IR::State::FnCallOutput>, std::less<IR::State::FnCallInput>, true>, std::allocator<std::__value_type<IR::State::FnCallInput, IR::State::FnCallOutput>>>::value_compare' (aka 'std::__map_value_compare<IR::State::FnCallInput, std::__value_type<IR::State::FnCallInput, IR::State::FnCallOutput>, std::less<IR::State::FnCallInput>, true>')
        if (__prior == begin() || value_comp()(*--__prior, __v))
                                  ^~~~~~~~~~~~
I suspect that this has something to do with the c++ version apple-clang uses. Has anyone gotten alive2 built on their m1 macs? If so did you run into this issue?
I'm new to creating issues for open source projects, would it be better to post this on google/souper instead?
Thanks.

**Comment by regehr** [comment]
I just built the latest alive2 on my M1 Mac using `Apple clang version 14.0.3 (clang-1403.0.22.14.1)`

the alive2 that's part of souper is a bit old. Nuno's not going to be interested in supporting it. I'll talk to me student who did the souper-alive2 integration and see if he'll update souper's alive2, at which point presumably it will work for both of us

**Comment by nunoplopes** [comment]
dup of #903. You need a more recent compiler.

**Comment by regehr** [comment]
I can also build using top-of-tree LLVM. I can't build alive2 using g++-13 from homebrew, but it dies with vtable-related linker errors, not spaceship problems
