### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by tanmaytirpankar** [AliveToolkit/alive2#924]
For the following test Alive says that value in %3 for target is 31 which seems incorrect after you look at Alive's output. Looking at the output, although %0 contains an `undef` value, looking at the first element of the final return vector, we see that %0 seems to be 0. So when you perform AND operation with 0, the result should be 0, however the output shows the result is 31.

[Alive2 Online Compiler Link with Test](https://alive2.llvm.org/ce/z/LqCsEW)

define <2 x i32> @src(i32 %0, i32 %1) {
  %3 = srem i32 %0, 32
  %4 = insertelement <2 x i32> undef, i32 %0, i64 0
  %5 = insertelement <2 x i32> %4, i32 %3, i64 1
  ret <2 x i32> %5
}

define <2 x i32> @tgt(i32 %0, i32 %1) {
  %3 = and i32 %0, 31
  %4 = or i32 %0, 4294967264
  %5 = icmp eq i32 %3, 0
  %6 = select i1 %5, i32 %3, i32 %4
  %7 = icmp slt i32 %0, 0
  %8 = select i1 %7, i32 %6, i32 %3
  %9 = insertelement <2 x i32> undef, i32 %0, i64 0
  %10 = insertelement <2 x i32> %9, i32 %8, i64 1
  ret <2 x i32> %10
}

**Comment by regehr** [comment]
are you saying that two uses of an undef value are returning two different values? if so, that's absolutely how undef works

**Comment by tanmaytirpankar** [comment]
Thanks. It makes sense. I was confused about undef here.

**Comment by regehr** [comment]
a general rule is that it is almost never OK to increase the number of uses of an SSA variable, unless you can prove that it is not undef (for example by freezing it)

but also we hope that undef is going away. your transformation works if you provide the `--disable-undef-input` flag, which also makes Alive2 much faster, in many cases

**Comment by sridhargopinath** [comment]
> are you saying that two uses of an undef value are returning two different values?

Hi, let me ask a follow-up question. I think the confusion here is not on the two uses of an undef value. I understand that if an arg `%0` is assigned an undef value and `%0` is used in multiple places across the same function, it can assume different concrete values.

For Alive, if `%0` is the same arg for both src and tgt function and `%0` is assigned an undef value, my understanding is that it should assume the same value for the same use across the two functions. In the above code, Alive assigned an undef input for `%0`. However, there does not seem to be any concrete value for `%0` that produces 0 in `%3` in src and `0x1f` in `%3` in tgt.
Am I missing something?

**Comment by nunoplopes** [comment]
Alive2 is free to pick any value for undef arguments. They may be different in source and target.
The correction criteria is that if target returns value 'x' for some undef input, then source must be able to return that value for some undef value. But the undef values don't have to be the same.
Any use of an undef may yield any value.

**Comment by regehr** [comment]
just to be perfectly clear here: Nuno is explaining the consensus view on how undef works among LLVM people. this isn't something that we chose to do just for alive2

**Comment by sridhargopinath** [comment]
Thanks for the explanations, this is really helpful.

I think I understand the root cause for the above test case better. In the `tgt` function, there are two uses of `%0`. As per LLVM semantics, these two uses could be two different concrete values. Through that, Alive generated `-32` as the result for `tgt`. However, there's no concrete value for `%0` in `src` that can generate `-32`. As per Alive's verification condition, this is incorrect and thus the transformation is marked as incorrect.

To fix this while allowing checks for undef, we would have to freeze multiple uses of `%0` in `tgt`. Indeed, after adding `%t1 = freeze i32 %0` to `tgt`, transformation is verified.

If we remove undef behavior by adding `--disable-undef-input`, then without any changes to the code, transformation verifies.

**Comment by sridhargopinath** [comment]
@nunoplopes I do have a question about Alive's verification condition for undef inputs. You mentioned that for some evaluation of undef in `tgt`, there has to be at least one evaluation of the same input in `src` to verify the transformation. Is this verification condition weaker than assuming the same evaluation of undef in both `src` and `tgt`?

**Comment by nunoplopes** [comment]
> @nunoplopes I do have a question about Alive's verification condition for undef inputs. You mentioned that for some evaluation of undef in `tgt`, there has to be at least one evaluation of the same input in `src` to verify the transformation. Is this verification condition weaker than assuming the same evaluation of undef in both `src` and `tgt`?

Assuming that undef evaluates to the same value in both programs would miss some cases. It's not a correct criteria.
The refinement criteria states that all behaviors of tgt must be included in the behaviors of src, for whatever non-determinism they may have (incl undef). Limiting the non-determinism results in under-approximating the set of possible behaviors.
