### ISSUE TITLE
Can we make the assumptions like 

### ISSUE THREAD

**Issue by UmeshKalappa0** [AliveToolkit/alive2#925]
Hi ,
We have the instance  i.e https://alive2.llvm.org/ce/z/ei2YsT .

and tool says like  
----------------------------------------
```llvm
define i32 @foo(i32 noundef %f32In) {
%entry:
  %shl = shl i32 noundef %f32In, 1
  %cond = abs i32 %shl, 1
  %sub1 = sub nsw i32 0, %cond
  %conv = sext i32 %sub1 to i64
  %mul = mul nsw i64 %conv, %conv
  %shr = lshr i64 %mul, 31
  %conv3 = trunc i64 %shr to i32
  %cmp4 = icmp eq i32 %conv3, 2147483648
  %cond9 = select i1 %cmp4, i32 2147483647, i32 %conv3
  ret i32 %cond9
}
=>
define i32 @foo(i32 noundef %f32In) {
%entry:
  %shl = shl i32 noundef %f32In, 1
  %cond = abs i32 %shl, 1
  %sub1 = sub nsw i32 0, %cond
  %conv = sext i32 %sub1 to i64
  %mul = mul nsw i64 %conv, %conv
  %shr = lshr i64 %mul, 31
  %conv3 = trunc i64 %shr to i32
  %cond9 = select i1 0, i32 2147483647, i32 %conv3
  ret i32 %cond9
}
Transformation seems to be correct!
 
Lets take example %f32In = 0x40000000 and i32 is 4 bytes .
%shl = 0x80000000
%cond = 0x80000000
%sub1 = 0x80000000
%conv = 0xffffffff80000000
%mul = 0x4000000000000000
%shr = 0x0000000000000000
 %conv3 =  0x00000000
```

not equal to  0x80000000 and transformation is right and we return %conv3 i.e 0 and great 

Question is that ,from above IR ,we can always says like 
/* multiplication of two negative number is always positive  */
%mul = mul nsw i64 %conv, %conv
/* left shift i64 to 31 bits is  always positive  ,not right like 0x7fffffff00000000 >>31 is 0000000080000000 */
  %shr = lshr i64 %mul, 31
/* 0000000080000000  to 80000000  and $conv3 can be negative */ 
  %conv3 = trunc i64 %shr to i32

and llvm have the interferce  like 
  %sub1 = sub nsw i32 0, %cond

Here we are assuming that  %sub1 is not poison value  and  we think the alive is reasoning with false positive or we are missing any llvm  rationale behind like poison values here  on branch /select  ,we tried get hold on these poison values and map to our C like standard but with no luck.

Any comments or suggestions ,will help us to understand problem better .

Thank you

**Comment by nunoplopes** [comment]
I think the mistake in your argument is here:
```
%mul = 0x4000000000000000
%shr = 0x0000000000000000
```

The value of `%shr` is not 0. It's 0x80000000.

Other things to keep is mind are:
 - shl nsw yields poison if there's a sign overflow
 - abs(x, true) yields poison for INT_MIN

So LLVM's transformation is correct because it's taking advantage of the undefined behavior your function has.

**Comment by UmeshKalappa0** [comment]
@nunoplopes  ,thank you quick response and 

>>The value of %shr is not 0. It's 0x80000000.
ok ,mybad and in that case my argument sound sense like 

 %conv3 = trunc i64 %shr to i32
/*%conv 3 = 0x80000000 */
%cmp4 = icmp eq i32 %conv3, 2147483648
/*%comp4 is true here */
  %cond9 = select i1 0, i32 2147483647, i32 %conv3
/*%cond9 =  0x80000000 */

>>abs(x, true) yields poison for INT_MIN 
but lets consider  the  our abs() implementation  don't change the underlying object  sign bit and 
>>shl nsw yields poison if there's a sign overflow
for the input  like 0x40000000 ,the shl nsw don't overflow .

So we trying with all possible inputs and understanding the poison semantics in llvm and what use of  this poison value can trigger the  overflow and does this poison values are tied with certain operations  like select or function call or any  arth operator ?

**Comment by nunoplopes** [comment]
There are many operations that can yield poison or trigger UB. You can read the manual here: https://llvm.org/docs/LangRef.html

There's a tool called `alive-exec` that can help you understand where poison is coming from. Unfortunately it's not available online yet. You've to compile Alive2 by hand.
See the ouput:
```llvm
$ alive-exec file.ll

define i32 @foo(i32 noundef %f32In) {
%entry:
  %shl = shl i32 1073741824, 1 ;; your test input (0x40000000)
  %cond = abs i32 %shl, 0   ;; I changed this to false
  %sub1 = sub nsw i32 0, %cond
  %conv = sext i32 %sub1 to i64
  %mul = mul nsw i64 %conv, %conv
  %shr = lshr i64 %mul, 31
  %conv3 = trunc i64 %shr to i32
  %cmp4 = icmp eq i32 %conv3, 2147483648
  %cond9 = select i1 %cmp4, i32 2147483647, i32 %conv3
  ret i32 %cond9
}
i32 %shl = #x80000000 (2147483648, -2147483648)
i32 %cond = #x80000000 (2147483648, -2147483648)
i32 %sub1 = poison
i64 %conv = poison
i64 %mul = poison
i64 %shr = poison
i32 %conv3 = poison
i1 %cmp4 = poison
i32 %cond9 = poison
Returned: poison
```

**Comment by UmeshKalappa0** [comment]
@nunoplopes ,
>> %sub1 = sub nsw i32 0, %cond
Really alteast in x86 ,its generates neg inst like 
neg %cond

which is 2's complement of 0x80000000  i.e  " 0x80000000" 
and looked at CSR flag for overflow ,and for our curious is not set .

and  0x80000000 is representable value in X86.

**Comment by nunoplopes** [comment]
> @nunoplopes ,
> 
> > > %sub1 = sub nsw i32 0, %cond
> > > Really alteast in x86 ,its generates neg inst like
> > > neg %cond
> 
> which is 2's complement of 0x80000000 i.e " 0x80000000" and looked at CSR flag for overflow ,and for our curious is not set .
> 
> and 0x80000000 is representable value in X86.

The semantics of x86 assembly are irrelevant for this discussion. We are talking about LLVM IR here.

See the manual no sub: https://llvm.org/docs/LangRef.html#sub-instruction

> nuw and nsw stand for “No Unsigned Wrap” and “No Signed Wrap”, respectively. If the nuw and/or nsw keywords are present, the result value of the sub is a [poison value](https://llvm.org/docs/LangRef.html#poisonvalues) if unsigned and/or signed overflow, respectively, occurs.

**Comment by UmeshKalappa0** [comment]
Thank you @nunoplopes  and sorry for bothering you again 
>> LLVM integers use a two’s complement representation, this instruction is appropriate for both signed and unsigned integers.

>>The semantics of x86 assembly are irrelevant for this discussion. We are talking about LLVM IR here.
True and  we are trying to understand LLVM IR semantics w.r.t the sub operation along nsw here  
>>%sub1 = sub nsw i32 0, %cond
any signed number sN is  subtracted by zero  is that two’s complement representation i.e sN again and don't overflow .

**Comment by nunoplopes** [comment]
`0 - INT_MIN` is not representable in two's complement (since INT_MAX == -INT_MIN-1), hence it's defined as poison when the `nsw` tag is present.
For all other values, `sub nsw` returns a "normal" value.

**Comment by UmeshKalappa0** [comment]
@nunoplopes 
>>0 - INT_MIN is not representable in two's complement (since INT_MAX == -INT_MIN-1 hence it's defined as poison when the nsw tag is present.
Agree ,but how llvm transformation generalize this kind of assumption made ,like  "0 - INT_MIN ie %cond = INT_MIN " is poison totally agree and we are good  ,but for  %cond other values its not case right and making assumption for other inputs of %cond  is not valid right ?

**Comment by nunoplopes** [comment]
Sure, a transformation needs to be correct for any input. And it is.
LLVM is not making any assumption for the sub for other inputs.
