### ISSUE TITLE
should it invalid for divided by 0 ?

### ISSUE THREAD

**Issue by vfdff** [AliveToolkit/alive2#946]
* test: https://alive2.llvm.org/ce/z/NHSHSZ
```
define i4 @src(i4 %a) {
  %lhs = shl nuw i4 %a, 3
  %rhs = shl nuw i4 %a, 1

  %div = udiv i4 %lhs, %rhs
  ret i4 %div
}

define i4 @tgt(i4 %a) {
  %sub = sub nuw i4 3, 1
  %res = shl nuw i4 1, %sub
  ret i4 %res
}
```

* when the %a is 0, the result of @src is 0/0, which is a UB ?
  so the above case should not return correct for alive2 ?

**Comment by nunoplopes** [comment]
When `%a` is 0, the source function is UB. That means that the compiler is allowed to rewrite it in any way it wants. UB in source enables optimizations; it doesn't cause verification to fail.
On the other hand, UB in target is more dangerous. It fails verification, unless source was already UB for the same inputs.
