### ISSUE TITLE
Add lit test support for opt plugin & alive-tv

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#95]
Required for e.g. https://github.com/AliveToolkit/alive2/pull/88 because the parser doesn't have support for load/store, etc yet.

**Comment by nunoplopes** [comment]
Support for `alive-tv` tests committed in https://github.com/AliveToolkit/alive2/commit/6327fe3b463a3c66c93f1a15797d89ded21d213e

**Comment by aqjune** [comment]
This seems easy for me to implement (hopefully)
