### ISSUE TITLE
Alive2 recognized infinite empty loop as flat ret

### ISSUE THREAD

**Issue by XChy** [AliveToolkit/alive2#952]
For an empty infinite loop, it make function not return at all. But Alive2 see it as a willreturn function.
It may be semantically wrong?

```llvm
define void @src1() {
entry:
  br label %entry
}

define void @tgt1() {
entry:
  ret void
}
```

https://alive2.llvm.org/ce/z/xEAHDc

**Comment by nunoplopes** [comment]
Alive2 doesn't support infinite loops without at least a function call inside. This is a known limitation, I'm afraid.
