### ISSUE TITLE
Alignment check when bytes is zero

### ISSUE THREAD

**Issue by Dongjoo-Kim** [AliveToolkit/alive2#98]
When bytes is zero, any pointer is dereferenceable in this implementations.
However, alignment must be checked if bytes is zero in LLVM Language Reference.
```If “len” is 0, the pointers may be NULL or dangling. However, they must still be appropriately aligned.```

Because giving alignment for memcpy and memset instructions is not implemented, I can't check it.
Though, in my opinion, we have to modify the code.

**Comment by nunoplopes** [comment]
Sounds good. Do you want to send a patch to fix this? Thanks!

**Comment by nunoplopes** [comment]
Fixed in https://github.com/AliveToolkit/alive2/commit/c4fad9ef5d08bf7634f65b10bb51f8fedefd71f9
