### ISSUE TITLE
`--print-options` and `--print-all-options` don’t.

### ISSUE THREAD

**Issue by FlashSheridan** [AliveToolkit/alive2#999]
`$ALIVE2_HOME/alive2/build/alive-tv --help-list-hidden` lists the following options:

```
  --print-all-options            - Print all option values after command line parsing
  --print-options                - Print non-default options after command line parsing
```

But the following three command give nearly identical output, none of them including option values:

* `$ALIVE2_HOME/alive2/build/alive-tv --smt-to=90000  $LLVM2_HOME/llvm/test/Transforms/LoopVectorize/runtime-checks-difference.ll`
* `$ALIVE2_HOME/alive2/build/alive-tv  --print-options --smt-to=90000  $LLVM2_HOME/llvm/test/Transforms/LoopVectorize/runtime-checks-difference.ll`
* `$ALIVE2_HOME/alive2/build/alive-tv  --print-all-options --smt-to=90000  $LLVM2_HOME/llvm/test/Transforms/LoopVectorize/runtime-checks-difference.ll`

## Configuration
* Originally found at c06ddaf7, re-checked with b13ec126
* Clang 18 ToT (18.0.0 8f6f5ec77)
* MacOS 13.6.3 22G436 on M1 Max
* MacOSX14.2.sdk
* Xcode 15.1 15C65

## Attachments
* [default passes --print-options runtime-checks-difference.ll.txt](https://github.com/AliveToolkit/alive2/files/13814508/default.passes.--print-options.runtime-checks-difference.ll.txt)
* [default passes not --print-all-options runtime-checks-difference.ll.txt](https://github.com/AliveToolkit/alive2/files/13814509/default.passes.not.--print-all-options.runtime-checks-difference.ll.txt)
* [default passes --print-all-options runtime-checks-difference.ll.txt](https://github.com/AliveToolkit/alive2/files/13814510/default.passes.--print-all-options.runtime-checks-difference.ll.txt)

**Comment by nunoplopes** [comment]
Those cmd options are from LLVM; we don't control them. Can't do anything about them.
We print the cmd options on error only, as that's the case where you usually want to reproduce the problem.
